# Views package for simulate app
from .agent_definition import (
    AgentDefinitionDetailView,
    AgentDefinitionOperationsViewSet,
    AgentDefinitionView,
    CreateAgentDefinitionView,
    DeleteAgentDefinitionView,
    EditAgentDefinitionView,
)
from .run_test import (
    AddEvalConfigView,
    CallExecutionAPIView,
    CallExecutionDetailView,
    CreateRunTestView,
    RunTestAPIView,
    RunTestDetailView,
    RunTestExecutionsView,
    RunTestListView,
    RunTestScenariosView,
    TestExecutionAPIView,
    TestExecutionDetailView,
)
from .scenarios import (
    AddScenarioColumnsView,
    AddScenarioRowsView,
    CreateScenarioView,
    DeleteScenarioView,
    EditScenarioView,
    ScenarioDetailView,
    ScenariosListView,
)
from .simulator_agent import (
    CreateSimulatorAgentView,
    DeleteSimulatorAgentView,
    EditSimulatorAgentView,
    SimulatorAgentDetailView,
    SimulatorAgentListView,
)

__all__ = [
    "ScenariosListView",
    "CreateScenarioView",
    "DeleteScenarioView",
    "EditScenarioView",
    "ScenarioDetailView",
    "AddScenarioRowsView",
    "AddScenarioColumnsView",
    "AgentDefinitionView",
    "CreateAgentDefinitionView",
    "AgentDefinitionDetailView",
    "EditAgentDefinitionView",
    "AgentDefinitionOperationsViewSet",
    "DeleteAgentDefinitionView",
    "SimulatorAgentListView",
    "CreateSimulatorAgentView",
    "SimulatorAgentDetailView",
    "EditSimulatorAgentView",
    "DeleteSimulatorAgentView",
    "RunTestListView",
    "CreateRunTestView",
    "RunTestDetailView",
    "RunTestScenariosView",
    "AddEvalConfigView",
    "RunTestExecutionsView",
    "RunTestAPIView",
    "TestExecutionAPIView",
    "CallExecutionAPIView",
    "TestExecutionDetailView",
    "CallExecutionDetailView",
]
