# Generated by Django 5.1.8 on 2025-07-09 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('model_hub', '0001_initial'),
        ('tracer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationslabels',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations_labels', to='tracer.project'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='annotation_label', to='model_hub.annotationslabels'),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='assigned_users',
            field=models.ManyToManyField(related_name='annotation_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key_org', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autogenerateeventsrun',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_generate_runs', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='clickhouseannotation',
            name='annotation_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickhouse_annotations', to='model_hub.annotationtask'),
        ),
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.column'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='annotation_columns', to='model_hub.column'),
        ),
        migrations.AddField(
            model_name='columnconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_configs', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='customaimodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ai_models', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='customaimodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_org', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='cell',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='datasetinsightmeta',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_dataset_insight_meta', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='datasetinsightmeta',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_insight_meta', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='datasetproperties',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_properties', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='datasetproperties',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='developai',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='develop_ais', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='errorlocalizertask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='evalsettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaltemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_org', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='errorlocalizertask',
            name='eval_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.evaltemplate'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='eval_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluators', to='model_hub.evaltemplate'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentdatasettable',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='experiments_dataset_column', to='model_hub.column'),
        ),
        migrations.AddField(
            model_name='experimentcomparison',
            name='experiment_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.experimentdatasettable'),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.column'),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_dataset', to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='experiments_datasets',
            field=models.ManyToManyField(blank=True, related_name='experiments_datasets_created', to='model_hub.experimentdatasettable'),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentcomparison',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='model_hub.experimentstable'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='eval_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.evaltemplate'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insight',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_insights', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='insight',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='insightstatus',
            name='insight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_status', to='model_hub.insight'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='developai',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.knowledgebase'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='files',
            field=models.ManyToManyField(related_name='knowledge_base_files', to='model_hub.files'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='kb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.knowledgebasefile'),
        ),
        migrations.AddField(
            model_name='metric',
            name='develop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='model_hub.developai'),
        ),
        migrations.AddField(
            model_name='metric',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='default_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaulted_by', to='model_hub.metric'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='monitoralert',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_alerts', to='model_hub.monitor'),
        ),
        migrations.AddField(
            model_name='node',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='model_hub.conversation'),
        ),
        migrations.AddField(
            model_name='node',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='model_hub.message'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_nodes', to='model_hub.node'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='root_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_conversation', to='model_hub.node'),
        ),
        migrations.AddField(
            model_name='optimizationdataset',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimizations_col', to='model_hub.column'),
        ),
        migrations.AddField(
            model_name='optimizationdataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations_dataset', to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='optimizationdataset',
            name='generated_column_id',
            field=models.ManyToManyField(blank=True, related_name='optimization_columns', to='model_hub.column'),
        ),
        migrations.AddField(
            model_name='optimizedataset',
            name='develop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimize_datasets', to='model_hub.developai'),
        ),
        migrations.AddField(
            model_name='optimizedataset',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimize_knowledge_base', to='model_hub.knowledgebase'),
        ),
        migrations.AddField(
            model_name='optimizedataset',
            name='metrics',
            field=models.ManyToManyField(blank=True, null=True, related_name='optimize_dataset', to='model_hub.metric'),
        ),
        migrations.AddField(
            model_name='optimizedataset',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='model_hub.aimodel'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='develop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='model_hub.developai'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='collaborators',
            field=models.ManyToManyField(related_name='user_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='original_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_executions', to='model_hub.prompttemplate'),
        ),
        migrations.AddField(
            model_name='row',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.row'),
        ),
        migrations.AddField(
            model_name='runprompter',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='runprompter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_prompt_org', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='secretmodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_secrets', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='tools',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_org', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='runprompter',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='runprompters', to='model_hub.tools'),
        ),
        migrations.AddField(
            model_name='userevalmetric',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.dataset'),
        ),
        migrations.AddField(
            model_name='userevalmetric',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_template_org', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='userevalmetric',
            name='template',
            field=models.ForeignKey(help_text='Link to the metric template configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='user_metrics', to='model_hub.evaltemplate'),
        ),
        migrations.AddField(
            model_name='userevalmetric',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optimizationdataset',
            name='user_eval_template_ids',
            field=models.ManyToManyField(blank=True, related_name='optimization_datasets_evals', to='model_hub.userevalmetric'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_eval_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.userevalmetric'),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='user_eval_template_ids',
            field=models.ManyToManyField(blank=True, related_name='experiments_evaluation_ids', to='model_hub.userevalmetric'),
        ),
        migrations.AddField(
            model_name='userresponseschema',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_response_schemas', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='autogenerateeventsrun',
            unique_together={('ai_model',)},
        ),
        migrations.AlterUniqueTogether(
            name='customaimodel',
            unique_together={('organization', 'user_model_id', 'deleted')},
        ),
        migrations.AddIndex(
            model_name='errorlocalizertask',
            index=models.Index(fields=['source_id'], name='error_local_source__c3981d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('organization', 'user_model_id', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together={('original_template', 'template_version')},
        ),
        migrations.AlterUniqueTogether(
            name='secretmodel',
            unique_together={('organization', 'name')},
        ),
        migrations.AddConstraint(
            model_name='userresponseschema',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_schema_name_per_organization'),
        ),
    ]
