# Generated by Django 5.1.8 on 2025-07-09 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='eval_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
