# Generated by Django 5.1.8 on 2025-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_config'),
        ('model_hub', '0003_alter_evaluator_config_alter_evaluator_description_and_more'),
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationslabels',
            options={},
        ),
        migrations.AddConstraint(
            model_name='annotationslabels',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name', 'type', 'project'), name='unique_active_label_org_name_type_project'),
        ),
    ]
