# Generated by Django 5.1.8 on 2025-07-15 12:15

from django.conf import settings
from django.db import migrations, models

import model_hub.models.develop_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0004_alter_annotationslabels_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='source',
            field=models.CharField(choices=[('evaluation', 'Evaluation'), ('evaluation_tags', 'Evaluation Tags'), ('evaluation_reason', 'Evaluation Reason'), ('run_prompt', 'Run Prompt'), ('experiment', 'Experiment'), ('optimisation', 'Optimisation'), ('experiment_evaluation', 'Experiment Evaluation'), ('experiment_evaluation_tags', 'Experiment Evaluation Tags'), ('optimisation_evaluation', 'Optimisation Evaluation'), ('annotation_label', 'Annotation Label'), ('optimisation_evaluation_tags', 'Optimisation Evaluation Tags'), ('extracted_json', 'Extracted Json'), ('classification', 'Classification'), ('extracted_entities', 'Extracted Entities'), ('api_call', 'Api Call'), ('python_code', 'Python Code'), ('vector_db', 'Vector Db'), ('conditional', 'Conditional'), ('eval_playground', 'Eval Playground'), ('OTHERS', 'Others')], max_length=50, validators=[model_hub.models.develop_dataset.validate_source_choice]),
        ),
        migrations.AlterUniqueTogether(
            name='evalsettings',
            unique_together={('eval_id', 'source', 'user')},
        ),
    ]
