# Generated by Django 5.1.8 on 2025-07-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0003_remove_prompttemplate_evaluation_configs_and_more'),
        ('model_hub', '0005_alter_column_source_and_more'),
    ]

    operations = [
    ]
