# Generated by Django 5.1.8 on 2025-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0006_merge_20250724_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='source',
            field=models.CharField(choices=[('dataset', 'Dataset'), ('prompt', 'Prompt'), ('sdk', 'Sdk'), ('trace', 'Trace'), ('experiment', 'Experiment'), ('observe', 'Observe'), ('eval_playground', 'Eval Playground')], max_length=50),
        ),
    ]
