# Generated by Django 5.1.8 on 2025-08-01 09:30

from django.db import migrations, models

import model_hub.models.develop_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0008_alter_dataset_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='errorlocalizertask',
            name='source',
            field=models.CharField(choices=[('dataset', 'Dataset'), ('observe', 'Observe'), ('playground', 'Playground'), ('simulate', 'Simulate')], default='dataset', max_length=255),
        ),
        migrations.AlterField(
            model_name='experimentdatasettable',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='NotStarted', max_length=50),
        ),
        migrations.AlterField(
            model_name='experimentstable',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='NotStarted', max_length=50),
        ),
        migrations.AlterField(
            model_name='files',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Processing', validators=[model_hub.models.develop_dataset.validate_status_choices]),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Processing', validators=[model_hub.models.develop_dataset.validate_status_choices]),
        ),
        migrations.AlterField(
            model_name='optimizationdataset',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='NotStarted', max_length=50),
        ),
        migrations.AlterField(
            model_name='promptevalconfig',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='runprompter',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='NotStarted', max_length=100),
        ),
        migrations.AlterField(
            model_name='userevalmetric',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Inactive', max_length=100),
        ),
    ]
