# Generated by Django 5.1.8 on 2025-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0009_alter_column_status_alter_errorlocalizertask_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
