# Generated by Django 5.1.8 on 2025-08-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0010_cell_completion_tokens_cell_prompt_tokens_and_more'),
        ('model_hub', '0010_evaluation'),
    ]

    operations = [
    ]
