# Generated by Django 5.1.8 on 2025-08-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0011_dataset_synthetic_dataset_config'),
        ('model_hub', '0011_merge_20250809_0613'),
    ]

    operations = [
    ]
