# Generated by Django 5.1.8 on 2025-08-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0012_merge_20250811_1553'),
    ]

    operations = [
    ]
