# Generated by Django 5.1.8 on 2025-08-13 09:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('model_hub', '0013_merge_20250812_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_labels', to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='promptversion',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='prompt_versions', to='model_hub.promptlabel'),
        ),
        migrations.AddIndex(
            model_name='promptlabel',
            index=models.Index(fields=['organization', 'type'], name='model_hub_p_organiz_866122_idx'),
        ),
        migrations.AddIndex(
            model_name='promptlabel',
            index=models.Index(fields=['name'], name='model_hub_p_name_fb729b_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name'), name='unique_label_name_per_org_active'),
        ),
        migrations.AddConstraint(
            model_name='promptlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('organization__isnull', True), ('type', 'system')), fields=('name',), name='unique_global_system_label_name'),
        ),
    ]
