# Generated by Django 5.1.8 on 2025-08-13 12:10

from django.db import migrations, models

import model_hub.models.develop_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0014_promptlabel_promptversion_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('json', 'Json'), ('array', 'Array'), ('image', 'Image'), ('datetime', 'Datetime'), ('audio', 'Audio'), ('document', 'Document'), ('others', 'Others')], max_length=50, validators=[model_hub.models.develop_dataset.validate_data_type_choice]),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='column',
            name='source_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='errorlocalizertask',
            name='selected_input_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='evaltemplate',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='model',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='model_name',
            field=models.CharField(blank=True, help_text='Model used for evaluation', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='experimentdatasettable',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_by',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploaded_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='created_by',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='last_error',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='optimizationdataset',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='optimizationdataset',
            name='prompt_name',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='promptevalconfig',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='promptlabel',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='runprompter',
            name='model',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='runprompter',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userevalmetric',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userresponseschema',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
