# Generated by Django 5.1.8 on 2025-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0015_alter_column_data_type_alter_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationslabels',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
