# Generated by Django 5.1.8 on 2025-08-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_organization_role_organizationmembership_and_more'),
        ('model_hub', '0015_alter_column_data_type_alter_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='annotationslabels',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations_labels', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='columnconfig',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_configs', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='customaimodel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_ai_models', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='datasetinsightmeta',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_insight_meta', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='datasetproperties',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_properties', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='developai',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='develop_ais', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='errorlocalizertask',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_localizer_tasks', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='evaltemplate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_templates', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='insight',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_files', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='promptlabel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_labels', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='runprompter',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_prompts', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='secretmodel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='tools',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='userevalmetric',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_eval_metrics', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='userresponseschema',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_response_schemas', to='accounts.workspace'),
        ),
    ]
