# Generated by Django 5.1.8 on 2025-08-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0016_aimodel_workspace_annotations_workspace_and_more'),
        ('model_hub', '0016_dataset_eval_reasons'),
    ]

    operations = [
    ]
