# Generated by Django 5.1.8 on 2025-08-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0012_merge_20250822_0853'),
        ('model_hub', '0016_aimodel_workspace_annotations_workspace_and_more'),
    ]

    operations = [
    ]
