# Generated by Django 5.1.8 on 2025-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_ws_enabled_and_more'),
        ('model_hub', '0018_remove_dataset_eval_reasons'),
        ('tracer', '0013_merge_20250826_0926'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annotationslabels',
            name='unique_active_label_org_name_type_project',
        ),
        migrations.RemoveConstraint(
            model_name='promptlabel',
            name='unique_label_name_per_org_active',
        ),
        migrations.RemoveConstraint(
            model_name='userresponseschema',
            name='unique_schema_name_per_organization',
        ),
        migrations.AddConstraint(
            model_name='annotationslabels',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name', 'type', 'project', 'workspace'), name='unique_active_label_org_name_type_project'),
        ),
        migrations.AddConstraint(
            model_name='promptlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name', 'workspace'), name='unique_label_name_per_org_active'),
        ),
        migrations.AddConstraint(
            model_name='userresponseschema',
            constraint=models.UniqueConstraint(fields=('name', 'organization', 'workspace'), name='unique_schema_name_per_organization'),
        ),
    ]
