# Generated by Django 5.1.8 on 2025-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0018_remove_dataset_eval_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptversion',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
