# Generated by Django 5.1.8 on 2025-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0019_promptversion_placeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
