# Generated by Django 5.1.8 on 2025-08-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0016_annotationslabels_metadata'),
        ('model_hub', '0019_dataset_eval_reasons'),
    ]

    operations = [
    ]
