# Generated by Django 5.1.8 on 2025-09-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0019_remove_annotationslabels_unique_active_label_org_name_type_project_and_more'),
        ('model_hub', '0020_dataset_eval_reason_last_updated'),
    ]

    operations = [
    ]
