# Generated by Django 5.1.8 on 2025-09-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0020_evaluation_error_localizer_and_more'),
        ('model_hub', '0021_merge_20250902_0743'),
    ]

    operations = [
    ]
