# Generated by Django 5.1.8 on 2025-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0017_merge_20250826_0917'),
        ('model_hub', '0021_merge_20250902_0743'),
    ]

    operations = [
    ]
