# Generated by Django 5.1.8 on 2025-09-05 11:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250905_1157'),
        ('model_hub', '0022_merge_20250905_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PromptBaseTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_sample', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_config_snapshot', models.JSONField(blank=True, default=list, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_base_templates', to='accounts.organization')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_base_templates', to='model_hub.promptversion')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_base_templates', to='accounts.workspace')),
            ],
            options={
                'db_table': 'model_hub_prompt_base_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promptversion',
            name='prompt_base_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='model_hub.promptbasetemplate'),
        ),
        migrations.CreateModel(
            name='PromptFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_sample', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_folders', to='accounts.organization')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='model_hub.promptfolder')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_folders', to='accounts.workspace')),
            ],
            options={
                'db_table': 'model_hub_prompt_folder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='prompt_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='model_hub.promptfolder'),
        ),
        migrations.AddIndex(
            model_name='promptbasetemplate',
            index=models.Index(fields=['organization', 'workspace', 'created_at'], name='model_hub_p_organiz_39d4a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptbasetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name', 'organization', 'workspace'), name='unique_prompt_base_template_name_organization_workspace_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='promptfolder',
            index=models.Index(fields=['organization', 'workspace', 'created_at'], name='model_hub_p_organiz_b7c845_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name', 'organization', 'workspace'), name='unique_prompt_folder_name_organization_workspace_not_deleted'),
        ),
    ]
