# Generated by Django 5.1.8 on 2025-09-04 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_ws_enabled_and_more'),
        ('model_hub', '0022_merge_20250904_0542'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='errorlocalizertask',
            index=models.Index(fields=['status'], name='error_local_status_5890d8_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['error_localizer_enabled'], name='model_hub_e_error_l_a2674f_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['error_localizer'], name='model_hub_e_error_l_48330a_idx'),
        ),
    ]
