# Generated by Django 5.1.8 on 2025-09-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0017_merge_20250826_0917'),
        ('model_hub', '0020_merge_20250828_1205'),
        ('model_hub', '0023_errorlocalizertask_error_local_status_5890d8_idx_and_more'),
    ]

    operations = [
    ]
