# Generated by Django 5.1.8 on 2025-09-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0023_prompttemplate_is_sample_promptbasetemplate_and_more'),
        ('model_hub', '0024_merge_20250905_1045'),
    ]

    operations = [
    ]
