# Generated by Django 5.1.8 on 2025-09-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0022_merge_20250905_1827'),
        ('model_hub', '0025_merge_20250905_1241'),
    ]

    operations = [
    ]
