# Generated by Django 5.1.8 on 2025-09-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20250905_1241'),
        ('model_hub', '0025_merge_20250905_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptbasetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_base_templates', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='promptfolder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_folders', to='accounts.organization'),
        ),
    ]
