# Generated by Django 5.1.8 on 2025-09-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0026_alter_promptbasetemplate_organization_and_more'),
        ('model_hub', '0026_merge_20250908_0727'),
    ]

    operations = [
    ]
