# Generated by Django 5.1.8 on 2025-09-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0020_prompttemplate_placeholders'),
        ('model_hub', '0029_prompttemplate_created_by'),
    ]

    operations = [
    ]
