# Generated by Django 5.1.8 on 2025-09-12 15:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250908_0727'),
        ('model_hub', '0030_merge_20250911_0838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_groups', to=settings.AUTH_USER_MODEL)),
                ('eval_templates', models.ManyToManyField(blank=True, related_name='eval_groups', to='model_hub.evaltemplate')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_groups', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_groups', to='accounts.workspace')),
            ],
            options={
                'db_table': 'model_hub_eval_group',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'workspace', 'created_at'], name='model_hub_e_organiz_2c8a72_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name', 'organization', 'workspace'), name='unique_eval_group_name_organization_workspace_not_deleted')],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField(help_text='ID of the source entity')),
                ('source_type', models.CharField(choices=[('EVAL_GROUP', 'Eval Group')], max_length=50)),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('DELETE', 'Delete')], max_length=20)),
                ('reference_id', models.UUIDField(help_text='ID of the referenced entity (e.g., eval_template_id)')),
                ('action_by', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='history_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization where the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace where the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='accounts.workspace')),
            ],
            options={
                'db_table': 'model_hub_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_id', 'source_type', 'created_at'], name='model_hub_h_source__70dc06_idx'), models.Index(fields=['reference_id', 'action'], name='model_hub_h_referen_5c7f29_idx'), models.Index(fields=['action_by', 'created_at'], name='model_hub_h_action__e0bbc0_idx'), models.Index(fields=['organization', 'workspace', 'created_at'], name='model_hub_h_organiz_8a32a6_idx')],
            },
        ),
    ]
