# Generated by Django 5.1.8 on 2025-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0033_remove_evalgroup_unique_eval_group_name_organization_workspace_not_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalgroup',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
