# Generated by Django 5.1.8 on 2025-09-29 11:32

from django.db import migrations, models

import model_hub.models.develop_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0034_evalgroup_is_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('json', 'Json'), ('array', 'Array'), ('image', 'Image'), ('datetime', 'Datetime'), ('audio', 'Audio'), ('document', 'Document'), ('others', 'Others'), ('persona', 'Persona')], max_length=50, validators=[model_hub.models.develop_dataset.validate_data_type_choice]),
        ),
    ]
