# Generated by Django 5.1.8 on 2025-10-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0035_alter_column_data_type'),
        ('model_hub', '0035_userevalmetric_eval_group_alter_column_data_type'),
    ]

    operations = [
    ]
