# Generated by Django 5.1.8 on 2025-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0036_merge_20251001_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runprompter',
            name='output_format',
            field=models.CharField(choices=[('array', 'array'), ('string', 'string'), ('number', 'number'), ('object', 'object'), ('audio', 'audio')], default='string', help_text="Output format type. Defaults to 'string'.", max_length=10),
        ),
    ]
