# Generated by Django 5.1.8 on 2025-11-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0037_add_promptversion_labels_composite_index'),
        ('model_hub', '0037_alter_runprompter_output_format'),
    ]

    operations = [
    ]
