# Generated by Django 5.1.8 on 2025-11-24 11:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_goals_user_role'),
        ('model_hub', '0038_merge_20251105_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSVoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('voice_id', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('provider', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('model', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('voice_type', models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], default='custom', max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tts_voices_org', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tts_voices', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
