# Generated by Django 5.1.8 on 2025-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0039_ttsvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttsvoice',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
