# Generated by Django 5.1.8 on 2025-11-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0040_alter_ttsvoice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('messages', models.JSONField(help_text='The messages to use for processing the row')),
                ('model', models.CharField(help_text='The model to use for processing', max_length=255)),
                ('model_config', models.JSONField(help_text='The model configuration to use for processing')),
                ('output_format', models.CharField(blank=True, help_text='The output format for the response', max_length=255, null=True)),
                ('run_prompt_config', models.JSONField(blank=True, help_text='The run prompt configuration', null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='registered', help_text='The status of the row processing task', max_length=255)),
                ('column', models.ForeignKey(help_text='The column this row processing belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pending_row_tasks', to='model_hub.column')),
                ('dataset', models.ForeignKey(help_text='The dataset this row processing belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pending_row_tasks', to='model_hub.dataset')),
                ('experiment', models.ForeignKey(help_text='The experiment this row processing belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pending_row_tasks', to='model_hub.experimentstable')),
                ('row', models.ForeignKey(help_text='The row to process', on_delete=django.db.models.deletion.CASCADE, related_name='pending_row_tasks', to='model_hub.row')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
