# Generated by Django 5.1.8 on 2025-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0041_pendingrowtask'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pendingrowtask',
            index=models.Index(fields=['status', 'created_at'], name='model_hub_p_status_600b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingrowtask',
            index=models.Index(fields=['experiment_id', 'status'], name='model_hub_p_experim_6792e7_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingrowtask',
            index=models.Index(fields=['column_id', 'status'], name='model_hub_p_column__fc926e_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingrowtask',
            index=models.Index(fields=['row_id', 'column_id', 'dataset_id', 'experiment_id', 'status'], name='model_hub_p_row_id_6507c4_idx'),
        ),
    ]
