# Generated by Django 5.1.8 on 2025-12-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0041_alter_dataset_eval_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_by',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploaded_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='created_by',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='last_error',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='name',
            field=models.CharField(max_length=5000),
        ),
    ]
