# Generated by Django 5.1.8 on 2025-12-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0041_alter_dataset_eval_reasons'),
        ('model_hub', '0042_pendingrowtask_model_hub_p_status_600b9b_idx_and_more'),
    ]

    operations = [
    ]
