# Generated by Django 5.1.8 on 2025-12-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0042_alter_files_name_alter_files_updated_by_and_more'),
        ('model_hub', '0043_merge_20251210_1300'),
    ]

    operations = [
    ]
