# Generated by Django 5.1.8 on 2025-12-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('model_hub', '0047_alter_dataset_eval_reason_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secretmodel',
            unique_together={('organization', 'workspace', 'name')},
        ),
    ]
