# Generated by Django 5.1.8 on 2026-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0048_alter_secretmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
