# Generated by Django 5.1.8 on 2026-01-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('model_hub', '0049_row_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AddField(
            model_name='feedback',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.workspace'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['organization', 'eval_template'], name='model_hub_f_organiz_595720_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['workspace', 'eval_template'], name='model_hub_f_workspa_c18024_idx'),
        ),
    ]
