# Generated by Django 5.1.8 on 2026-01-30 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0053_optimize_dataset_inherit_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOptimizationTrialItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_id', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('filled_prompt', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_items', to='model_hub.datasetoptimizationtrial')),
            ],
            options={
                'db_table': 'dataset_optimization_trial_item',
            },
        ),
        migrations.CreateModel(
            name='DatasetOptimizationItemEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('eval_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_optimization_evaluations', to='model_hub.userevalmetric')),
                ('trial_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='model_hub.datasetoptimizationtrialitem')),
            ],
            options={
                'db_table': 'dataset_optimization_item_evaluation',
            },
        ),
        migrations.AddIndex(
            model_name='datasetoptimizationtrialitem',
            index=models.Index(fields=['trial'], name='idx_ds_opt_trial_item_trial'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetoptimizationtrialitem',
            unique_together={('trial', 'row_id')},
        ),
        migrations.AddIndex(
            model_name='datasetoptimizationitemevaluation',
            index=models.Index(fields=['trial_item', 'eval_metric'], name='idx_dsopt_eval_item_metric'),
        ),
        migrations.AddIndex(
            model_name='datasetoptimizationitemevaluation',
            index=models.Index(fields=['eval_metric'], name='idx_dsopt_eval_metric'),
        ),
    ]
