# Generated by Django 5.1.8 on 2026-02-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0052_remove_dataset_model_hub_d_organiz_edc982_idx_and_more'),
        ('model_hub', '0054_add_trial_item_models'),
    ]

    operations = [
    ]
