# Generated by Django 5.1.8 on 2026-02-25 12:17

import django.db.models.deletion
import model_hub.models.develop_dataset
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0003_alter_graphversion_status'),
        ('model_hub', '0056_remove_dataset_model_hub_d_organiz_edc982_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdatasettable',
            name='prompt_config',
            field=models.JSONField(db_column='prompt_config', default=dict),
        ),
        migrations.RenameField(
            model_name='experimentdatasettable',
            old_name='prompt_config',
            new_name='legacy_prompt_config',
        ),
        migrations.AddField(
            model_name='experimentdatasettable',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_datasets', to='model_hub.experimentstable'),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='experiment_type',
            field=models.CharField(choices=[('llm', 'LLM'), ('tts', 'TTS'), ('stt', 'STT'), ('image', 'Image')], default='llm', help_text='Determines how the experiment executes: llm, tts, stt, or image.', max_length=50),
        ),
        migrations.AddField(
            model_name='experimentstable',
            name='snapshot_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_snapshots', to='model_hub.dataset'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo'), ('build', 'Build'), ('sdk', 'Sdk'), ('observe', 'Observe'), ('knowledge_base', 'Knowledge Base'), ('scenario', 'Scenario'), ('experiment_snapshot', 'Experiment Snapshot')], default='build', max_length=50, validators=[model_hub.models.develop_dataset.validate_dataset_source_choice]),
        ),
        migrations.CreateModel(
            name='ExperimentAgentConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('order', models.PositiveIntegerField(default=0, help_text='Processing order.')),
                ('experiment_dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='model_hub.experimentdatasettable')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_agent_configs', to='agent_playground.graph')),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_agent_configs', to='agent_playground.graphversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentPromptConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('model', models.CharField(help_text="Single model name (e.g., 'gpt-5', 'openai/tts-1-hd').", max_length=2000)),
                ('model_display_name', models.CharField(blank=True, help_text='Optional display name for the model.', max_length=2000, null=True)),
                ('model_config', models.JSONField(default=dict, help_text='Inline config from model spec dict (e.g., {"voice": "alloy"} for TTS). Empty for string-format models.')),
                ('model_params', models.JSONField(default=dict, help_text='Per-model params from modelParams[model_name]: {"temperature": 0.5, "maxTokens": 4085, "providers": "openai", "logoUrl": "..."}')),
                ('configuration', models.JSONField(default=dict, help_text='Tools config: {"toolChoice": "auto", "tools": [...]}')),
                ('output_format', models.CharField(default='string', help_text='Output format: string, object, audio, image.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Deterministic processing order.')),
                ('messages', models.JSONField(blank=True, help_text='Inline messages for tts/stt/image experiments. Null when prompt_version is set.', null=True)),
                ('experiment_dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_config', to='model_hub.experimentdatasettable')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment_prompt_configs', to='model_hub.prompttemplate')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment_prompt_configs', to='model_hub.promptversion')),
                ('voice_input_column', models.ForeignKey(blank=True, help_text='STT only: references dataset column containing audio data to transcribe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_stt_configs', to='model_hub.column')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
