# Generated by Django 5.1.8 on 2026-02-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0050_alter_dataset_source'),
        ('model_hub', '0056_remove_dataset_model_hub_d_organiz_edc982_idx_and_more'),
    ]

    operations = [
    ]
