# Generated by Django 5.1.8 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_hub", "0056_remove_dataset_model_hub_d_organiz_edc982_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptevalconfig",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
