# Generated by Django 5.1.8 on 2026-02-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0056_remove_dataset_model_hub_d_organiz_edc982_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedataset',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=100),
        ),
    ]
