# Generated by Django 5.1.8 on 2026-03-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0057_alter_optimizedataset_status'),
        ('model_hub', '0057_promptevalconfig_config'),
    ]

    operations = [
    ]
