# Generated by Django 5.1.8 on 2026-03-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0059_alter_dataset_eval_reason_status'),
        ('model_hub', '0059_clear_uc_session_ids_from_row_metadata'),
    ]

    operations = [
    ]
