# Generated by Django 5.1.8 on 2026-03-09 13:17

from django.db import migrations


class Migration(migrations.Migration):
 
    dependencies = [
        ('model_hub', '0057_merge_20260227_1332'),
        ('model_hub', '0059_clear_uc_session_ids_from_row_metadata'),
    ]

    operations = [
    ]
