# Generated by Django 5.1.8 on 2026-03-08 15:56

"""
Creates TTSVoice and Score models, then backfills TraceAnnotation and
ItemAnnotation records into the unified Score table.

Old tables (trace_annotation, model_hub_itemannotation) are kept intact —
they are deprecated and will be removed in a future release.
"""

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Backfill helpers (inlined constants to avoid importing app code)
# ---------------------------------------------------------------------------

BATCH_SIZE = 500

NUMERIC = "numeric"
STAR = "star"
THUMBS_UP_DOWN = "thumbs_up_down"
CATEGORICAL = "categorical"

SOURCE_FK_MAP = {
    "trace": "trace_id",
    "observation_span": "observation_span_id",
    "trace_session": "trace_session_id",
    "call_execution": "call_execution_id",
    "prototype_run": "prototype_run_id",
    "dataset_row": "dataset_row_id",
}


def _ta_to_score_value(label_type, ta):
    """Convert TraceAnnotation typed fields → Score JSON value."""
    if label_type in (NUMERIC, STAR):
        if ta.annotation_value_float is not None:
            key = "rating" if label_type == STAR else "value"
            return {key: ta.annotation_value_float}
        return {"value": 0}
    if label_type == THUMBS_UP_DOWN:
        if ta.annotation_value_bool is not None:
            return {"value": "up" if ta.annotation_value_bool else "down"}
        return {"value": "up"}
    if label_type == CATEGORICAL:
        if ta.annotation_value_str_list:
            return {"selected": ta.annotation_value_str_list}
        return {"selected": []}
    # TEXT or unknown
    return {"text": ta.annotation_value or ""}


def backfill_trace_annotations(apps, schema_editor):
    """Migrate TraceAnnotation → Score."""
    TraceAnnotation = apps.get_model("tracer", "TraceAnnotation")
    Score = apps.get_model("model_hub", "Score")

    qs = (
        TraceAnnotation.objects.filter(deleted=False)
        .select_related(
            "annotation_label",
            "observation_span__trace__project__organization",
            "trace__project__organization",
            "user__organization",
        )
        .order_by("created_at")
    )
    total = qs.count()
    if total == 0:
        return

    created = 0
    skipped = 0
    offset = 0

    while offset < total:
        batch = list(qs[offset : offset + BATCH_SIZE])
        if not batch:
            break

        for ta in batch:
            obs_span_id = ta.observation_span_id
            trace_id = ta.trace_id

            # Skip if BOTH observation_span and trace are NULL
            if not obs_span_id and not trace_id:
                skipped += 1
                continue

            label_type = ta.annotation_label.type if ta.annotation_label else None
            if not label_type:
                skipped += 1
                continue

            value = _ta_to_score_value(label_type, ta)

            # Determine source_type, source FK kwargs, and org.
            # NOTE: Score.project FK points to DevelopAI, not tracer.Project,
            # so we do NOT set project from trace annotations.
            org_id = None
            if obs_span_id:
                source_type = "observation_span"
                source_kwargs = {"observation_span_id": obs_span_id}
                span = ta.observation_span
                if span and span.trace and span.trace.project:
                    org_id = span.trace.project.organization_id
            else:
                source_type = "trace"
                source_kwargs = {"trace_id": trace_id}
                trace_obj = ta.trace
                if trace_obj and trace_obj.project:
                    org_id = trace_obj.project.organization_id

            if not org_id and ta.user_id and ta.user:
                org_id = ta.user.organization_id

            if not org_id:
                skipped += 1
                continue

            try:
                # Idempotency: skip if a Score already exists for this
                # (source, label, annotator) combination so re-running
                # the migration is safe and fast.
                if Score.objects.filter(
                    **source_kwargs,
                    label_id=ta.annotation_label_id,
                    annotator_id=ta.user_id,
                    deleted=False,
                ).exists():
                    skipped += 1
                    continue

                Score.objects.create(
                    **source_kwargs,
                    label_id=ta.annotation_label_id,
                    annotator_id=ta.user_id,
                    deleted=False,
                    source_type=source_type,
                    value=value,
                    score_source="human",
                    notes="",
                    organization_id=org_id,
                )
                created += 1
            except Exception:
                skipped += 1

        offset += BATCH_SIZE

    print(
        f"  TraceAnnotation backfill: {created} created/updated, "
        f"{skipped} skipped (of {total})"
    )


def backfill_item_annotations(apps, schema_editor):
    """Migrate ItemAnnotation → Score."""
    ItemAnnotation = apps.get_model("model_hub", "ItemAnnotation")
    Score = apps.get_model("model_hub", "Score")

    qs = (
        ItemAnnotation.objects.filter(deleted=False)
        .select_related("queue_item", "label", "annotator")
        .order_by("created_at")
    )
    total = qs.count()
    if total == 0:
        return

    created = 0
    skipped = 0
    offset = 0

    while offset < total:
        batch = list(qs[offset : offset + BATCH_SIZE])
        if not batch:
            break

        for ia in batch:
            qi = ia.queue_item
            if not qi:
                skipped += 1
                continue

            source_type = qi.source_type
            fk_id_field = SOURCE_FK_MAP.get(source_type)
            if not fk_id_field:
                skipped += 1
                continue

            source_obj_id = getattr(qi, fk_id_field, None)
            if not source_obj_id:
                skipped += 1
                continue

            try:
                # Idempotency: skip if a Score already exists for this
                # (source, label, annotator) combination so re-running
                # the migration is safe and fast.
                if Score.objects.filter(
                    **{fk_id_field: source_obj_id},
                    label_id=ia.label_id,
                    annotator_id=ia.annotator_id,
                    deleted=False,
                ).exists():
                    skipped += 1
                    continue

                Score.objects.create(
                    **{fk_id_field: source_obj_id},
                    label_id=ia.label_id,
                    annotator_id=ia.annotator_id,
                    deleted=False,
                    source_type=source_type,
                    value=ia.value,
                    score_source=ia.score_source or "human",
                    notes=ia.notes or "",
                    organization_id=ia.organization_id,
                    queue_item_id=qi.pk,
                )
                created += 1
            except Exception:
                skipped += 1

        offset += BATCH_SIZE

    print(
        f"  ItemAnnotation backfill: {created} created/updated, "
        f"{skipped} skipped (of {total})"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('model_hub', '0061_add_trace_session_to_queue_item'),
        ('simulate', '0068_chatsimulatorassistant_chatsimulatorsession'),
        ('tracer', '0046_replaysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSVoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('voice_id', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('provider', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('model', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('voice_type', models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], default='custom', max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tts_voices_org', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tts_voices', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('dataset_row', 'Dataset Row'), ('trace', 'Trace'), ('observation_span', 'Observation Span'), ('prototype_run', 'Prototype Run'), ('call_execution', 'Call Execution'), ('trace_session', 'Trace Session')], max_length=30)),
                ('value', models.JSONField()),
                ('score_source', models.CharField(choices=[('human', 'Human'), ('api', 'Api'), ('auto', 'Auto')], default='human', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('call_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='simulate.callexecution')),
                ('dataset_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='model_hub.row')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='model_hub.annotationslabels')),
                ('observation_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tracer.observationspan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='model_hub.developai')),
                ('prototype_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='model_hub.runprompter')),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='model_hub.queueitem')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tracer.trace')),
                ('trace_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tracer.tracesession')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['trace', 'label'], name='model_hub_s_trace_i_d55df9_idx'), models.Index(fields=['observation_span', 'label'], name='model_hub_s_observa_c0bec4_idx'), models.Index(fields=['trace_session', 'label'], name='model_hub_s_trace_s_b93ebb_idx'), models.Index(fields=['call_execution', 'label'], name='model_hub_s_call_ex_5231cb_idx'), models.Index(fields=['source_type', 'label', 'created_at'], name='model_hub_s_source__66b24a_idx'), models.Index(fields=['queue_item'], name='model_hub_s_queue_i_bd4a73_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False), ('trace__isnull', False)), fields=('trace', 'label', 'annotator'), name='unique_score_trace_label_annotator'), models.UniqueConstraint(condition=models.Q(('deleted', False), ('observation_span__isnull', False)), fields=('observation_span', 'label', 'annotator'), name='unique_score_span_label_annotator'), models.UniqueConstraint(condition=models.Q(('deleted', False), ('trace_session__isnull', False)), fields=('trace_session', 'label', 'annotator'), name='unique_score_session_label_annotator'), models.UniqueConstraint(condition=models.Q(('call_execution__isnull', False), ('deleted', False)), fields=('call_execution', 'label', 'annotator'), name='unique_score_call_label_annotator'), models.UniqueConstraint(condition=models.Q(('deleted', False), ('prototype_run__isnull', False)), fields=('prototype_run', 'label', 'annotator'), name='unique_score_run_label_annotator'), models.UniqueConstraint(condition=models.Q(('dataset_row__isnull', False), ('deleted', False)), fields=('dataset_row', 'label', 'annotator'), name='unique_score_row_label_annotator')],
            },
        ),
        migrations.RunPython(
            backfill_trace_annotations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_item_annotations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
