# Generated by Django 5.1.8 on 2026-03-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0057_alter_experimentdatasettable_prompt_config_and_more'),
        ('model_hub', '0061_merge_20260306_0640'),
        ('model_hub', '0062_ttsvoice_score'),
    ]

    operations = [
    ]
