# Generated by Django 5.1.8 on 2026-03-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0060_merge_20260311_1110'),
        ('model_hub', '0065_alter_score_call_execution_alter_score_dataset_row_and_more'),
    ]

    operations = [
    ]
