# Generated by Django 5.1.8 on 2026-03-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0061_merge_20260306_0640'),
        ('model_hub', '0066_merge_20260312_0339'),
    ]

    operations = [
    ]
