# Generated by Django 5.1.8 on 2026-03-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0060_merge_20260309_1317'),
        ('model_hub', '0062_merge_20260316_1301'),
        ('model_hub', '0067_merge_20260316_0730'),
    ]

    operations = [
    ]
