# Generated by Django 5.1.8 on 2026-03-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0060_merge_20260309_1317'),
        ('model_hub', '0070_migrate_assigned_to_m2m'),
    ]

    operations = [
    ]
