# Generated by Django 5.1.8 on 2026-03-30 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0071_merge_20260323_0811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationqueue",
            name="assignment_strategy",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("round_robin", "Round Robin"),
                    ("load_balanced", "Load Balanced"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="annotationqueueannotator",
            name="role",
            field=models.CharField(
                choices=[
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                    ("manager", "Manager"),
                ],
                default="annotator",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="queueitemassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="queueitemassignment",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="runprompter",
            name="concurrency",
            field=models.IntegerField(
                default=5,
                help_text="Concurrency level, default is 5. Maximum 10.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="runprompter",
            name="temperature",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Controls the randomness. Value between 0 and 2.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
    ]
