# Generated by Django 5.1.8 on 2026-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0071_merge_20260323_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaltemplate',
            name='choice_scores',
            field=models.JSONField(blank=True, help_text='Maps choice labels to 0-1 scores: {"Yes": 1.0, "No": 0.0}', null=True),
        ),
        migrations.AddField(
            model_name='evaltemplate',
            name='output_type_normalized',
            field=models.CharField(blank=True, help_text='Normalized output type: pass_fail, percentage, deterministic', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaltemplate',
            name='pass_threshold',
            field=models.FloatField(blank=True, default=0.5, help_text='Score >= threshold means pass. Range 0.0-1.0', null=True),
        ),
        migrations.AlterField(
            model_name='annotationqueue',
            name='assignment_strategy',
            field=models.CharField(choices=[('manual', 'Manual'), ('round_robin', 'Round Robin'), ('load_balanced', 'Load Balanced')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotationqueueannotator',
            name='role',
            field=models.CharField(choices=[('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('manager', 'Manager')], default='annotator', max_length=20),
        ),
        migrations.AlterField(
            model_name='queueitemassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queueitemassignment',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
