# Generated by Django 5.1.8 on 2026-03-31 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0068_merge_20260319_0729'),
        ('model_hub', '0071_merge_20260323_0811'),
    ]

    operations = [
    ]
