# Generated by Django 5.1.8 on 2026-04-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0072_merge_20260331_0222'),
        ('model_hub', '0072_update_run_prompter_validators'),
    ]

    operations = [
    ]
