# Generated by Django 5.1.8 on 2026-03-29 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_eval_template_version'),
        ('model_hub', '0074_add_composite_eval'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalGroundTruth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ground truth dataset name', max_length=255)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original uploaded file name', max_length=500)),
                ('columns', models.JSONField(blank=True, default=list, help_text='Column headers: ["input", "expected_output", ...]')),
                ('data', models.JSONField(blank=True, default=list, help_text='Row data: [{"input": "...", "expected_output": "..."}, ...]')),
                ('row_count', models.IntegerField(default=0)),
                ('variable_mapping', models.JSONField(blank=True, help_text='Maps eval variables to ground truth columns: {"ground_truth": "expected_output"}', null=True)),
                ('eval_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truths', to='model_hub.evaltemplate')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_ground_truths', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_ground_truths', to='accounts.workspace')),
            ],
            options={
                'db_table': 'model_hub_eval_ground_truth',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['eval_template', 'created_at'], name='model_hub_e_eval_te_b8c943_idx')],
            },
        ),
    ]
