# Generated by Django 5.1.8 on 2026-04-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0073_merge_20260403_2145'),
        ('model_hub', '0080_optimize_dataset_list_indexes'),
    ]

    operations = [
    ]
