# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0082_add_error_localizer_to_eval_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaltemplate",
            name="aggregation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable score aggregation for composite evals. When False, children run independently.",
            ),
        ),
        migrations.AddField(
            model_name="evaltemplate",
            name="aggregation_function",
            field=models.CharField(
                choices=[
                    ("weighted_avg", "Weighted Average"),
                    ("avg", "Average"),
                    ("min", "Minimum"),
                    ("max", "Maximum"),
                    ("pass_rate", "Pass Rate"),
                ],
                default="weighted_avg",
                help_text="Aggregation function for composite eval scores.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compositeevalchild",
            name="weight",
            field=models.FloatField(
                default=1.0,
                help_text="Weight for weighted aggregation (0.0-10.0)",
            ),
        ),
    ]
