# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0083_composite_aggregation"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaltemplate",
            name="composite_child_axis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pass_fail", "Pass / Fail"),
                    ("percentage", "Score"),
                    ("choices", "Choices"),
                    ("code", "Code"),
                ],
                default="",
                help_text="For composite evals: which tab/axis children must belong to. Enforces homogeneity.",
                max_length=20,
            ),
        ),
    ]
