# Generated by Django 5.1.8 on 2026-04-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0085_alter_column_status_alter_dataset_source_and_more'),
        ('model_hub', '0086_alter_column_status_alter_dataset_source_and_more'),
    ]

    operations = [
    ]
