# Generated by Django 5.1.8 on 2026-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0087_merge_20260416_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationslabels",
            name="allow_notes",
            field=models.BooleanField(default=False),
        ),
    ]
