# Generated by Django 5.1.8 on 2026-04-22 12:37

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0087_merge_20260416_1409'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name='cell',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('deleted', False), ('status', 'pass'), ('value__isnull', False), models.Q(('value', ''), _negated=True)), fields=['value'], name='model_hub_cell_value_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
