# Generated by Django 5.1.8 on 2026-04-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0088_add_allow_notes_to_annotations_labels'),
        ('model_hub', '0088_cell_model_hub_cell_value_trgm_idx'),
    ]

    operations = [
    ]
