# Generated by Django 5.1.8 on 2026-04-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0089_merge_20260422_1854'),
        ('model_hub', '0089_merge_20260423_0001'),
    ]

    operations = [
    ]
