# Generated by Django 5.1.8 on 2025-07-10 10:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('model_hub', '0002_initial'),
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvalConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the external eval config', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('mapping', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, choices=[('turing_large', 'Turing Large'), ('turing_small', 'Turing Small'), ('protect', 'Protect'), ('protect_flash', 'Protect Flash'), ('turing_flash', 'Turing Flash')], max_length=255, null=True)),
                ('eval_results', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, default=list, null=True)),
                ('platform', models.CharField(choices=[('langfuse', 'Langfuse')], max_length=255)),
                ('credentials', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=255)),
                ('eval_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.evaltemplate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'db_table': 'tracer_external_eval_config',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tracer_exte_status_276d0a_idx'), models.Index(fields=['platform'], name='tracer_exte_platfor_8af6f6_idx'), models.Index(fields=['organization'], name='tracer_exte_organiz_ee2b3f_idx')],
            },
        ),
    ]
