# Generated by Django 5.1.8 on 2025-07-23 10:13

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0002_externalevalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useralertmonitor',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='useralertmonitor',
            name='threshold_method',
        ),
        migrations.RemoveField(
            model_name='useralertmonitor',
            name='threshold_value',
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='alert_frequency',
            field=models.IntegerField(default=60, help_text='Frequency of alert checks in minutes.', validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='auto_threshold_time_window',
            field=models.PositiveIntegerField(default=10080, help_text='For auto-thresholding. The time window in minutes to calculate the historical mean'),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='critical_threshold_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, help_text='The last time the monitor was checked for alerts.', null=True),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='slack_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='slack_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='threshold_operator',
            field=models.CharField(choices=[('greater_than', 'Greater than'), ('less_than', 'Less than')], default='greater_than', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='warning_threshold_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='is_mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='logs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='metric',
            field=models.CharField(blank=True, help_text='Id of the evaluation template.', max_length=2556, null=True),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='metric_type',
            field=models.CharField(choices=[('count_of_errors', 'Count of errors'), ('error_rates_for_function_calling', 'Error rates for function calling'), ('error_free_session_rates', 'Error free session rates'), ('user_experience_error', 'User experience error'), ('service_provider_error_rates', 'Service provider error rates'), ('llm_api_failure_rates', 'LLM API failure rates'), ('span_response_time', 'Span response time'), ('llm_response_time', 'LLM response time'), ('token_usage', 'Token usage'), ('daily_tokens_spent', 'Daily tokens spent'), ('monthly_tokens_spent', 'Monthly tokens spent'), ('credit_exhaustion', 'Credit exhaustion'), ('evaluation_metrics', 'Evaluation metrics'), ('rate_limit_alert', 'Rate limit alert')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='threshold_metric_value',
            field=models.CharField(blank=True, help_text='For choice and pass/fail evals, the specific metric value to monitor.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='threshold_type',
            field=models.CharField(choices=[('static', 'Static'), ('percentage_change', 'Percentage change'), ('anomaly_detection', 'Anomaly detection')], default='percentage_change', help_text='Method to set the threshold for the monitor (Static or Percentage change).', max_length=50),
        ),
        migrations.CreateModel(
            name='UserAlertMonitorLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning')], max_length=100)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.useralertmonitor')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
