# Generated by Django 5.1.8 on 2025-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0003_alter_useralertmonitor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertmonitor',
            name='metric_type',
            field=models.CharField(choices=[('count_of_errors', 'Count of errors'), ('error_rates_for_function_calling', 'Error rates for function calling'), ('error_free_session_rates', 'Error free session rates'), ('service_provider_error_rates', 'Service provider error rates'), ('llm_api_failure_rates', 'LLM API failure rates'), ('span_response_time', 'Span response time'), ('llm_response_time', 'LLM response time'), ('token_usage', 'Token usage'), ('daily_tokens_spent', 'Daily tokens spent'), ('monthly_tokens_spent', 'Monthly tokens spent'), ('evaluation_metrics', 'Evaluation metrics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='threshold_type',
            field=models.CharField(choices=[('static', 'Static'), ('percentage_change', 'Percentage Change')], default='percentage_change', help_text='Method to set the threshold for the monitor (Static or Percentage change).', max_length=50),
        ),
    ]
