# Generated by Django 5.1.8 on 2025-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_alter_useralertmonitor_metric_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertmonitorlog',
            name='time_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useralertmonitorlog',
            name='time_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
