# Generated by Django 5.1.8 on 2025-08-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0003_alter_observationspan_eval_status'),
        ('tracer', '0006_alter_observationspan_eval_status_delete_tracealert'),
    ]

    operations = [
    ]
