# Generated by Django 5.1.8 on 2025-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('model_hub', '0010_cell_completion_tokens_cell_prompt_tokens_and_more'),
        ('tracer', '0007_merge_20250803_1321'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inlineeval',
            index=models.Index(fields=['status', 'span_id'], name='tracer_inli_status_78e96c_idx'),
        ),
    ]
