# Generated by Django 5.1.8 on 2025-08-04 11:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('tracer', '0007_merge_20250803_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.project')),
            ],
            options={
                'unique_together': {('project', 'organization', 'user_id', 'user_id_type')},
            },
        ),
        migrations.AddField(
            model_name='observationspan',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracer.enduser'),
        )
    ]
