# Generated by Django 5.1.8 on 2025-08-04 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('model_hub', '0009_alter_column_status_alter_errorlocalizertask_source_and_more'),
        ('tracer', '0007_merge_20250803_1321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddIndex(
            model_name='customevalconfig',
            index=models.Index(fields=['project', 'name'], name='tracer_cust_project_98d288_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'name', 'trace_type'], name='tracer_proj_organiz_bf2ef6_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name', 'trace_type', 'organization'), name='unique_project_per_org_type'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('project', 'version'), name='unique_version_per_project'),
        ),
    ]
