# Generated by Django 5.1.8 on 2025-08-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0008_enduser_observationspan_end_user'),
        ('tracer', '0008_inlineeval_tracer_inli_status_78e96c_idx'),
    ]

    operations = [
    ]
