# Generated by Django 5.1.8 on 2025-08-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0008_alter_project_options_and_more'),
        ('tracer', '0009_merge_20250813_0953'),
    ]

    operations = [
    ]
