# Generated by Django 5.1.8 on 2025-08-15 13:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('model_hub', '0015_alter_column_data_type_alter_column_name_and_more'),
        ('tracer', '0010_merge_20250814_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='The version identifier, e.g., a git commit hash or version tag.', max_length=255)),
                ('eval_data', models.JSONField(blank=True, default=dict, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='tracer.project')),
            ],
            options={
                'db_table': 'tracer_evaluation_run',
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ci_cd_result', to='model_hub.evaluation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracer.evaluationrun')),
            ],
            options={
                'db_table': 'tracer_evaluation_result',
            },
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['project', 'version'], name='tracer_eval_project_cacad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationrun',
            unique_together={('project', 'version')},
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['evaluation_run'], name='tracer_eval_evaluat_3543a3_idx'),
        ),
    ]
