# Generated by Django 5.1.8 on 2025-08-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0015_alter_column_data_type_alter_column_name_and_more'),
        ('tracer', '0010_merge_20250814_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationspan',
            name='prompt_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.promptversion'),
        ),
    ]
