# Generated by Django 5.1.8 on 2025-08-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_organization_role_organizationmembership_and_more'),
        ('tracer', '0011_evaluationrun_evaluationresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='externalevalconfig',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_eval_configs', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='inlineeval',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_evals', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='useralertmonitor',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_monitors', to='accounts.workspace'),
        ),
    ]
