# Generated by Django 5.1.8 on 2025-08-25 17:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0011_evaluationrun_evaluationresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceErrorAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('agent_version', models.CharField(default='1.0', max_length=50)),
                ('memory_enhanced', models.BooleanField(default=False)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('total_errors', models.IntegerField(default=0)),
                ('high_impact_errors', models.IntegerField(default=0)),
                ('medium_impact_errors', models.IntegerField(default=0)),
                ('low_impact_errors', models.IntegerField(default=0)),
                ('recommended_priority', models.CharField(default='LOW', max_length=20)),
                ('factual_grounding_score', models.FloatField(blank=True, null=True)),
                ('factual_grounding_reason', models.TextField(blank=True, null=True)),
                ('privacy_and_safety_score', models.FloatField(blank=True, null=True)),
                ('privacy_and_safety_reason', models.TextField(blank=True, null=True)),
                ('instruction_adherence_score', models.FloatField(blank=True, null=True)),
                ('instruction_adherence_reason', models.TextField(blank=True, null=True)),
                ('optimal_plan_execution_score', models.FloatField(blank=True, null=True)),
                ('optimal_plan_execution_reason', models.TextField(blank=True, null=True)),
                ('insights', models.TextField(blank=True, null=True)),
                ('memory_context', models.JSONField(blank=True, default=dict)),
                ('grouped_errors_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_analyses', to='tracer.project')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_analyses', to='tracer.trace')),
            ],
            options={
                'db_table': 'tracer_trace_error_analysis',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='TraceErrorDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_id', models.CharField(max_length=20)),
                ('cluster_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=200)),
                ('impact', models.CharField(default='MEDIUM', max_length=20)),
                ('urgency_to_fix', models.CharField(default='HIGH', max_length=20)),
                ('location_spans', models.JSONField(blank=True, default=list)),
                ('evidence_snippets', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('root_causes', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('immediate_fix', models.TextField(blank=True, null=True)),
                ('trace_impact', models.TextField(blank=True, null=True)),
                ('trace_assessment', models.TextField(blank=True, null=True)),
                ('llm_analysis', models.TextField(blank=True, null=True)),
                ('memory_enhanced', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_details', to='tracer.traceerroranalysis')),
            ],
            options={
                'db_table': 'tracer_trace_error_detail',
                'ordering': ['error_id'],
            },
        ),
        migrations.CreateModel(
            name='TraceErrorGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=20)),
                ('error_type', models.CharField(max_length=200)),
                ('error_ids', models.JSONField(blank=True, default=list)),
                ('affected_spans', models.JSONField(blank=True, default=list)),
                ('combined_impact', models.CharField(default='MEDIUM', max_length=20)),
                ('combined_description', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('trace_impact', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_groups', to='tracer.traceerroranalysis')),
            ],
            options={
                'db_table': 'tracer_trace_error_group',
                'ordering': ['cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='ErrorMemory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(max_length=20)),
                ('memory_key', models.CharField(max_length=200)),
                ('memory_data', models.JSONField(blank=True, default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('memory_window_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_memories', to='tracer.project')),
            ],
            options={
                'db_table': 'tracer_error_memory',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['project', 'memory_type'], name='tracer_erro_project_ea2355_idx'), models.Index(fields=['memory_key'], name='tracer_erro_memory__ae8b26_idx'), models.Index(fields=['is_active'], name='tracer_erro_is_acti_336ee6_idx'), models.Index(fields=['last_updated'], name='tracer_erro_last_up_a306c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(max_length=100)),
                ('specific_error', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern_description', models.TextField(blank=True, null=True)),
                ('frequency', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('span_type', models.CharField(blank=True, max_length=50, null=True)),
                ('input_pattern', models.TextField(blank=True, null=True)),
                ('output_pattern', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('immediate_fix', models.TextField(blank=True, null=True)),
                ('root_causes', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='tracer.project')),
            ],
            options={
                'db_table': 'tracer_error_pattern',
                'ordering': ['-frequency', '-last_seen'],
                'indexes': [models.Index(fields=['project', 'category'], name='tracer_erro_project_d67290_idx'), models.Index(fields=['pattern_type', 'frequency'], name='tracer_erro_pattern_a6ce00_idx'), models.Index(fields=['tool_name'], name='tracer_erro_tool_na_be023a_idx'), models.Index(fields=['is_resolved'], name='tracer_erro_is_reso_84ff4b_idx'), models.Index(fields=['confidence_score'], name='tracer_erro_confide_4573e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='traceerroranalysis',
            index=models.Index(fields=['trace', 'analysis_date'], name='tracer_trac_trace_i_c37ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerroranalysis',
            index=models.Index(fields=['project', 'analysis_date'], name='tracer_trac_project_49f754_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerroranalysis',
            index=models.Index(fields=['overall_score'], name='tracer_trac_overall_ccccc3_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerroranalysis',
            index=models.Index(fields=['recommended_priority'], name='tracer_trac_recomme_34f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerroranalysis',
            index=models.Index(fields=['total_errors'], name='tracer_trac_total_e_c38541_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrordetail',
            index=models.Index(fields=['analysis', 'error_id'], name='tracer_trac_analysi_8d7cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrordetail',
            index=models.Index(fields=['category'], name='tracer_trac_categor_15c2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrordetail',
            index=models.Index(fields=['impact'], name='tracer_trac_impact_c7cd24_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrordetail',
            index=models.Index(fields=['urgency_to_fix'], name='tracer_trac_urgency_65baf9_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrordetail',
            index=models.Index(fields=['cluster_id'], name='tracer_trac_cluster_63dc83_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['analysis', 'cluster_id'], name='tracer_trac_analysi_89cf5f_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['error_type'], name='tracer_trac_error_t_c8fe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['combined_impact'], name='tracer_trac_combine_2535a2_idx'),
        ),
    ]
