# Generated by Django 5.1.8 on 2025-08-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0011_evaluationrun_evaluationresult_and_more'),
        ('tracer', '0011_observationspan_prompt_version'),
    ]

    operations = [
    ]
