# Generated by Django 5.1.8 on 2025-08-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0012_enduser_workspace_evaluationresult_workspace_and_more'),
        ('tracer', '0012_merge_20250821_1940'),
    ]

    operations = [
    ]
