# Generated by Django 5.1.8 on 2025-08-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0012_traceerroranalysis_traceerrordetail_traceerrorgroup_and_more'),
        ('tracer', '0013_merge_20250826_0926'),
    ]

    operations = [
    ]
