# Generated by Django 5.1.8 on 2025-08-29 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_ws_enabled_and_more'),
        ('tracer', '0013_merge_20250826_0926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_per_org_type',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name', 'trace_type', 'organization', 'workspace'), name='unique_project_per_org_type'),
        ),
    ]
