# Generated by Django 5.1.8 on 2025-09-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0022_merge_20250904_0542'),
        ('tracer', '0014_remove_project_unique_project_per_org_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlineeval',
            name='data',
        ),
        migrations.RemoveField(
            model_name='inlineeval',
            name='eval_explanation',
        ),
        migrations.RemoveField(
            model_name='inlineeval',
            name='eval_template',
        ),
        migrations.RemoveField(
            model_name='inlineeval',
            name='failure',
        ),
        migrations.RemoveField(
            model_name='inlineeval',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='inlineeval',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_evals', to='model_hub.evaluation'),
        ),
        migrations.AlterField(
            model_name='inlineeval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=255),
        ),
    ]
