# Generated by Django 5.1.8 on 2025-09-01 17:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0014_merge_20250828_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisErrorGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=20)),
                ('error_type', models.CharField(max_length=200)),
                ('error_ids', models.JSONField(blank=True, default=list)),
                ('affected_spans', models.JSONField(blank=True, default=list)),
                ('combined_impact', models.CharField(default='MEDIUM', max_length=20)),
                ('combined_description', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('trace_impact', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_error_groups', to='tracer.traceerroranalysis')),
            ],
            options={
                'db_table': 'tracer_analysis_error_group',
                'ordering': ['cluster_id'],
                'indexes': [models.Index(fields=['analysis', 'cluster_id'], name='tracer_anal_analysi_ec31f1_idx'), models.Index(fields=['error_type'], name='tracer_anal_error_t_8d1ea3_idx'), models.Index(fields=['combined_impact'], name='tracer_anal_combine_fa12b9_idx')],
            },
        ),
    ]
