# Generated by Django 5.1.8 on 2025-09-02 17:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0015_analysiserrorgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceErrorAnalysisTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sampling_rate', models.FloatField(default=0.1, help_text='Percentage of traces to analyze (0-1)')),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting', 'Waiting'), ('paused', 'Paused')], default='waiting', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_traces_analyzed', models.IntegerField(default=0)),
                ('total_errors_found', models.IntegerField(default=0)),
                ('failed_analyses', models.IntegerField(default=0)),
                ('failed_traces', models.ManyToManyField(blank=True, related_name='failed_error_analyses', to='tracer.trace')),
                ('last_trace_analyzed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_analyzed_by_task', to='tracer.trace')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trace_error_task', to='tracer.project')),
            ],
            options={
                'db_table': 'tracer_trace_error_analysis_task',
                'unique_together': {('project', 'deleted')},
            },
        ),
    ]
