# Generated by Django 5.1.8 on 2025-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0016_traceerroranalysistask'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceerroranalysistask',
            name='processed_traces',
            field=models.ManyToManyField(blank=True, help_text='Traces that have been selected and processed (successfully or not)', related_name='selected_for_error_analysis', to='tracer.trace'),
        ),
    ]
