# Generated by Django 5.1.8 on 2025-09-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0014_remove_project_unique_project_per_org_type_and_more'),
        ('tracer', '0017_traceerroranalysistask_processed_traces'),
    ]

    operations = [
    ]
