# Generated by Django 5.1.8 on 2025-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0018_merge_20250903_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traceerroranalysistask',
            name='processed_traces',
        ),
        migrations.AddField(
            model_name='trace',
            name='error_analysis_processed',
            field=models.BooleanField(default=False),
        ),
    ]
