# Generated by Django 5.1.8 on 2025-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0019_remove_traceerroranalysistask_processed_traces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='error_analysis_processed',
        ),
        migrations.AddField(
            model_name='trace',
            name='error_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['project', 'error_analysis_status', 'created_at'], name='tracer_trac_project_d6fec8_idx'),
        ),
    ]
