# Generated by Django 5.1.8 on 2025-09-03 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0020_remove_trace_error_analysis_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trace',
            name='tracer_trac_project_d6fec8_idx',
        ),
        migrations.RemoveIndex(
            model_name='traceerrorgroup',
            name='tracer_trac_analysi_89cf5f_idx',
        ),
        migrations.RemoveField(
            model_name='traceerrorgroup',
            name='analysis',
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='affected_traces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_error_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='error_groups', to='tracer.project'),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='total_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='unique_traces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='unique_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trace',
            name='error_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['project', 'cluster_id'], name='tracer_trac_project_c0f648_idx'),
        ),
    ]
