# Generated by Django 5.1.8 on 2025-09-04 09:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0021_remove_trace_tracer_trac_project_d6fec8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traceerrorgroup',
            name='affected_spans',
        ),
        migrations.RemoveField(
            model_name='traceerrorgroup',
            name='affected_traces',
        ),
        migrations.CreateModel(
            name='ErrorClusterTraces',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='tracer.traceerrorgroup')),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_cluster_spans', to='tracer.observationspan')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_cluster_traces', to='tracer.trace')),
            ],
            options={
                'db_table': 'tracer_error_cluster_traces',
                'indexes': [models.Index(fields=['cluster', 'trace'], name='tracer_erro_cluster_f92650_idx'), models.Index(fields=['cluster'], name='tracer_erro_cluster_dc2ec4_idx'), models.Index(fields=['trace'], name='tracer_erro_trace_i_fe34c4_idx'), models.Index(fields=['span'], name='tracer_erro_span_id_4f93e8_idx')],
                'unique_together': {('cluster', 'trace', 'span')},
            },
        ),
    ]
