# Generated by Django 5.1.8 on 2025-09-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0015_remove_inlineeval_data_and_more'),
        ('tracer', '0022_remove_traceerrorgroup_affected_spans_and_more'),
    ]

    operations = [
    ]
