# Generated by Django 5.1.8 on 2025-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0023_merge_20250905_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationspan',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='trace',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
