# Generated by Django 5.1.8 on 2025-09-17 18:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250908_0727'),
        ('tracer', '0024_customevalconfig_eval_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('vapi', 'Vapi'), ('eleven_labs', 'Eleven Labs'), ('retell', 'Retell')], max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('credentials', models.JSONField(default=dict, help_text='API keys and other credentials for the provider.')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observability_providers', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observability_providers', to='tracer.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observability_providers', to='accounts.workspace')),
            ],
            options={
                'db_table': 'tracer_observability_provider',
                'indexes': [models.Index(fields=['project', 'last_fetched_at', 'enabled', 'organization', 'workspace'], name='tracer_obse_project_05942b_idx')],
            },
        ),
    ]
