# Generated by Django 5.1.8 on 2025-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0025_observabilityprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationspan',
            name='observation_type',
            field=models.CharField(choices=[('tool', 'Tool'), ('chain', 'Chain'), ('llm', 'LLM'), ('retriever', 'Retriever'), ('embedding', 'Embedding'), ('agent', 'Agent'), ('reranker', 'Reranker'), ('unknown', 'Unknown'), ('guardrail', 'Guardrail'), ('evaluator', 'Evaluator'), ('conversation', 'Conversation')], max_length=20),
        ),
    ]
