# Generated by Django 5.1.8 on 2025-09-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0026_alter_observationspan_observation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observabilityprovider',
            name='credentials',
        ),
    ]
