# Generated by Django 5.1.8 on 2025-09-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0024_alter_observationspan_name_alter_trace_name'),
        ('tracer', '0026_alter_observationspan_observation_type'),
    ]

    operations = [
    ]
