# Generated by Django 5.1.8 on 2025-09-29 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0027_merge_20250925_0731'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='traceerrorgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('project', 'cluster_id'), name='unique_project_cluster_if_not_deleted'),
        ),
    ]
