# Generated by Django 5.1.8 on 2025-09-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0027_merge_20250925_0731'),
        ('tracer', '0027_remove_observabilityprovider_credentials'),
    ]

    operations = [
    ]
