# Generated by Django 5.1.8 on 2025-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0028_merge_20250925_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo'), ('prototype', 'Prototype'), ('simulator', 'Simulator')], default='prototype', max_length=20),
        ),
    ]
