# Generated by Django 5.1.8 on 2025-09-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0028_traceerrorgroup_unique_project_cluster_if_not_deleted'),
        ('tracer', '0029_alter_project_source'),
    ]

    operations = [
    ]
