# Generated by Django 5.1.8 on 2025-10-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0036_merge_20251001_0933'),
        ('tracer', '0030_merge_20250930_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationspan',
            name='prompt_label',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.promptlabel'),
        ),
    ]
