# Generated by Django 5.1.8 on 2025-10-30 01:06

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0036_merge_20251001_0933'),
        ('tracer', '0030_merge_20250930_1302'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationspan',
            name='cost',
        ),
        # migrations.AddIndex(
        #     model_name='observationspan',
        #     index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='tracer_obse_metadat_19717b_gin'),
        # ),
        migrations.AddIndex(
            model_name='traceannotation',
            index=models.Index(fields=['observation_span', 'annotation_label', 'created_at'], name='trace_annot_observa_d4c4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='traceannotation',
            index=models.Index(fields=['annotation_label', 'created_at'], name='trace_annot_annotat_dd91a1_idx'),
        ),
        migrations.AddIndex(
            model_name='traceannotation',
            index=models.Index(fields=['annotation_value_float'], name='trace_annot_annotat_8ee498_idx'),
        ),
        migrations.AddIndex(
            model_name='traceannotation',
            index=models.Index(fields=['annotation_value_bool'], name='trace_annot_annotat_30fccb_idx'),
        ),
    ]
