# Generated by Django 5.1.8 on 2025-10-16 11:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0036_merge_20251001_0933'),
        ('tracer', '0030_merge_20250930_1302'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observationspan',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='tracer_obse_metadat_19717b_gin'),
        ),
    ]
