# Generated by Django 5.1.8 on 2025-10-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0031_remove_observationspan_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationspan',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
