# Generated by Django 5.1.8 on 2025-10-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0032_auto_20251030_1000'),
        ('tracer', '0032_observationspan_cost'),
    ]

    operations = [
    ]
