# Generated by Django 5.1.8 on 2025-11-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0032_add_prompt_label_indexes'),
        ('tracer', '0033_merge_20251030_1927'),
    ]

    operations = [
    ]
