# Generated by Django 5.1.8 on 2025-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0033_merge_20251030_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='user_id_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('uuid', 'UUID'), ('custom', 'Custom')], max_length=50, null=True),
        ),
    ]
