# Generated by Django 5.1.8 on 2025-11-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0034_alter_enduser_user_id_type'),
        ('tracer', '0034_merge_20251103_0656'),
    ]

    operations = [
    ]
