# Generated by Django 5.1.8 on 2025-11-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0036_add_graph_query_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evallogger',
            name='evallog_config_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='evallogger',
            name='evallog_span_cfg_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='evallogger',
            name='evallog_trace_cfg_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='observationspan',
            name='span_proj_time_lat_idx',
        ),
        migrations.RemoveIndex(
            model_name='observationspan',
            name='span_proj_time_tok_idx',
        ),
        migrations.RemoveIndex(
            model_name='observationspan',
            name='span_proj_time_cost_idx',
        ),
        migrations.RemoveIndex(
            model_name='observationspan',
            name='span_trace_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='traceannotation',
            name='annot_label_time_float_idx',
        ),
        migrations.RemoveIndex(
            model_name='traceannotation',
            name='annot_label_time_bool_idx',
        ),
        migrations.RemoveIndex(
            model_name='traceannotation',
            name='annot_span_label_time_idx',
        ),
    ]
