# Generated by Django 5.1.8 on 2025-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0037_remove_evallogger_evallog_config_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationspan',
            name='input_backup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationspan',
            name='output_backup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
