# Generated by Django 5.1.8 on 2025-11-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0038_observationspan_input_backup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationspan',
            name='input_backup',
        ),
        migrations.RemoveField(
            model_name='observationspan',
            name='output_backup',
        ),
        migrations.AddField(
            model_name='observationspan',
            name='input_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationspan',
            name='output_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
