# Generated by Django 5.1.8 on 2025-11-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0039_remove_observationspan_input_backup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationspan',
            name='input',
        ),
        migrations.RemoveField(
            model_name='observationspan',
            name='output',
        ),
    ]
