# Generated by Django 5.1.8 on 2025-11-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0040_remove_observationspan_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationspan',
            old_name='input_json',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='observationspan',
            old_name='output_json',
            new_name='output',
        ),
    ]
