# Generated by Django 5.1.8 on 2025-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0041_rename_input_json_observationspan_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observabilityprovider',
            name='provider',
            field=models.CharField(choices=[('vapi', 'Vapi'), ('eleven_labs', 'Eleven Labs'), ('retell', 'Retell'), ('others, Others', 'Others')], max_length=255),
        ),
    ]
