# Generated by Django 5.1.8 on 2025-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0042_alter_observabilityprovider_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observabilityprovider',
            name='provider',
            field=models.CharField(choices=[('vapi', 'Vapi'), ('eleven_labs', 'Eleven Labs'), ('retell', 'Retell'), ('others', 'Others')], max_length=255),
        ),
    ]
