# Generated by Django 5.1.8 on 2025-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0047_alter_dataset_eval_reason_status'),
        ('tracer', '0044_alter_observationspan_eval_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationspan',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddIndex(
            model_name='observationspan',
            index=models.Index(fields=['start_time'], name='tracer_obse_start_t_05e60d_idx'),
        ),
        migrations.AddIndex(
            model_name='observationspan',
            index=models.Index(fields=['trace', 'start_time'], name='tracer_obse_trace_i_224882_idx'),
        ),
    ]
