# Generated by Django 5.1.8 on 2025-12-31 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0058_alter_agentdefinition_authentication_method_and_more'),
        ('tracer', '0045_alter_observationspan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplaySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('replay_type', models.CharField(choices=[('session', 'Session'), ('trace', 'Trace')], max_length=255)),
                ('ids', models.JSONField(blank=True, null=True)),
                ('select_all', models.BooleanField(default=False)),
                ('current_step', models.CharField(choices=[('init', 'Init'), ('generating', 'Generating Scenario'), ('completed', 'Completed')], default='init', max_length=20)),
                ('agent_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_sessions', to='simulate.agentdefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_sessions', to='tracer.project')),
                ('run_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_sessions', to='simulate.runtest')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_sessions', to='simulate.scenarios')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
