# Generated by Django 5.1.8 on 2026-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0046_replaysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observabilityprovider',
            name='provider',
            field=models.CharField(choices=[('vapi', 'Vapi'), ('eleven_labs', 'Eleven Labs'), ('retell', 'Retell'), ('livekit', 'LiveKit'), ('others', 'Others')], max_length=255),
        ),
    ]
