# Generated by Django 5.1.8 on 2026-03-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0047_add_livekit_provider_choice'),
        ('tracer', '0047_remove_observationspan_system_and_more'),
    ]

    operations = [
    ]
