# Generated by Django 5.1.8 on 2026-03-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0048_merge_20260310_1407'),
        ('tracer', '0059_dashboardwidget_dashboard_pos_idx'),
    ]

    operations = [
    ]
