# Generated by Django 5.1.8 on 2026-03-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0060_merge_20260325_0715'),
        ('tracer', '0060_merge_20260325_1051'),
    ]

    operations = [
    ]
