# Generated by Django 5.1.8 on 2026-04-08 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0061_merge_20260326_0747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCapability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Auto-generated: "Refund Processing"', max_length=255)),
                ('trace_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='0.0-1.0, traces without issues / total')),
                ('centroid_id', models.CharField(help_text='Reference to ClickHouse centroid for this capability cluster', max_length=255)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tracer_project_capability',
                'ordering': ['-trace_count'],
            },
        ),
        migrations.CreateModel(
            name='TraceScanConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sampling_rate', models.FloatField(default=1.0, help_text='0.0-1.0, fraction of traces to scan')),
                ('enabled', models.BooleanField(default=True)),
                ('scan_version', models.CharField(default='v7.2', max_length=20)),
            ],
            options={
                'db_table': 'tracer_trace_scan_config',
            },
        ),
        migrations.CreateModel(
            name='TraceScanIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Subcategory e.g. "Language-only"', max_length=100)),
                ('group', models.CharField(help_text='Scanner group e.g. "Tool Failures"', max_length=100)),
                ('fix_layer', models.CharField(help_text='"Tools" / "Prompt" / "Orchestration" / "Guardrails"', max_length=50)),
                ('confidence', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=2)),
                ('brief', models.TextField(help_text='Short description of the issue')),
            ],
            options={
                'db_table': 'tracer_trace_scan_issue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceScanResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('has_issues', models.BooleanField(default=False)),
                ('key_moments', models.JSONField(blank=True, default=list, help_text='[{"kevinified": "...", "verbatim": "..."}]')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='{tools_called, tools_available, turn_count}')),
                ('scan_version', models.CharField(default='v7.2', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tracer_trace_scan_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='errorclustertraces',
            name='eval_logger',
            field=models.ForeignKey(blank=True, help_text='Eval result that caused membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_memberships', to='tracer.evallogger'),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='eval_config',
            field=models.ForeignKey(blank=True, help_text='For eval-sourced clusters', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_groups', to='tracer.customevalconfig'),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='fix_layer',
            field=models.CharField(blank=True, help_text='"Tools" / "Prompt" / "Orchestration" / "Guardrails"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='issue_category',
            field=models.CharField(blank=True, help_text='Scanner: "Language-only", Eval: criteria or null', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='issue_group',
            field=models.CharField(blank=True, help_text='Scanner: "Tool Failures", Eval: eval name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='source',
            field=models.CharField(choices=[('scanner', 'Scanner'), ('eval', 'Eval')], default='scanner', max_length=20),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('acknowledged', 'Acknowledged'), ('fix_deployed', 'Fix Deployed'), ('resolved', 'Resolved')], default='for_review', max_length=20),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='success_trace',
            field=models.ForeignKey(blank=True, help_text='Precomputed nearest success trace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_for_groups', to='tracer.trace'),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='title',
            field=models.TextField(blank=True, help_text='Descriptive Sentry-style issue title', null=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='width',
            field=models.IntegerField(default=12),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['project', 'source'], name='tracer_trac_project_e524df_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['project', 'issue_group'], name='tracer_trac_project_8f4af6_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['status'], name='tracer_trac_status_9fcb99_idx'),
        ),
        migrations.AddField(
            model_name='projectcapability',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='tracer.project'),
        ),
        migrations.AddField(
            model_name='tracescanconfig',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_config', to='tracer.project'),
        ),
        migrations.AddField(
            model_name='tracescanissue',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Assigned after clustering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_issues', to='tracer.traceerrorgroup'),
        ),
        migrations.AddField(
            model_name='errorclustertraces',
            name='scan_issue',
            field=models.ForeignKey(blank=True, help_text='Scanner finding that caused membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_memberships', to='tracer.tracescanissue'),
        ),
        migrations.AddIndex(
            model_name='errorclustertraces',
            index=models.Index(fields=['scan_issue'], name='tracer_erro_scan_is_584ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='errorclustertraces',
            index=models.Index(fields=['eval_logger'], name='tracer_erro_eval_lo_b27736_idx'),
        ),
        migrations.AddField(
            model_name='tracescanresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='tracer.project'),
        ),
        migrations.AddField(
            model_name='tracescanresult',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='tracer.trace'),
        ),
        migrations.AddField(
            model_name='tracescanissue',
            name='scan_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tracer.tracescanresult'),
        ),
        migrations.AddIndex(
            model_name='projectcapability',
            index=models.Index(fields=['project', 'created_at'], name='tracer_proj_project_10ba05_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcapability',
            index=models.Index(fields=['project', 'success_rate'], name='tracer_proj_project_c24503_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanresult',
            index=models.Index(fields=['project', 'created_at'], name='tracer_trac_project_dc8301_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanresult',
            index=models.Index(fields=['trace'], name='tracer_trac_trace_i_cf00ba_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanresult',
            index=models.Index(fields=['status'], name='tracer_trac_status_c35b26_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanresult',
            index=models.Index(fields=['has_issues'], name='tracer_trac_has_iss_e6cb75_idx'),
        ),
        migrations.AddConstraint(
            model_name='tracescanresult',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('trace',), name='unique_scan_result_per_trace'),
        ),
        migrations.AddIndex(
            model_name='tracescanissue',
            index=models.Index(fields=['scan_result'], name='tracer_trac_scan_re_270fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanissue',
            index=models.Index(fields=['group'], name='tracer_trac_group_63e478_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanissue',
            index=models.Index(fields=['category'], name='tracer_trac_categor_61be4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanissue',
            index=models.Index(fields=['fix_layer'], name='tracer_trac_fix_lay_1c97c4_idx'),
        ),
        migrations.AddIndex(
            model_name='tracescanissue',
            index=models.Index(fields=['confidence'], name='tracer_trac_confide_41b7db_idx'),
        ),
    ]
