# Generated by Django 5.1.8 on 2026-03-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0060_saved_view'),
        ('tracer', '0061_merge_20260326_0747'),
    ]

    operations = [
    ]
