# Generated by Django 5.1.8 on 2026-04-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0062_merge_0060_saved_view_0061_merge_20260326_0747'),
    ]


    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
