# Generated by Django 5.1.8 on 2026-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0062_projectcapability_tracescanconfig_tracescanissue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceerrorgroup',
            name='status',
            field=models.CharField(choices=[('escalating', 'Escalating'), ('for_review', 'For Review'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='escalating', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracescanconfig',
            name='sampling_rate',
            field=models.FloatField(default=0.1, help_text='0.0-1.0, fraction of traces to scan'),
        ),
    ]
