# Generated by Django 5.1.8 on 2026-04-01 00:15

import django.db.models.deletion
import tracer.models.shared_link
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_eval_template_version'),
        ('tracer', '0062_merge_0060_saved_view_0061_merge_20260326_0747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('trace', 'Trace'), ('dashboard', 'Dashboard'), ('eval_run', 'Eval Run'), ('dataset', 'Dataset'), ('project', 'Project')], max_length=20)),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(db_index=True, default=tracer.models.shared_link.generate_share_token, max_length=64, unique=True)),
                ('access_type', models.CharField(choices=[('public', 'Anyone with the link'), ('restricted', 'Only specific people')], default='public', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SharedLinkAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveIndex(
            model_name='dashboardwidget',
            name='tracer_widget_dashboard_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboard',
            new_name='tracer_dash_workspa_124094_idx',
            old_name='tracer_dash_workspa_idx',
        ),
        migrations.RenameIndex(
            model_name='savedview',
            new_name='tracer_save_project_35a47b_idx',
            old_name='tracer_save_project_user_vis_idx',
        ),
        migrations.RenameIndex(
            model_name='savedview',
            new_name='tracer_save_project_ea122c_idx',
            old_name='tracer_save_project_vis_idx',
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='width',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='sharedlinkaccess',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_shared_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedlinkaccess',
            name='shared_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='tracer.sharedlink'),
        ),
        migrations.AddField(
            model_name='sharedlinkaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_link_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sharedlink',
            index=models.Index(fields=['resource_type', 'resource_id'], name='tracer_shar_resourc_f82ed7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedlinkaccess',
            unique_together={('shared_link', 'email')},
        ),
    ]
