# Generated by Django 5.1.8 on 2026-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0063_alter_traceerrorgroup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceerrorgroup',
            name='external_issue_id',
            field=models.CharField(blank=True, help_text='External issue identifier (e.g. TH-123, #456)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traceerrorgroup',
            name='external_issue_url',
            field=models.URLField(blank=True, help_text='URL of linked external issue (Linear, GitHub, Jira, etc.)', max_length=500, null=True),
        ),
    ]
