# Generated by Django 5.1.8 on 2026-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0063_add_shared_link_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='access_type',
            field=models.CharField(choices=[('public', 'Anyone with the link'), ('restricted', 'Only specific people')], default='restricted', max_length=16),
        ),
    ]
