# Generated by Django 5.1.8 on 2026-04-08 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20260407_1927'),
        ('tracer', '0064_add_tags_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationspan',
            name='eval_status',
            field=models.CharField(blank=True, choices=[('NotStarted', 'NotStarted'), ('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'PartialRun'), ('ExperimentEvaluation', 'ExperimentEvaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'PartialExtracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'PartialCompleted'), ('OptimizationEvaluation', 'OptimizationEvaluation'), ('Error', 'Error'), ('Cancelled', 'Cancelled')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='tab_type',
            field=models.CharField(choices=[('traces', 'Traces'), ('spans', 'Spans'), ('voice', 'Voice'), ('imagine', 'Imagine')], max_length=20),
        ),
        migrations.CreateModel(
            name='ImagineAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_id', models.CharField(max_length=100)),
                ('trace_id', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('workflow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagine_analyses', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagine_analyses', to='tracer.project')),
                ('saved_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagine_analyses', to='tracer.savedview')),
            ],
            options={
                'db_table': 'tracer_imagine_analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['saved_view', 'trace_id'], name='tracer_imag_saved_v_4460db_idx'), models.Index(fields=['trace_id', 'status'], name='tracer_imag_trace_i_76aa03_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('saved_view', 'widget_id', 'trace_id'), name='unique_imagine_analysis_per_widget_trace')],
            },
        ),
    ]
