# Generated by Django 5.1.8 on 2026-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0067_saved_view_user_detail_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaltask',
            name='sampling_rate',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
    ]
