# Generated by Django 5.1.8 on 2026-04-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0064_linear_integration'),
        ('tracer', '0068_alter_evaltask_sampling_rate'),
    ]

    operations = [
    ]
