# Generated by Django 5.1.8 on 2026-04-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0063_dashboardwidget_description'),
        ('tracer', '0069_merge_20260416_1406'),
    ]

    operations = [
    ]
