# Generated by Django 5.1.8 on 2026-04-28 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0071_observation_span_eval_attributes_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceerrorgroup',
            name='title',
            field=models.TextField(blank=True, help_text='Descriptive issue title', null=True),
        ),
        migrations.AddIndex(
            model_name='errorclustertraces',
            index=models.Index(fields=['cluster', '-created_at'], name='tracer_ect_cluster_created_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(condition=models.Q(('deleted', False)), fields=['project', '-last_seen'], name='tracer_teg_proj_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='traceerrorgroup',
            index=models.Index(fields=['project', 'fix_layer'], name='tracer_trac_project_04b36e_idx'),
        ),
    ]
