# Generated by Django 5.1.8 on 2026-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracer", "0073_merge_20260428_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaltask",
            name="row_type",
            field=models.CharField(
                choices=[
                    ("spans", "Spans"),
                    ("traces", "Traces"),
                    ("sessions", "Sessions"),
                    ("voiceCalls", "Voice Calls"),
                ],
                db_index=True,
                default="spans",
                max_length=32,
            ),
        ),
    ]
