# Generated by Django 5.1.8 on 2026-05-07 03:34
#
# Hand-edited for production safety:
#   1. ``atomic = False`` so each operation runs in its own transaction
#      (required by AddIndexConcurrently and recommended for the
#      NOT VALID -> VALIDATE constraint pattern).
#   2. The composite dedup index uses ``AddIndexConcurrently`` to avoid
#      table locks on a large prod ``tracer_eval_logger`` table.
#   3. The ``eval_logger_target_type_fks`` check constraint is added in
#      two steps via ``SeparateDatabaseAndState`` + raw SQL: ADD
#      CONSTRAINT ... NOT VALID (cheap, no table scan) followed by
#      VALIDATE CONSTRAINT (table scan, but only takes a SHARE UPDATE
#      EXCLUSIVE lock, NOT an ACCESS EXCLUSIVE lock — readers + writers
#      stay live). Django state still sees the AddConstraint via
#      state_operations so subsequent migrations don't drift.
#
# All existing rows on dev/staging/prod satisfy the new constraint
# (every current row has both observation_span and trace populated and
# defaults to target_type='span' via the column DEFAULT), so VALIDATE
# never raises.

import django.contrib.postgres.operations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("tracer", "0074_evaltask_row_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="evallogger",
            name="target_type",
            field=models.CharField(
                choices=[("span", "Span"), ("trace", "Trace"), ("session", "Session")],
                db_index=True,
                default="span",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="evallogger",
            name="trace_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_logs",
                to="tracer.tracesession",
            ),
        ),
        migrations.AlterField(
            model_name="evallogger",
            name="observation_span",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_logs",
                to="tracer.observationspan",
            ),
        ),
        migrations.AlterField(
            model_name="evallogger",
            name="trace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_logs",
                to="tracer.trace",
            ),
        ),
        # Small new column — regular AddIndex is fine (no table lock of
        # consequence on a column where every row is NULL initially).
        migrations.AddIndex(
            model_name="evallogger",
            index=models.Index(
                fields=["trace_session"], name="tracer_eval_trace_s_1c1186_idx"
            ),
        ),
        # Composite index used by the trace + session evaluator dedup
        # queries (PR4) and by span-only readers narrowing on target_type.
        # Concurrent build avoids ACCESS EXCLUSIVE lock on prod.
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name="evallogger",
            index=models.Index(
                fields=["eval_task_id", "target_type", "custom_eval_config"],
                name="eval_logger_task_target_idx",
            ),
        ),
        # Per-target_type FK shape constraint. Added in two steps so the
        # table scan happens under a non-blocking lock.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name="evallogger",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_type__in", ["span", "trace"]),
                                ("observation_span__isnull", False),
                                ("trace__isnull", False),
                                ("trace_session__isnull", True),
                            ),
                            models.Q(
                                ("target_type", "session"),
                                ("observation_span__isnull", True),
                                ("trace__isnull", True),
                                ("trace_session__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="eval_logger_target_type_fks",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tracer_eval_logger "
                        "ADD CONSTRAINT eval_logger_target_type_fks CHECK ("
                        "(target_type IN ('span', 'trace') "
                        " AND observation_span_id IS NOT NULL "
                        " AND trace_id IS NOT NULL "
                        " AND trace_session_id IS NULL) "
                        "OR (target_type = 'session' "
                        " AND observation_span_id IS NULL "
                        " AND trace_id IS NULL "
                        " AND trace_session_id IS NOT NULL)"
                        ") NOT VALID;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE tracer_eval_logger "
                        "DROP CONSTRAINT IF EXISTS eval_logger_target_type_fks;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tracer_eval_logger "
                        "VALIDATE CONSTRAINT eval_logger_target_type_fks;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
