from app.servable_models import ModelServing
from app.servable_models.constants import (
    MODEL_NAME_TO_SENTENCE_TRANSFORMER_MODEL_MAPPING,
)
from sentence_transformers import SentenceTransformer


class EmbeddingModel(ModelServing):
    _model_instance = None

    def __init__(
        self, model_name=MODEL_NAME_TO_SENTENCE_TRANSFORMER_MODEL_MAPPING["embedding"]
    ):
        """
        Initialize the EmbeddingModel instance by loading the SentenceTransformer model.

        Args:
            model_name (str): The name of the pre-trained SentenceTransformer model to load.
        """
        # Ensure that only one instance of the model is created (singleton pattern)
        if EmbeddingModel._model_instance is None:
            EmbeddingModel._model_instance = SentenceTransformer(
                model_name, trust_remote_code=True
            )
        self.model = EmbeddingModel._model_instance

    def preprocess(self, data):
        """
        Preprocess the input sentences for embedding.

        Args:
            data (list of str): List of sentences to preprocess.

        Returns:
            list of str: Preprocessed sentences, ready for embedding.

        In this case, preprocessing might involve tasks such as text normalization,
        though for SentenceTransformer, input text is typically used as-is.
        """
        # In this simple example, we assume no specific preprocessing is needed
        # but you can add text normalization or cleaning if required.
        return data

    def forward(self, data):
        """
        Generate embeddings for the preprocessed sentences.

        Args:
            data (list of str): List of preprocessed sentences.

        Returns:
            numpy.ndarray: Array of sentence embeddings generated by the model.

        This method utilizes the SentenceTransformer model to compute embeddings.
        """
        # Use the SentenceTransformer model to get sentence embeddings

        return self.model.encode(data)

    def postprocess(self, output):
        """
        Postprocess the embeddings if needed.

        Args:
            output (numpy.ndarray): Array of embeddings.

        Returns:
            numpy.ndarray: Postprocessed embeddings.

        In this case, embeddings are returned as-is, but you can add further
        processing if required.
        """
        # In this simple example, no postprocessing is applied
        return output
