# Generated by Django 5.1.8 on 2026-02-22 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('tracer', '0046_replaysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismGateway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('admin_token', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('degraded', 'Degraded'), ('unreachable', 'Unreachable')], default='disconnected', max_length=20)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('last_health_response', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_count', models.IntegerField(default=0)),
                ('model_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prism_gateways', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prism_gateways', to='accounts.workspace')),
            ],
            options={
                'db_table': 'prism_gateway',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrismProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prism.prismgateway')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prism_projects', to='accounts.organization')),
                ('tracer_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prism_project', to='tracer.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prism_projects', to='accounts.workspace')),
            ],
            options={
                'db_table': 'prism_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrismAPIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_key_id', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('allowed_models', models.JSONField(blank=True, default=list)),
                ('allowed_providers', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prism_api_keys', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prism_api_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prism_api_keys', to='accounts.workspace')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='prism.prismgateway')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='prism.prismproject')),
            ],
            options={
                'db_table': 'prism_api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrismRequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_model', models.CharField(blank=True, default='', max_length=255)),
                ('latency_ms', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('status_code', models.IntegerField(default=0)),
                ('is_stream', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cache_hit', models.BooleanField(default=False)),
                ('fallback_used', models.BooleanField(default=False)),
                ('guardrail_triggered', models.BooleanField(default=False)),
                ('api_key_id', models.CharField(blank=True, default='', max_length=255)),
                ('user_id', models.CharField(blank=True, default='', max_length=255)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('routing_strategy', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='prism.prismgateway')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prism_request_logs', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prism_request_logs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'prism_request_log',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prismgateway',
            index=models.Index(fields=['organization'], name='prism_gatew_organiz_0d96d6_idx'),
        ),
        migrations.AddIndex(
            model_name='prismgateway',
            index=models.Index(fields=['organization', 'workspace'], name='prism_gatew_organiz_241445_idx'),
        ),
        migrations.AddConstraint(
            model_name='prismgateway',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'workspace', 'name'), name='unique_prism_gateway_per_org_workspace'),
        ),
        migrations.AddIndex(
            model_name='prismproject',
            index=models.Index(fields=['organization'], name='prism_proje_organiz_5798fd_idx'),
        ),
        migrations.AddIndex(
            model_name='prismproject',
            index=models.Index(fields=['gateway'], name='prism_proje_gateway_ca4730_idx'),
        ),
        migrations.AddConstraint(
            model_name='prismproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('gateway', 'name'), name='unique_prism_project_per_gateway'),
        ),
        migrations.AddIndex(
            model_name='prismapikey',
            index=models.Index(fields=['organization'], name='prism_api_k_organiz_12dbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='prismapikey',
            index=models.Index(fields=['gateway'], name='prism_api_k_gateway_cc22c5_idx'),
        ),
        migrations.AddIndex(
            model_name='prismapikey',
            index=models.Index(fields=['gateway_key_id'], name='prism_api_k_gateway_ebb7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='prismapikey',
            index=models.Index(fields=['status'], name='prism_api_k_status_733623_idx'),
        ),
        migrations.AddConstraint(
            model_name='prismapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('gateway', 'gateway_key_id'), name='unique_prism_api_key_per_gateway'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['organization', '-started_at'], name='prism_reque_organiz_b3d195_idx'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['gateway', '-started_at'], name='prism_reque_gateway_aa0973_idx'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['model'], name='prism_reque_model_eeaf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['provider'], name='prism_reque_provide_fb4304_idx'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['api_key_id'], name='prism_reque_api_key_3986d3_idx'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['status_code'], name='prism_reque_status__725a20_idx'),
        ),
        migrations.AddIndex(
            model_name='prismrequestlog',
            index=models.Index(fields=['is_error'], name='prism_reque_is_erro_eacbca_idx'),
        ),
    ]
