# Generated by Django 5.1.8 on 2026-02-25 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('prism', '0004_prismorgconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismGuardrailPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('project', 'Project'), ('key', 'Key')], default='global', max_length=20)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('mode', models.CharField(choices=[('enforce', 'Enforce'), ('monitor', 'Monitor')], default='enforce', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('applied_keys', models.JSONField(blank=True, default=list)),
                ('applied_projects', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'prism_guardrail_policy',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='prismorgconfig',
            new_name='prism_org_c_organiz_186d51_idx',
            old_name='prism_org_c_organiz_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='prismorgconfig',
            new_name='prism_org_c_organiz_0069d3_idx',
            old_name='prism_org_c_organiz_act_idx',
        ),
        migrations.AddField(
            model_name='prismguardrailpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prism_guardrail_policies', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='prismguardrailpolicy',
            index=models.Index(fields=['organization'], name='prism_guard_organiz_150856_idx'),
        ),
        migrations.AddConstraint(
            model_name='prismguardrailpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name'), name='unique_prism_guardrail_policy_name'),
        ),
    ]
