# Generated by Django 5.1.8 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prism", "0016_prismorgconfig_model_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="prismorgconfig",
            name="model_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
