# Generated by Django 5.1.8 on 2026-03-04 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('prism', '0017_prismorgconfig_model_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismProviderCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_credentials', models.BinaryField()),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_format', models.CharField(default='openai', max_length=50)),
                ('models_list', models.JSONField(blank=True, default=list)),
                ('default_timeout_seconds', models.IntegerField(default=60)),
                ('max_concurrent', models.IntegerField(default=100)),
                ('conn_pool_size', models.IntegerField(default=100)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prism_provider_credential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='prismorgconfig',
            name='providers',
        ),
        migrations.AddField(
            model_name='prismapikey',
            name='key_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='prismapikey',
            index=models.Index(fields=['key_hash'], name='prism_api_k_key_has_076d17_idx'),
        ),
        migrations.AddField(
            model_name='prismprovidercredential',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to='prism.prismgateway'),
        ),
        migrations.AddField(
            model_name='prismprovidercredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prism_provider_credentials', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='prismprovidercredential',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prism_provider_credentials', to='accounts.workspace'),
        ),
        migrations.AddIndex(
            model_name='prismprovidercredential',
            index=models.Index(fields=['organization'], name='prism_provi_organiz_af8bee_idx'),
        ),
        migrations.AddIndex(
            model_name='prismprovidercredential',
            index=models.Index(fields=['gateway'], name='prism_provi_gateway_6a6c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='prismprovidercredential',
            index=models.Index(fields=['provider_name'], name='prism_provi_provide_1cb6e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='prismprovidercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'gateway', 'provider_name'), name='unique_prism_provider_per_org_gateway'),
        ),
    ]
