# Generated by Django 5.1.8 on 2026-03-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prism', '0019_workspace_and_shadow_org_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prismrequestlog',
            options={'ordering': ['-created_at']},
        ),
    ]
