# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prism', '0020_request_log_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='prismguardrailpolicy',
            name='encrypted_check_configs',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
