# Generated by Django 5.1.8 on 2026-03-09 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('prism', '0021_prismguardrailpolicy_encrypted_check_configs'),
        ('tracer', '0046_replaysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prismgateway',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='prismgateway',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='prismrequestlog',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='prismapikey',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='prismprovidercredential',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='prismproject',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='prismshadowresult',
            name='gateway',
        ),
        migrations.RemoveConstraint(
            model_name='prismapikey',
            name='unique_prism_api_key_per_gateway',
        ),
        migrations.RemoveConstraint(
            model_name='prismproject',
            name='unique_prism_project_per_gateway',
        ),
        migrations.RemoveConstraint(
            model_name='prismprovidercredential',
            name='unique_prism_provider_per_org_gateway',
        ),
        migrations.RemoveIndex(
            model_name='prismapikey',
            name='prism_api_k_gateway_cc22c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='prismproject',
            name='prism_proje_gateway_ca4730_idx',
        ),
        migrations.RemoveIndex(
            model_name='prismprovidercredential',
            name='prism_provi_gateway_6a6c6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='prismrequestlog',
            name='prism_reque_gateway_aa0973_idx',
        ),
        migrations.RemoveIndex(
            model_name='prismshadowresult',
            name='prism_prism_gateway_51af5c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='prismshadowexperiment',
            unique_together={('organization', 'name')},
        ),
        migrations.AddConstraint(
            model_name='prismapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('gateway_key_id',), name='unique_prism_api_key_id'),
        ),
        migrations.AddConstraint(
            model_name='prismproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name'), name='unique_prism_project_per_org'),
        ),
        migrations.AddConstraint(
            model_name='prismprovidercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'provider_name'), name='unique_prism_provider_per_org'),
        ),
        migrations.RemoveField(
            model_name='prismshadowexperiment',
            name='gateway',
        ),
        migrations.DeleteModel(
            name='PrismGateway',
        ),
    ]
