# Generated by Django 5.1.8 on 2026-03-15 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_backfill_rbac_data'),
        ('prism', '0022_remove_prismgateway_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prismshadowexperiment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prismshadowexperiment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'name'), name='unique_prism_shadow_experiment_name'),
        ),
    ]
