# Generated by Django 5.1.8 on 2026-04-17 18:53

import agentcc.org_config_defaults
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20260407_1927'),
        ('prism', '0024_rename_prism_to_agentcc'),
        ('tracer', '0070_merge_20260417_1113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentccapikey',
            new_name='agentcc_api_organiz_d8761a_idx',
            old_name='prism_api_k_organiz_12dbc2_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccapikey',
            new_name='agentcc_api_gateway_c6b1ed_idx',
            old_name='prism_api_k_gateway_ebb7aa_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccapikey',
            new_name='agentcc_api_key_has_bdbf6d_idx',
            old_name='prism_api_k_key_has_076d17_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccapikey',
            new_name='agentcc_api_status_bd44ae_idx',
            old_name='prism_api_k_status_733623_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccblocklist',
            new_name='agentcc_blo_organiz_164fbc_idx',
            old_name='prism_block_organiz_35d2fb_idx',
        ),
        migrations.RenameIndex(
            model_name='agentcccustompropertyschema',
            new_name='agentcc_cus_organiz_31839a_idx',
            old_name='prism_custo_organiz_1db216_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccguardrailfeedback',
            new_name='agentcc_gua_organiz_bd33d2_idx',
            old_name='prism_guard_organiz_f514a3_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccguardrailfeedback',
            new_name='agentcc_gua_request_38db8c_idx',
            old_name='prism_guard_request_302ce8_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccguardrailfeedback',
            new_name='agentcc_gua_check_n_8b0eca_idx',
            old_name='prism_guard_check_n_953b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccguardrailpolicy',
            new_name='agentcc_gua_organiz_9feed4_idx',
            old_name='prism_guard_organiz_150856_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccorgconfig',
            new_name='agentcc_org_organiz_61a578_idx',
            old_name='prism_org_c_organiz_186d51_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccorgconfig',
            new_name='agentcc_org_organiz_35e9d9_idx',
            old_name='prism_org_c_organiz_0069d3_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccproject',
            new_name='agentcc_pro_organiz_bce00e_idx',
            old_name='prism_proje_organiz_5798fd_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccprovidercredential',
            new_name='agentcc_pro_organiz_cb6a70_idx',
            old_name='prism_provi_organiz_af8bee_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccprovidercredential',
            new_name='agentcc_pro_provide_b9e8cb_idx',
            old_name='prism_provi_provide_1cb6e7_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_organiz_cf90b8_idx',
            old_name='prism_reque_organiz_b3d195_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_model_4a70e3_idx',
            old_name='prism_reque_model_eeaf9c_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_provide_847ec0_idx',
            old_name='prism_reque_provide_fb4304_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_api_key_3cdc68_idx',
            old_name='prism_reque_api_key_3986d3_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_status__b95e42_idx',
            old_name='prism_reque_status__725a20_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_is_erro_e3a3f6_idx',
            old_name='prism_reque_is_erro_eacbca_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_session_5eb73b_idx',
            old_name='prism_reque_session_575c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccrequestlog',
            new_name='agentcc_req_user_id_b694ef_idx',
            old_name='prism_reque_user_id_4d5215_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccroutingpolicy',
            new_name='agentcc_rou_organiz_4ef704_idx',
            old_name='prism_routi_organiz_29a52d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccroutingpolicy',
            new_name='agentcc_rou_name_ec9bb8_idx',
            old_name='prism_routi_name_295711_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccsession',
            new_name='agentcc_ses_organiz_c0dfc8_idx',
            old_name='prism_sessi_organiz_4480c5_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccsession',
            new_name='agentcc_ses_session_9f77fd_idx',
            old_name='prism_sessi_session_8e348f_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccsession',
            new_name='agentcc_ses_status_235d46_idx',
            old_name='prism_sessi_status_65676e_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccshadowresult',
            new_name='agentcc_sha_experim_9077fe_idx',
            old_name='prism_prism_experim_358ef0_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccwebhook',
            new_name='agentcc_web_organiz_16da05_idx',
            old_name='prism_webho_organiz_9c3cfb_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccwebhookevent',
            new_name='agentcc_web_organiz_d95dbd_idx',
            old_name='prism_webho_organiz_8f6da6_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccwebhookevent',
            new_name='agentcc_web_webhook_11d49e_idx',
            old_name='prism_webho_webhook_70dda0_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccwebhookevent',
            new_name='agentcc_web_status_74dcd6_idx',
            old_name='prism_webho_status_6bdb02_idx',
        ),
        migrations.RenameIndex(
            model_name='agentccwebhookevent',
            new_name='agentcc_web_next_re_c13017_idx',
            old_name='prism_webho_next_re_2278c5_idx',
        ),
        migrations.AlterField(
            model_name='agentccapikey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_api_keys', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccapikey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcc_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentccapikey',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_api_keys', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccblocklist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_blocklists', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentcccustompropertyschema',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_custom_property_schemas', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccemailalert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_email_alerts', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccguardrailfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcc_guardrail_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentccguardrailfeedback',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_guardrail_feedback', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccguardrailpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_guardrail_policies', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccorgconfig',
            name='cost_tracking',
            field=models.JSONField(blank=True, default=agentcc.org_config_defaults.default_cost_tracking_config),
        ),
        migrations.AlterField(
            model_name='agentccorgconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcc_org_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentccorgconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_org_configs', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccorgconfig',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_org_configs', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccproject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_projects', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccproject',
            name='tracer_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcc_project', to='tracer.project'),
        ),
        migrations.AlterField(
            model_name='agentccproject',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_projects', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccprovidercredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_provider_credentials', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccprovidercredential',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_provider_credentials', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccrequestlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_request_logs', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccrequestlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_request_logs', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccroutingpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcc_routing_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentccroutingpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_routing_policies', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccsession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_sessions', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccsession',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_sessions', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccshadowexperiment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcc_shadow_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentccshadowexperiment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_shadow_experiments', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccshadowexperiment',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_shadow_experiments', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccshadowresult',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_shadow_results', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccshadowresult',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_shadow_results', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='agentccwebhook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_webhooks', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='agentccwebhookevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentcc_webhook_events', to='accounts.organization'),
        ),
    ]
