#!/usr/bin/env bash
# Interactive production setup for self-hosted Future AGI.
# Generates required secrets, prompts for URLs, writes deploy/.env.production,
# then pulls images and boots the stack via the production overlay.
#
# Usage: ./deploy/setup.sh [--skip-up] [--non-interactive]

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.production"
EXAMPLE_FILE="${SCRIPT_DIR}/.env.production.example"

SKIP_UP=0
NON_INTERACTIVE=0
for arg in "$@"; do
  case "$arg" in
    --skip-up) SKIP_UP=1 ;;
    --non-interactive) NON_INTERACTIVE=1 ;;
    -h|--help)
      sed -n '2,7p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
YELLOW=$'\033[33m'; RESET=$'\033[0m'
say()  { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s⚠%s %s\n' "$YELLOW" "$RESET" "$*"; }
err()  { printf '%s✗%s %s\n' "$RED" "$RESET" "$*" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || { err "missing dependency: $1"; exit 1; }
}

require docker
require openssl
docker compose version >/dev/null 2>&1 || { err "docker compose v2 required"; exit 1; }

prompt() {
  # prompt "Question" "default" → echoes user input or default.
  local question="$1" default="${2:-}" answer
  if (( NON_INTERACTIVE )); then
    printf '%s\n' "$default"
    return
  fi
  if [[ -n "$default" ]]; then
    read -r -p "${BOLD}${question}${RESET} ${DIM}[${default}]${RESET}: " answer
  else
    read -r -p "${BOLD}${question}${RESET}: " answer
  fi
  printf '%s\n' "${answer:-$default}"
}

prompt_required() {
  local question="$1" answer
  while :; do
    answer=$(prompt "$question" "")
    [[ -n "$answer" ]] && { printf '%s\n' "$answer"; return; }
    err "required"
  done
}

if [[ -f "$ENV_FILE" ]]; then
  warn "$ENV_FILE already exists."
  ans=$(prompt "Overwrite? (y/N)" "N")
  case "$ans" in y|Y|yes) ;; *) say "Keeping existing file. Run with --skip-up to just boot."; ;; esac
  if [[ "$ans" != y && "$ans" != Y && "$ans" != yes ]]; then
    [[ ! -f "$ENV_FILE" ]] && { err "no .env.production to use"; exit 1; }
  fi
fi

if [[ ! -f "$ENV_FILE" || "${ans:-}" == "y" || "${ans:-}" == "Y" || "${ans:-}" == "yes" ]]; then
  say ""
  say "${BOLD}== Public URLs ==${RESET}"
  FRONTEND_URL=$(prompt_required "Frontend URL (e.g. https://app.example.com)")
  VITE_HOST_API=$(prompt_required "Backend URL (e.g. https://api.example.com)")

  say ""
  say "${BOLD}== Release pins (one per image) ==${RESET}"
  read_default() { grep -E "^$1=" "$EXAMPLE_FILE" | cut -d= -f2- || echo ""; }
  FUTURE_AGI_VERSION=$(prompt        "Backend tag (futureagi/future-agi)"        "$(read_default FUTURE_AGI_VERSION)")
  FRONTEND_VERSION=$(prompt          "Frontend tag (futureagi/frontend)"         "$(read_default FRONTEND_VERSION)")
  AGENTCC_GATEWAY_VERSION=$(prompt   "Gateway tag (futureagi/agentcc-gateway)"   "$(read_default AGENTCC_GATEWAY_VERSION)")
  SERVING_VERSION=$(prompt           "Serving tag (futureagi/serving)"           "$(read_default SERVING_VERSION)")
  CODE_EXECUTOR_VERSION=$(prompt     "Code-executor tag (futureagi/code-executor)" "$(read_default CODE_EXECUTOR_VERSION)")

  say ""
  say "${BOLD}== Generating secrets ==${RESET}"
  SECRET_KEY=$(openssl rand -hex 32)
  AGENTCC_INTERNAL_API_KEY=$(openssl rand -hex 32)
  AGENTCC_ADMIN_TOKEN=$(openssl rand -hex 32)
  PG_PASSWORD=$(openssl rand -hex 24)
  MINIO_ROOT_PASSWORD=$(openssl rand -hex 24)
  RABBITMQ_PASSWORD=$(openssl rand -hex 24)
  ok "Generated SECRET_KEY, AGENTCC_INTERNAL_API_KEY, AGENTCC_ADMIN_TOKEN, PG_PASSWORD, MINIO_ROOT_PASSWORD, RABBITMQ_PASSWORD"

  say ""
  say "${BOLD}== Optional LLM provider keys ==${RESET}"
  say "${DIM}Press Enter to skip any.${RESET}"
  OPENAI_API_KEY=$(prompt "OPENAI_API_KEY" "")
  ANTHROPIC_API_KEY=$(prompt "ANTHROPIC_API_KEY" "")
  GOOGLE_API_KEY=$(prompt "GOOGLE_API_KEY" "")

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Edit by hand or re-run setup.sh to regenerate (overwrites this file).

SECRET_KEY=${SECRET_KEY}
AGENTCC_INTERNAL_API_KEY=${AGENTCC_INTERNAL_API_KEY}
AGENTCC_ADMIN_TOKEN=${AGENTCC_ADMIN_TOKEN}

PG_PASSWORD=${PG_PASSWORD}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

RABBITMQ_USER=futureagi
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

FUTURE_AGI_VERSION=${FUTURE_AGI_VERSION}
FRONTEND_VERSION=${FRONTEND_VERSION}
AGENTCC_GATEWAY_VERSION=${AGENTCC_GATEWAY_VERSION}
SERVING_VERSION=${SERVING_VERSION}
CODE_EXECUTOR_VERSION=${CODE_EXECUTOR_VERSION}

FRONTEND_URL=${FRONTEND_URL}
VITE_HOST_API=${VITE_HOST_API}

OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
EOF
  ok "Wrote $ENV_FILE (mode 600)"
fi

if (( SKIP_UP )); then
  say ""
  ok "Setup complete. Skipping boot per --skip-up."
  exit 0
fi

cd "$REPO_ROOT"

say ""
say "${BOLD}== Pulling images ==${RESET}"
docker compose --env-file "$ENV_FILE" \
  -f docker-compose.yml -f deploy/docker-compose.production.yml pull

say ""
say "${BOLD}== Starting stack ==${RESET}"
docker compose --env-file "$ENV_FILE" \
  -f docker-compose.yml -f deploy/docker-compose.production.yml up -d

say ""
ok "Stack is up. Check status with:"
say "  docker compose --env-file $ENV_FILE -f docker-compose.yml -f deploy/docker-compose.production.yml ps"
say ""
say "Create your first user (interactive):"
say "  docker compose --env-file $ENV_FILE -f docker-compose.yml -f deploy/docker-compose.production.yml exec backend python manage.py create_user"
