SYSTEM_PERSONAS = [
    {
        "persona_id": 1,
        "name": "The Impatient Driver",
        "description": "A truck driver who frequently uses a fuel app and gets frustrated when responses are slow or repetitive.",
        "gender": ["male"],
        "age_group": ["32-40"],
        "occupation": ["Freelancer"],
        "location": ["United States"],
        "personality": ["Impatient and direct"],
        "communication_style": ["Assertive"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.25"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["6"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Respond quickly and avoid repetition to maintain his patience.",
    },
    {
        "persona_id": 2,
        "name": "The Lost Newbie",
        "description": "A new truck driver exploring the fuel app for the first time who often asks for repeated guidance.",
        "gender": ["male"],
        "age_group": ["25-32"],
        "occupation": ["Freelancer"],
        "location": ["United States"],
        "personality": ["Friendly and cooperative"],
        "communication_style": ["Questioning"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.0"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["5"],
        "custom_properties": {},
        "additional_instruction": "Be patient, guide step-by-step, and confirm understanding after each instruction.",
    },
    {
        "persona_id": 3,
        "name": "The Stressed Accountant",
        "description": "An overworked accountant managing multiple clients who remains polite but gets anxious about delays.",
        "gender": ["male"],
        "age_group": ["32-40"],
        "occupation": ["Accountant"],
        "location": ["Canada"],
        "personality": ["Detail-oriented"],
        "communication_style": ["Technical"],
        "languages": ["English"],
        "accent": ["Canadian"],
        "conversation_speed": ["1.0"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Use clear, data-driven explanations and acknowledge his time constraints.",
    },
    {
        "persona_id": 4,
        "name": "The Frustrated Subscriber",
        "description": "A business owner upset with repeated subscription billing issues despite being a long-time user.",
        "gender": ["male"],
        "age_group": ["32-40"],
        "occupation": ["Business Owner"],
        "location": ["United States"],
        "personality": ["Impatient and direct"],
        "communication_style": ["Direct and concise"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.25"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["6"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Acknowledge frustration immediately and provide quick, solution-focused responses.",
    },
    {
        "persona_id": 5,
        "name": "The Confused First-Time User",
        "description": "A friendly teacher who recently joined the platform and needs reassurance while activating her account.",
        "gender": ["female"],
        "age_group": ["40-50"],
        "occupation": ["Teacher"],
        "location": ["United States"],
        "personality": ["Friendly and cooperative"],
        "communication_style": ["Questioning"],
        "languages": ["English"],
        "accent": ["Neutral"],
        "conversation_speed": ["0.75"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["4"],
        "custom_properties": {},
        "additional_instruction": "Speak slowly and reassure frequently to build her confidence in using the app.",
    },
    {
        "persona_id": 6,
        "name": "The Curious Evaluator",
        "description": "A manager evaluating a product for enterprise rollout, asking detailed and structured questions.",
        "gender": ["male"],
        "age_group": ["32-40"],
        "occupation": ["Manager"],
        "location": ["United Kingdom"],
        "personality": ["Analytical"],
        "communication_style": ["Detailed and elaborate"],
        "languages": ["English"],
        "accent": ["British"],
        "conversation_speed": ["1.0"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["6"],
        "interrupt_sensitivity": ["5"],
        "custom_properties": {},
        "additional_instruction": "Provide comprehensive explanations with facts, metrics, and clear comparisons.",
    },
    {
        "persona_id": 7,
        "name": "The No-Nonsense Executive",
        "description": "A confident female business owner who prefers concise, professional communication and fast decisions.",
        "gender": ["female"],
        "age_group": ["40-50"],
        "occupation": ["Business Owner"],
        "location": ["United States"],
        "personality": ["Professional and formal"],
        "communication_style": ["Direct and concise"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.5"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["7"],
        "interrupt_sensitivity": ["7"],
        "custom_properties": {},
        "additional_instruction": "Get to the point quickly, avoid small talk, and focus on results.",
    },
    {
        "persona_id": 8,
        "name": "The Frustrated Everyday User",
        "description": "An emotional and impatient customer service professional expressing irritation casually yet openly.",
        "gender": ["male"],
        "age_group": ["32-40"],
        "occupation": ["Customer Service"],
        "location": ["India"],
        "personality": ["Emotional"],
        "communication_style": ["Casual and friendly"],
        "languages": ["English"],
        "accent": ["Indian"],
        "conversation_speed": ["1.25"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["6"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Show empathy, use an understanding tone, and assure swift issue resolution.",
    },
    {
        "persona_id": 9,
        "name": "The Reserved Senior",
        "description": "A retired senior who is cautious and skeptical, preferring calm, clear explanations.",
        "gender": ["male"],
        "age_group": ["60+"],
        "occupation": ["Retired"],
        "location": ["United States"],
        "personality": ["Cautious and skeptical"],
        "communication_style": ["Simple and clear"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["0.75"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["4"],
        "interrupt_sensitivity": ["3"],
        "custom_properties": {},
        "additional_instruction": "Speak slowly, avoid jargon, and provide reassurance before giving instructions.",
    },
    {
        "persona_id": 10,
        "name": "The Emotional Loyalist",
        "description": "A marketing professional who's disappointed about recent changes but remains emotionally loyal.",
        "gender": ["female"],
        "age_group": ["32-40"],
        "occupation": ["Marketing Professional"],
        "location": ["Australia"],
        "personality": ["Emotional"],
        "communication_style": ["Detailed and elaborate"],
        "languages": ["English"],
        "accent": ["Australian"],
        "conversation_speed": ["1.0"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["5"],
        "custom_properties": {},
        "additional_instruction": "Listen empathetically and express appreciation for her long-term loyalty.",
    },
    {
        "persona_id": 11,
        "name": "The Hustling Homemaker",
        "description": "A motivated homemaker from India who manages family and side projects, looking for efficiency.",
        "gender": ["female"],
        "age_group": ["32-40"],
        "occupation": ["Homemaker"],
        "location": ["India"],
        "personality": ["Friendly and cooperative"],
        "communication_style": ["Simple and clear"],
        "languages": ["Hindi"],
        "accent": ["Indian"],
        "conversation_speed": ["1.25"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["5"],
        "custom_properties": {},
        "additional_instruction": "Be polite, helpful, and concise when explaining product steps in Hindi.",
    },
    {
        "persona_id": 12,
        "name": "The Telecom Customer in Distress",
        "description": "An emotional and talkative young customer service worker irritated with telecom issues.",
        "gender": ["female"],
        "age_group": ["25-32"],
        "occupation": ["Customer Service"],
        "location": ["United States"],
        "personality": ["Talkative"],
        "communication_style": ["Casual and friendly"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.25"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Show understanding and let her vent briefly before offering clear solutions.",
    },
    {
        "persona_id": 13,
        "name": "The Tech-Savvy Young Professional",
        "description": "A confident engineer who values efficiency and clear, technical communication.",
        "gender": ["male"],
        "age_group": ["25-32"],
        "occupation": ["Engineer"],
        "location": ["South Africa"],
        "personality": ["Confident"],
        "communication_style": ["Technical"],
        "languages": ["English"],
        "accent": ["Neutral"],
        "conversation_speed": ["1.25"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["6"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Use technical vocabulary and provide concise, data-driven answers.",
    },
    {
        "persona_id": 14,
        "name": "The Polite Senior Caller",
        "description": "A retired Australian who is polite and friendly, seeking help with patience and courtesy.",
        "gender": ["male"],
        "age_group": ["60+"],
        "occupation": ["Retired"],
        "location": ["Australia"],
        "personality": ["Friendly and cooperative"],
        "communication_style": ["Formal and polite"],
        "languages": ["English"],
        "accent": ["Australian"],
        "conversation_speed": ["0.75"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["4"],
        "interrupt_sensitivity": ["3"],
        "custom_properties": {},
        "additional_instruction": "Be respectful, avoid rushing, and confirm understanding after each step.",
    },
    {
        "persona_id": 15,
        "name": "The Hungry Customer in a Rush",
        "description": "A young female engineer frustrated by food delivery delays, switching between politeness and irritation.",
        "gender": ["female"],
        "age_group": ["25-32"],
        "occupation": ["Engineer"],
        "location": ["United States"],
        "personality": ["Impatient and direct"],
        "communication_style": ["Direct and concise"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.5"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["6"],
        "interrupt_sensitivity": ["7"],
        "custom_properties": {},
        "additional_instruction": "Keep responses fast and factual; update status without overexplaining.",
    },
    {
        "persona_id": 16,
        "name": "The Local Restaurant Owner",
        "description": "A professional business owner concerned about operational details and customer experience.",
        "gender": ["male"],
        "age_group": ["40-50"],
        "occupation": ["Business Owner"],
        "location": ["United States"],
        "personality": ["Detail-oriented"],
        "communication_style": ["Detailed and elaborate"],
        "languages": ["English"],
        "accent": ["American"],
        "conversation_speed": ["1.0"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["5"],
        "interrupt_sensitivity": ["6"],
        "custom_properties": {},
        "additional_instruction": "Provide business-relevant data clearly and maintain a professional tone.",
    },
    {
        "persona_id": 17,
        "name": "The Delivery Driver on the Move",
        "description": "A talkative freelancer multitasking during deliveries, occasionally distracted while explaining issues.",
        "gender": ["male"],
        "age_group": ["25-32"],
        "occupation": ["Freelancer"],
        "location": ["United States"],
        "personality": ["Easy-going"],
        "communication_style": ["Casual and friendly"],
        "languages": ["English"],
        "accent": ["Neutral"],
        "conversation_speed": ["1.25"],
        "background_sound": True,
        "finished_speaking_sensitivity": ["4"],
        "interrupt_sensitivity": ["4"],
        "custom_properties": {},
        "additional_instruction": "Use simple phrases and keep responses short to suit his multitasking pace.",
    },
    {
        "persona_id": 18,
        "name": "The Enterprise IT Admin",
        "description": "A focused and analytical engineer managing system reliability and technical escalations.",
        "gender": ["male"],
        "age_group": ["32-40"],
        "occupation": ["Engineer"],
        "location": ["United States"],
        "personality": ["Analytical"],
        "communication_style": ["Technical"],
        "languages": ["English"],
        "accent": ["Neutral"],
        "conversation_speed": ["1.25"],
        "background_sound": False,
        "finished_speaking_sensitivity": ["7"],
        "interrupt_sensitivity": ["7"],
        "custom_properties": {},
        "additional_instruction": "Communicate with precision and focus on actionable, technical details.",
    },
]
