/* eslint-disable no-unused-vars */
import React from "react";

export const modelConfigDefault = {
  model: "",
  model_detail: {
    model_name: "",
    logo_url: "",
    providers: "",
    is_available: false,
  },
  output_format: "string",
  tool_choice: "auto",
  tools: [],
  model_type: "all",
};

export const PromptWorkbenchContext = React.createContext({
  prompts: [],
  placeholders: [],
  currentTab: "Playground",
  setCurrentTab: (value) => {},
  setPrompts: (value) => {},
  versionHistoryOpen: false,
  setVersionHistoryOpen: (value) => {},
  variableDrawerOpen: false,
  setVariableDrawerOpen: (value) => {},
  variableData: {},
  setVariableData: (value) => {},
  placeholderData: {},
  setPlaceholderData: (value) => {},
  originalPlaceholderData: {},
  setOriginalPlaceholderData: (value) => {},
  valuesChanged: false,
  setValuesChanged: (value) => {},
  promptGeneratingStatus: false,
  results: [],
  modelConfig: { ...modelConfigDefault },
  // setModelConfig: (pre) => {},
  selectedVersions: [],
  setSelectedVersionByIndex: (value) => {},
  onRestoreVersion: (value) => {},
  reset: () => {},
  loadingPrompt: false,
  promptName: "",
  setPromptName: (value) => {},
  setPromptsByIndex: (a, b) => {},
  setResultsByIndex: (value) => {},
  setPlaceholdersByIndex: (a, b) => {},
  openSelectModel: false,
  setOpenSelectModel: (value) => {},
  setModelConfigByIndex: (a, b, c = {}) => {},
  addToCompare: () => {},
  saveAndRun: (index) => {},
  removeFromCompare: (val) => {},
  isImportDatasetDrawerOpen: false,
  setImportDatasetDrawerOpen: (value) => {},
  applyCompare: () => {},
  isEmptyPrompt: [],
  isVariablesDefined: true,
  setLoadingStatusByIndex: (value) => {},
  setLoadingStatus: (value) => {},
  isAddingDraft: false,
  getStreamingIds: (_a) => {},
  setStreamingIdForVersion: (value, def) => {},
  pushStoppedIds: (id) => {},
  closeSocketByIndex: (_index) => {},
  setPlaceholders: (value) => {},
  submitPlaceholders: () => {},
  setModelConfig: (_val) => {},
  templateFormat: "mustache",
  setTemplateFormat: (_val) => {},
});

export const usePromptWorkbenchContext = () => {
  return React.useContext(PromptWorkbenchContext);
};
