# Generated by Django 5.1.8 on 2025-07-09 07:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLMetadataModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('identity_type', models.PositiveSmallIntegerField(choices=[(1, 'AWS'), (2, 'OKTA'), (3, 'Google')])),
                ('relay_state', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('meta', models.TextField(blank=True, help_text='To store content of XML file.')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'SAML Meta',
                'verbose_name_plural': 'SAML Meta',
                'db_table': 'saml_meta',
                'ordering': ('-created_at',),
            },
        ),
    ]
