# Generated by Django 5.1.8 on 2026-03-04 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_orgapikey_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPOAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('redirect_uris', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_mode', models.CharField(choices=[('remote', 'Remote'), ('stdio', 'Stdio')], default='remote', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('oauth_token_encrypted', models.TextField(blank=True, null=True)),
                ('oauth_refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('oauth_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=100)),
                ('client_version', models.CharField(blank=True, default='', max_length=50)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_connections', to='accounts.orgapikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('disconnected', 'Disconnected'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('transport', models.CharField(choices=[('sse', 'SSE'), ('stdio', 'Stdio')], default='sse', max_length=10)),
                ('client_name', models.CharField(blank=True, default='', max_length=100)),
                ('client_version', models.CharField(blank=True, default='', max_length=50)),
                ('client_os', models.CharField(blank=True, default='', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mcp_server.mcpconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPToolGroupConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled_groups', models.JSONField(default=list)),
                ('disabled_tools', models.JSONField(default=list)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_config', to='mcp_server.mcpconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('tool_group', models.CharField(max_length=50)),
                ('request_params', models.JSONField(default=dict)),
                ('response_status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('embedded_agent_used', models.BooleanField(default=False)),
                ('embedded_agent_tokens', models.PositiveIntegerField(default=0)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_usage', to='accounts.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='mcp_server.mcpsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_usage', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_usage', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mcpconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'workspace'), name='unique_mcp_connection_per_user_workspace'),
        ),
        migrations.AddIndex(
            model_name='mcpsession',
            index=models.Index(fields=['user', 'status'], name='idx_mcp_session_user_status'),
        ),
        migrations.AddIndex(
            model_name='mcpsession',
            index=models.Index(fields=['organization', 'status'], name='idx_mcp_session_org_status'),
        ),
        migrations.AddIndex(
            model_name='mcpusagerecord',
            index=models.Index(fields=['organization', 'called_at'], name='idx_mcp_usage_org_time'),
        ),
        migrations.AddIndex(
            model_name='mcpusagerecord',
            index=models.Index(fields=['session', 'called_at'], name='idx_mcp_usage_session_time'),
        ),
        migrations.AddIndex(
            model_name='mcpusagerecord',
            index=models.Index(fields=['tool_name', 'called_at'], name='idx_mcp_usage_tool_time'),
        ),
        migrations.AddIndex(
            model_name='mcpusagerecord',
            index=models.Index(fields=['user', 'called_at'], name='idx_mcp_usage_user_time'),
        ),
    ]
