# Generated by Django 5.1.8 on 2026-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0002_mcpoauthcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpsession',
            name='transport',
            field=models.CharField(choices=[('streamable_http', 'Streamable HTTP'), ('sse', 'SSE'), ('stdio', 'Stdio')], default='streamable_http', max_length=20),
        ),
    ]
