"""
Data migration: populate ExperimentDatasetTable.experiment FK from M2M relationship.

Run AFTER Django schema migrations have created the FK field:
    python manage.py migrate_m2m_to_fk [--dry-run]

Idempotent: skips EDT records that already have experiment FK set.
"""

from django.core.management.base import BaseCommand
from django.db import connection, transaction
from tqdm import tqdm


class Command(BaseCommand):
    help = "Populate ExperimentDatasetTable.experiment FK from the M2M through table."

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Report what would be done without making changes.",
        )
        parser.add_argument(
            "--batch-size",
            type=int,
            default=1000,
            help="Number of records to update per batch (default: 1000).",
        )

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        batch_size = options["batch_size"]

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN - no changes will be made"))

        # Read M2M through table directly via SQL for reliability
        # The M2M table is auto-generated by Django: model_hub_experimentstable_experiments_datasets
        m2m_table = self._find_m2m_table()
        if not m2m_table:
            self.stdout.write(
                self.style.ERROR("Could not find M2M through table. Aborting.")
            )
            return

        self.stdout.write(f"Using M2M through table: {m2m_table}")

        with connection.cursor() as cursor:
            # Get all M2M entries
            cursor.execute(
                f"SELECT experimentstable_id, experimentdatasettable_id FROM {m2m_table} ORDER BY experimentstable_id, experimentdatasettable_id"  # noqa: S608
            )
            m2m_rows = cursor.fetchall()

        self.stdout.write(f"Found {len(m2m_rows)} M2M entries")

        # Build EDT -> experiment mapping
        # Handle edge case: if an EDT appears in multiple M2M rows, use the most recent experiment
        edt_to_experiment = {}
        duplicates = {}
        for exp_id, edt_id in m2m_rows:
            if edt_id in edt_to_experiment:
                if edt_id not in duplicates:
                    duplicates[edt_id] = [edt_to_experiment[edt_id]]
                duplicates[edt_id].append(exp_id)
            edt_to_experiment[edt_id] = exp_id

        if duplicates:
            self.stdout.write(
                self.style.WARNING(
                    f"Found {len(duplicates)} EDT records linked to multiple experiments. "
                    f"Using latest M2M entry for each."
                )
            )
            for edt_id, exp_ids in list(duplicates.items())[:5]:
                self.stdout.write(f"  EDT {edt_id} -> experiments: {exp_ids}")

        # Filter out EDT records that already have FK set
        from model_hub.models.experiments import ExperimentDatasetTable

        already_set = set(
            ExperimentDatasetTable.all_objects.filter(
                experiment__isnull=False
            ).values_list("id", flat=True)
        )

        to_update = {
            edt_id: exp_id
            for edt_id, exp_id in edt_to_experiment.items()
            if edt_id not in already_set
        }

        self.stdout.write(f"EDT records already migrated: {len(already_set)}")
        self.stdout.write(f"EDT records to update: {len(to_update)}")

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN complete. No changes made."))
            return

        if not to_update:
            self.stdout.write(
                self.style.SUCCESS("Nothing to migrate. All FK values already set.")
            )
            return

        # Batch update
        updated = 0
        items = list(to_update.items())
        total_to_update = len(to_update)
        batch_count = (total_to_update + batch_size - 1) // batch_size
        with transaction.atomic():
            progress = tqdm(
                range(0, len(items), batch_size),
                total=batch_count,
                desc="Migrating M2M→FK",
                unit="batch",
            )
            for i in progress:
                batch = items[i : i + batch_size]
                # Use raw SQL for efficient batch update
                with connection.cursor() as cursor:
                    cursor.executemany(
                        "UPDATE model_hub_experimentdatasettable SET experiment_id = %s WHERE id = %s",
                        [[str(exp_id), str(edt_id)] for edt_id, exp_id in batch],
                    )
                updated += len(batch)

                progress.set_postfix_str(f"{updated}/{total_to_update}")
                self.stdout.write(f"  Updated {updated}/{total_to_update} records...")

        self.stdout.write(
            self.style.SUCCESS(f"Successfully migrated {updated} EDT records.")
        )

        # Verify
        still_null = ExperimentDatasetTable.all_objects.filter(
            experiment__isnull=True, deleted=False
        ).count()
        if still_null > 0:
            self.stdout.write(
                self.style.WARNING(
                    f"{still_null} active EDT records still have null experiment FK "
                    f"(may be orphaned records not in M2M table)."
                )
            )
        else:
            self.stdout.write(
                self.style.SUCCESS("All active EDT records have experiment FK set.")
            )

    def _find_m2m_table(self):
        """Find the auto-generated M2M through table name."""
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT tablename FROM pg_tables WHERE tablename LIKE %s",
                ["%experimentstable_experiments_datasets%"],
            )
            rows = cursor.fetchall()
            if rows:
                return rows[0][0]

            # Try alternate naming
            cursor.execute(
                "SELECT tablename FROM pg_tables WHERE tablename LIKE %s",
                ["%experiments_datasets%"],
            )
            rows = cursor.fetchall()
            for row in rows:
                # Filter out the actual model table
                if "experimentdatasettable" not in row[0]:
                    return row[0]

        return None
