"""
Django settings for tfc project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Structured logging configuration
from tfc.logging import configure_structlog, get_logging_config, init_sentry

configure_structlog()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is set below from env var (search for "SECRET_KEY =")

# Environment classification — used below for security-sensitive defaults.
# Must be one of: local, test, dev, staging, prod. Defaults to "local".
ENV_TYPE = os.getenv("ENV_TYPE", "local").lower()
_IS_LOCAL = ENV_TYPE in ("local", "test")


def _split_env(name: str, default: str = "") -> list[str]:
    """Parse a comma-separated env var into a list."""
    raw = os.getenv(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True" if _IS_LOCAL else "False").lower() in (
    "true",
    "1",
    "t",
    "yes",
    "y",
)

# ── ALLOWED_HOSTS ─────────────────────────────────────────────────────────
# Open by default for self-host-friendly OSS conventions —
# production deployments should tighten this via the ALLOWED_HOSTS env var
# or enforce via a reverse proxy (nginx / Caddy / load balancer).
ALLOWED_HOSTS = _split_env("ALLOWED_HOSTS", "*")

# ── CORS (django-cors-headers) ────────────────────────────────────────────
# Default: permissive — any browser origin can hit the API. Production
# self-hosters should set CORS_ALLOWED_ORIGINS (comma-separated) to flip
# CORS_ALLOW_ALL_ORIGINS off when explicit origins are configured.
_cors_origins = _split_env("CORS_ALLOWED_ORIGINS")
if _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _cors_origins
else:
    CORS_ALLOW_ALL_ORIGINS = True
# Legacy alias (django-cors-headers pre-4.0)
CORS_ORIGIN_ALLOW_ALL = CORS_ALLOW_ALL_ORIGINS

CORS_ALLOWED_ORIGIN_REGEXES = _split_env("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_ORIGIN_REGEX_WHITELIST = CORS_ALLOWED_ORIGIN_REGEXES  # legacy alias

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# Scope the CORS middleware to API / ingest paths only. Admin pages, static
# files, and Django admin don't need CORS headers.
# CORS_URLS_REGEX = r"^/(api/|tracer/|v1/|oauth/|static/).*$"
CORS_URLS_REGEX = r"^/(?!admin/|docs/|swagger|__debug__/).*$"

# Extend django-cors-headers' defaults with tracing + workspace headers we
# actually read. Using `default_headers` means we automatically pick up any
# new safe headers added upstream without maintaining a hand-rolled list.
from corsheaders.defaults import default_headers  # noqa: E402

CORS_ALLOW_HEADERS = (
    *default_headers,
    *(
        "x-api-key",
        "x-secret-key",
        "x-workspace-id",
        "x-workspace-slug",
        "x-project-id",
        "x-organization-id",
        "sentry-trace",
        "baggage",
        "traceparent",
        "tracestate",
    ),
)

# CSRF_TRUSTED_ORIGINS is built dynamically after BASE_URL is resolved — see below.

# Application definition

INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for database cache
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
    "anymail",
    "drf_yasg",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    # custom apps
    "tfc.apps.TfcConfig",
    "sockets",
    "accounts",
    "model_hub",
    "tracer",
    "simulate",
    "agent_playground",
    "integrations",
    # AI tools shared layer (MCP + AI Assistant)
    "ai_tools",
    # MCP Server (protocol layer for external AI clients)
    "mcp_server",
    "agentcc",
    # gRPC framework
    "django_socio_grpc",
    # "djstripe"
    "saml2_auth",
    # Structured logging
    "django_structlog",
]

# EE apps.
#   - ee.usage: gated on presence only — it implements DeploymentMode.
#   - ee feature modules: gated on presence AND deployment mode (EE/Cloud).
from tfc.ee_loader import ee_feature_enabled, has_ee  # noqa: E402

if ee_feature_enabled("ee.falcon_ai"):
    INSTALLED_APPS.append("ee.falcon_ai.apps.FalconAIConfig")
if has_ee("ee.usage"):
    INSTALLED_APPS.append("ee.usage")

# Site ID for django.contrib.sites
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  #
    "tfc.middleware.cors_origin.OriginCheckMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tfc.telemetry.middleware.OTelContextMiddleware",  # OpenTelemetry context enrichment (after auth)
    "django_structlog.middlewares.RequestMiddleware",  # Structured logging - adds request_id, ip, etc.
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'tfc.middleware.debug_middleware.DebugMiddleware',
    "tfc.middleware.auth_monitoring.AuthMonitoringMiddleware",
    "tfc.utils.audit.AuditMiddleware",  # Stores request.user in thread-local for audit logging
    # 'tfc.middleware.query_timeout.QueryTimeoutMiddleware',
    "accounts.authentication.AuthMonitoringMiddleware",
    # Workspace context and permissions are now handled in APIKeyAuthentication class
    "tfc.middleware.workspace_context.WorkspaceContextMiddleware",
]
if has_ee("ee.usage"):
    MIDDLEWARE.append("ee.usage.middleware.rate_limit.RateLimitMiddleware")
    MIDDLEWARE.append("ee.usage.middleware.ee.EEFeatureMiddleware")
MIDDLEWARE += [
    # "tfc.middleware.workspace_permissions.WorkspacePermissionMiddleware",
    # "tfc.middleware.workspace_permissions.WorkspaceCRUDMiddleware",
    "accounts.middleware.require_2fa.Require2FAMiddleware",
    "tfc.middleware.posthog_middleware.PostHogMiddleware",  # API analytics (after auth)
]

# To check all the APIs
SWAGGER_SETTINGS = {
    "DEFAULT_INFO": "tfc.urls.info_api",
    "SECURITY_DEFINITIONS": {
        "X-Api-Key": {"type": "apiKey", "in": "header", "name": "X-Api-Key"},
        "X-Secret-Key": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Secret-Key",
        },
    },
    "USE_SESSION_AUTH": False,
}

ROOT_URLCONF = "tfc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tfc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("PG_DB", "tfc"),
        "USER": os.getenv("PG_USER", "user"),
        "PASSWORD": os.getenv("PG_PASSWORD", "password"),
        "HOST": os.getenv("PGBOUNCER_HOST", "pgbouncer"),
        "PORT": os.getenv("PGBOUNCER_PORT", 6432),
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": True,  # Verify connection is alive before use (prevents stale PgBouncer connections)
        "DISABLE_SERVER_SIDE_CURSORS": True,  # Required for PgBouncer transaction pooling
    },
}

# Read replica — only enabled when PGBOUNCER_READ_HOST is set.
# Falls back to default when not configured, so safe to deploy without a replica.
_read_host = os.getenv("PGBOUNCER_READ_HOST")
if _read_host:
    DATABASES["replica"] = {
        **DATABASES["default"],
        "HOST": _read_host,
        "PORT": os.getenv("PGBOUNCER_READ_PORT", os.getenv("PGBOUNCER_PORT", 6432)),
        "NAME": os.getenv("PG_READ_DB", os.getenv("PG_DB", "tfc")),
        "TEST": {"MIRROR": "default"},  # Tests use default DB, not a real replica
    }

DATABASE_ROUTERS = ["tfc.routers.ReadReplicaRouter"]

CLICKHOUSE = {
    "CH_HOST": os.getenv("CH_HOST"),
    "CH_PORT": os.getenv("CH_PORT", "8123"),
    "CH_USERNAME": os.getenv("CH_USERNAME", "default"),
    "CH_PASSWORD": os.getenv("CH_PASSWORD", ""),
    "CH_DATABASE": os.getenv("CH_DATABASE", "futureagi"),
    # Phase 6: ClickHouse Analytics Backend
    "CH_ENABLED": os.getenv("CH_ENABLED", "false").lower() in ("true", "1", "yes"),
    "CH_DUAL_WRITE": os.getenv("CH_DUAL_WRITE", "false").lower()
    in ("true", "1", "yes"),
    "CH_BATCH_SIZE": int(os.getenv("CH_BATCH_SIZE", "1000")),
    "CH_FLUSH_INTERVAL_SECONDS": int(os.getenv("CH_FLUSH_INTERVAL_SECONDS", "5")),
    "CH_MAX_RETRIES": int(os.getenv("CH_MAX_RETRIES", "3")),
    "CH_RETRY_DELAY_SECONDS": int(os.getenv("CH_RETRY_DELAY_SECONDS", "1")),
    # Query routing: "clickhouse", "postgres", or "auto" (ClickHouse with PG fallback)
    "CH_ANALYTICS_BACKEND": os.getenv("CH_ANALYTICS_BACKEND", "postgres"),
    # Connection pool settings
    "CH_POOL_SIZE": int(os.getenv("CH_POOL_SIZE", "10")),
    "CH_CONNECT_TIMEOUT": int(os.getenv("CH_CONNECT_TIMEOUT", "10")),
    "CH_SEND_TIMEOUT": int(os.getenv("CH_SEND_TIMEOUT", "300")),
    "CH_RECEIVE_TIMEOUT": int(os.getenv("CH_RECEIVE_TIMEOUT", "300")),
    # Per-query-type routing for gradual rollout
    # Values: "postgres", "clickhouse", "auto" (CH with PG fallback), "shadow" (both, compare, return PG)
    "CH_ROUTE_TIME_SERIES": os.getenv("CH_ROUTE_TIME_SERIES", "postgres"),
    "CH_ROUTE_TRACE_LIST": os.getenv("CH_ROUTE_TRACE_LIST", "postgres"),
    "CH_ROUTE_SESSION_LIST": os.getenv("CH_ROUTE_SESSION_LIST", "postgres"),
    "CH_ROUTE_EVAL_METRICS": os.getenv("CH_ROUTE_EVAL_METRICS", "postgres"),
    "CH_ROUTE_ERROR_ANALYSIS": os.getenv("CH_ROUTE_ERROR_ANALYSIS", "postgres"),
    "CH_ROUTE_SPAN_LIST": os.getenv("CH_ROUTE_SPAN_LIST", "postgres"),
    "CH_ROUTE_TRACE_OF_SESSION_LIST": os.getenv(
        "CH_ROUTE_TRACE_OF_SESSION_LIST", "postgres"
    ),
    "CH_ROUTE_SPAN_GRAPH": os.getenv("CH_ROUTE_SPAN_GRAPH", "postgres"),
    "CH_ROUTE_VOICE_CALL_LIST": os.getenv("CH_ROUTE_VOICE_CALL_LIST", "postgres"),
    "CH_ROUTE_SESSION_ANALYTICS": os.getenv("CH_ROUTE_SESSION_ANALYTICS", "postgres"),
    "CH_ROUTE_ANNOTATION_GRAPH": os.getenv("CH_ROUTE_ANNOTATION_GRAPH", "postgres"),
    "CH_ROUTE_TRACE_DETAIL": os.getenv("CH_ROUTE_TRACE_DETAIL", "postgres"),
    "CH_ROUTE_MONITOR_METRICS": os.getenv("CH_ROUTE_MONITOR_METRICS", "postgres"),
    "CH_ROUTE_ANNOTATION_DETAIL": os.getenv("CH_ROUTE_ANNOTATION_DETAIL", "postgres"),
    "CH_ROUTE_VOICE_CALL_DETAIL": os.getenv("CH_ROUTE_VOICE_CALL_DETAIL", "postgres"),
    # Shadow mode: run both PG+CH, compare results, return PG
    "CH_SHADOW_MODE": os.getenv("CH_SHADOW_MODE", "false").lower()
    in ("true", "1", "yes"),
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
# Add static files directory for development
STATICFILES_DIRS = ["/app/backend/staticfiles"]
STATIC_ROOT = "/app/backend/static"

# Configure WhiteNoise for static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Enable static file serving in staging/production
if os.getenv("ENV_TYPE") in ["staging", "prod"]:
    # Use WhiteNoise for production static file serving
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# This ensures Django serves static files in development
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("accounts.authentication.APIKeyAuthentication",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_PAGINATION_CLASS": "tfc.utils.pagination.ExtendedPageNumberPagination",
    "PAGE_SIZE": 10,  # Number of objects per page.
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "EXCEPTION_HANDLER": "accounts.authentication.custom_exception_handler",
}

# SECRET_KEY — sentinel default so the app starts for first-run self-host;
# non-local environments using the default bail out loudly.
_DEFAULT_SECRET_KEY = "django-insecure-<default-SECRET_KEY-replace-in-production>"
SECRET_KEY = os.getenv("SECRET_KEY") or _DEFAULT_SECRET_KEY

if not _IS_LOCAL and SECRET_KEY == _DEFAULT_SECRET_KEY:
    import sys as _sys

    _sys.stderr.write(
        "[FATAL] SECRET_KEY is set to the default value in a non-local "
        "environment. Generate a key and set SECRET_KEY env var. "
        "See: https://docs.djangoproject.com/en/stable/ref/settings/#secret-key\n"
    )
    _sys.exit(1)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=14
    ),  # or the time frame you want your token to be active
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1 * 30),  # or the time frame you prefer
    "ROTATE_REFRESH_TOKENS": False,  # If True, the refresh token will be rotated each time
    "BLACKLIST_AFTER_ROTATION": False,  # If True, the refresh token will be blacklisted after being rotated
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

AUTH_USER_MODEL = "accounts.User"

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": os.getenv(
        "MAILGUN_SENDER_DOMAIN"
    ),  # your Mailgun domain, if needed
}
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "anymail.backends.mailgun.EmailBackend"
    if os.getenv("MAILGUN_API_KEY")
    else "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL"
)  # if you don't already have this in settings
SERVER_EMAIL = os.getenv("SERVER_EMAIL")  # ditto (default from-email for Django errors)

APP_URL = os.getenv("APP_URL")

# ── Billing ───────────────────────────────────────────────────
BILLING_CONFIG_PATH = os.environ.get(
    "BILLING_CONFIG_PATH",
    os.path.join(BASE_DIR, "..", "ee", "billing.yaml"),
)

# EE license key (self-hosted only, JWT RS256)
EE_LICENSE_KEY = os.environ.get("EE_LICENSE_KEY", "")

# Cloud API key for managed AI features (self-hosted → cloud Agentcc gateway)
FUTUREAGI_CLOUD_API_KEY = os.environ.get("FUTUREAGI_CLOUD_API_KEY", "")
FUTUREAGI_CLOUD_GATEWAY_URL = os.environ.get(
    "FUTUREAGI_CLOUD_GATEWAY_URL", "https://gateway.futureagi.com"
)

# Internal Agentcc gateway (cloud deployment only)
INTERNAL_GATEWAY_URL = os.environ.get(
    "INTERNAL_GATEWAY_URL", "http://agentcc-internal:8090"
)
INTERNAL_GATEWAY_KEY = os.environ.get("INTERNAL_GATEWAY_KEY", "")

# ── Multi-Region ──────────────────────────────────────────────
REGION = os.environ.get("REGION", "us")
CLOUD_DEPLOYMENT = os.environ.get("CLOUD_DEPLOYMENT", "")
CLOUD_DEPLOYMENT_SECRET = os.environ.get("CLOUD_DEPLOYMENT_SECRET", "")
AVAILABLE_REGIONS = os.environ.get("AVAILABLE_REGIONS", "")

# Celery Configuration Options

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL", "amqp://user:password@rabbitmq:5672//"
)
CELERY_RESULT_BACKEND = "django-db"  # If you want to use Django's ORM
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_DEFAULT_RETRY_DELAY = 300  # Retry in 5 minutes.
CELERY_TASK_MAX_RETRIES = 0  # Maximum retry attempts.
CELERY_TASK_PUBLISH_RETRY = False
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks only after successful execution
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = None  # No limit

CELERY_IMPORTS = [
    "model_hub.tasks",
    "agentcc.tasks",
]

# Temporal Test Execution Configuration
# When enabled, test executions use Temporal workflows instead of Celery tasks
TEMPORAL_TEST_EXECUTION_ENABLED = os.getenv(
    "TEMPORAL_TEST_EXECUTION_ENABLED", "false"
).lower() in ("true", "1", "yes")

# Structured logging configuration with django-structlog
# This provides:
# - JSON output in production, colored console in development
# - Automatic request_id (correlation ID) on every log
# - user_id, user_email, organization_id, workspace_id after authentication
# - OpenTelemetry trace_id/span_id for distributed tracing
# - Process ID and thread ID for debugging
LOGGING = get_logging_config(str(BASE_DIR))

# Airbyte configurations
AIRBYTE_HOST = os.getenv("AIRBYTE_HOST")
AIRBYTE_PORT = os.getenv("AIRBYTE_PORT")
AIRBYTE_API_URL = f"http://{AIRBYTE_HOST}:{AIRBYTE_PORT}/api/v1"
SLACK_WEBHOOK_CHANNEL = os.getenv("SLACK_WEBHOOK_CHANNEL", "")
ERROR_LOGS_WEBHOOK = os.getenv("ERROR_LOGS_WEBHOOK", "")

AIRBYTE_HEADERS = {
    "Content-Type": "application/json",
    "Authorization": "Basic YWlyYnl0ZTpwYXNzd29yZA==",
}


LLM_KEYS = {
    "OPENAI": os.getenv("OPENAI_API_KEY"),
    "ANTHROPIC": os.getenv("ANTHROPIC_API_KEY"),
    "OPENROUTER": os.getenv("OPENROUTER_API_KEY"),
}

DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY", "")
CARTESIA_API_KEY = os.getenv("CARTESIA_API_KEY", "")

AWS = {
    "AWS_ACCESS_KEY_ID": os.getenv("AWS_ACCESS_KEY_ID"),
    "AWS_SECRET_ACCESS_KEY": os.getenv("AWS_SECRET_ACCESS_KEY"),
    "AWS_DEFAULT_REGION": os.getenv("AWS_DEFAULT_REGION"),
    "S3_FOR_DATA": os.getenv("S3_FOR_DATA"),
    "AWS_BUCKET_NAME": os.getenv("AWS_BUCKET_NAME"),
    "BEDROCK_REGION": os.getenv("BEDROCK_REGION"),
}

HUGGINGFACE_API_TOKEN = os.getenv("HUGGINGFACE_API_TOKEN", "")
HUGGINGFACE_API_TOKEN_1 = os.getenv("HUGGINGFACE_API_TOKEN_1", "")
HUGGINGFACE_API_TOKEN_2 = os.getenv("HUGGINGFACE_API_TOKEN_2", "")
HUBSPOT_URL = "https://api.hubapi.com/crm/v3/objects/contacts"
HUBSPOT_UPDATE_URL = (
    "https://api.hubapi.com/crm/v3/objects/contacts/{}?idProperty=email"
)
HUBSPOT_API_TOKEN = os.getenv("HUBSPOT_API_TOKEN", "")

VAPI_INDIAN_PHONE_NUMBER_ID = os.getenv(
    "VAPI_INDIAN_PHONE_NUMBER_ID", "6fe53c53-99cc-4090-bf65-6ea4d8267a95"
)

# VAPI Webhook Configuration
# Single system phone number for all outbound calls (webhook-based architecture)
VAPI_PHONE_NUMBER_ID = os.getenv("VAPI_PHONE_NUMBER_ID", "")
# HMAC secret for webhook signature verification (configure in VAPI dashboard)
VAPI_WEBHOOK_SECRET = os.getenv("VAPI_WEBHOOK_SECRET", "")

# Internal API authentication (shared secret for service-to-service calls)
INTERNAL_API_SECRET = os.getenv("INTERNAL_API_SECRET", "")

# LiveKit credentials (used for webhook verification and API calls)
LIVEKIT_URL = os.getenv("LIVEKIT_URL", "")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY", "")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET", "")

# Fallback concurrency when a LiveKit agent's credentials don't specify one.
# Kept low by default to protect LiveKit quota; override per-agent via the
# agent-definition API or globally via this env var.
DEFAULT_LIVEKIT_MAX_CONCURRENCY = int(os.getenv("DEFAULT_LIVEKIT_MAX_CONCURRENCY", "2"))

# Third-party provider URLs for WebRTC bridge connectors
VAPI_API_URL = os.getenv("VAPI_API_URL", "https://api.vapi.ai/call")
RETELL_API_URL = os.getenv(
    "RETELL_API_URL", "https://api.retellai.com/v2/create-web-call"
)
RETELL_LIVEKIT_URL = os.getenv(
    "RETELL_LIVEKIT_URL", "wss://retell-ai-4ihahnq7.livekit.cloud"
)

# Stripe
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET")
STRIPE_REDIRECT_DOMAIN = os.getenv("STRIPE_REDIRECT_DOMAIN")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
BUSINESS_MONTHLY_STRIPE_PRICE_ID = os.getenv("BUSINESS_MONTHLY_STRIPE_PRICE_ID")
BUSINESS_YEARLY_STRIPE_PRICE_ID = os.getenv("BUSINESS_YEARLY_STRIPE_PRICE_ID")

STRIPE_LIVE = bool(STRIPE_SECRET_KEY and STRIPE_SECRET_KEY.startswith("sk_live"))

BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL = [
    x
    for x in (os.getenv("BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL") or "").split(",")
    if x
]
if (
    BUSINESS_MONTHLY_STRIPE_PRICE_ID
    and BUSINESS_MONTHLY_STRIPE_PRICE_ID not in BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL
):
    BUSINESS_MONTHLY_STRIPE_PRICE_IDS_ALL.append(BUSINESS_MONTHLY_STRIPE_PRICE_ID)

BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL = [
    x for x in (os.getenv("BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL") or "").split(",") if x
]
if (
    BUSINESS_YEARLY_STRIPE_PRICE_ID
    and BUSINESS_YEARLY_STRIPE_PRICE_ID not in BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL
):
    BUSINESS_YEARLY_STRIPE_PRICE_IDS_ALL.append(BUSINESS_YEARLY_STRIPE_PRICE_ID)

# ── URL & OAuth — all from env vars, no ENV_TYPE branching ───
# ENV_TYPE / _IS_LOCAL are computed once at the top of the file; aliased here
# for existing callers that read the lowercase names.
env_type = ENV_TYPE
_is_local = _IS_LOCAL
_ssl = "http://" if _is_local else "https://"
ssl = _ssl  # exported — used by accounts.utils, accounts.views.workspace_management

BASE_URL = os.getenv(
    "BASE_URL", "http://localhost:8000" if _is_local else f"https://api.futureagi.com"
)
WEBSOCKET_ENDPOINT = os.getenv("WEBSOCKET_ENDPOINT", f"{BASE_URL}/call-websocket/")
MINIO_URL = os.getenv(
    "MINIO_URL", f"{_ssl}localhost:9005" if _is_local else f"{_ssl}{APP_URL}:9005"
)
UPLOAD_BUCKET_NAME = os.getenv(
    "UPLOAD_BUCKET_NAME", "fi-content-dev" if _is_local else "fi-content"
)

# Storage backend: "s3" (default/US), "gcs" (EU via S3-interop HMAC keys),
# or "minio" (self-hosted OSS local stack)
STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "s3")
GCS_HMAC_ACCESS_KEY = os.getenv("GCS_HMAC_ACCESS_KEY", "")
GCS_HMAC_SECRET_KEY = os.getenv("GCS_HMAC_SECRET_KEY", "")

AUTH0_CLIENT_ID = os.getenv("AUTH0_CLIENT_ID", "")
AUTH0_CLIENT_SECRET = os.getenv("AUTH0_CLIENT_SECRET", "")
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "")
MICROSOFT_CLIENT_ID = os.getenv("MICROSOFT_CLIENT_ID", "")
MICROSOFT_CLIENT_SECRET = os.getenv("MICROSOFT_CLIENT_SECRET", "")

sentry_sdk_enabled = (
    os.getenv("SENTRY_ENABLED", "" if _is_local else "true").lower() == "true"
)

# ── CSRF trusted origins (built dynamically from BASE_URL / APP_URL) ──
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173", "http://localhost:3031"]
if APP_URL:
    CSRF_TRUSTED_ORIGINS += [f"https://{APP_URL}", f"http://{APP_URL}"]
if BASE_URL:
    CSRF_TRUSTED_ORIGINS += [BASE_URL, BASE_URL.replace("https://", "http://")]
# Extra origins (comma-separated) for additional subdomains or custom deployments
_extra_csrf = os.getenv("EXTRA_CSRF_ORIGINS", "")
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf.split(",") if o.strip()]

AUTH0_CALLBACK_URL = f"{BASE_URL}/saml2_auth/auth/callback/"
GITHUB_CALLBACK_URL = f"{BASE_URL}/saml2_auth/github/callback/"
MICROSOFT_CALLBACK_URL = f"{BASE_URL}/saml2_auth/microsoft/callback/"
get_assertion_url = f"{BASE_URL}/saml2_auth/acs/"
default_next_url = f"{_ssl}{APP_URL}/dashboard/develop"
get_started_url = f"{_ssl}{APP_URL}/dashboard/get-started"
default_error_next_url = f"{_ssl}{APP_URL}/auth/jwt/login?denied=true"
get_entity_id = f"{_ssl}{APP_URL}"

get_name_id_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
AUTH0_DOMAIN = "accounts.google.com/o/oauth2"
AUTH0_ALGORITHM = "RS256"
GITHUB_API_ENDPOINT = "https://api.github.com"
GITHUB_OAUTH_URL = "https://github.com/login/oauth"
GOOGLE_USERINFO_API = "https://www.googleapis.com/oauth2/v1/userinfo"
MICROSOFT_OAUTH_URL = "https://login.microsoftonline.com/common/oauth2/v2.0"
MICROSOFT_GRAPH_API = "https://graph.microsoft.com/v1.0"

RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_ENABLED = os.getenv(
    "RECAPTCHA_ENABLED",
    "false" if env_type in {"local", "development"} else "true",
).lower() in ("true", "1", "yes")

# Integration encryption key (Fernet) for storing external platform credentials
INTEGRATION_ENCRYPTION_KEY = os.getenv("INTEGRATION_ENCRYPTION_KEY", "")
if not INTEGRATION_ENCRYPTION_KEY and env_type == "local":
    # Generate a throwaway key for local dev so the app starts without config.
    # Data encrypted with this key is lost on restart — production MUST set
    # INTEGRATION_ENCRYPTION_KEY as an env var.
    import base64
    import secrets as _secrets

    INTEGRATION_ENCRYPTION_KEY = base64.urlsafe_b64encode(
        _secrets.token_bytes(32)
    ).decode()
ENABLE_INTEGRATIONS = os.getenv("ENABLE_INTEGRATIONS", "false").lower() == "true"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": CELERY_BROKER_URL,
            "ssl_context": None,
            "expiry": 300,
            "local_capacity": 500,
            "local_expiry": 300,
            "remote_capacity": 500,
        },
    },
}
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_CACHE_URL", f"{REDIS_URL}"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "futureagi",
        "TIMEOUT": 600,  # Default timeout in seconds (10 minutes)
    }
}

# Authentication Security Settings
MAX_LOGIN_ATTEMPTS = 10  # Maximum failed login attempts before account lockout
ACCOUNT_LOCKOUT_DURATION = 1800  # 30 minutes in seconds
FAILED_ATTEMPTS_TIMEOUT = 3600  # 1 hour in seconds
MAX_LOGIN_ATTEMPTS_PER_HOUR = 10  # Rate limiting per IP
IP_BLOCK_DURATION = 3600  # 1 hour in seconds

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB in bytes
DATA_UPLOAD_MAX_NUMBER_FILES = 1000


init_sentry(component="django")

# gRPC-framework settings
GRPC_FRAMEWORK = {
    "ROOT_HANDLERS_HOOK": "tracer.handlers.grpc_handlers",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.APIKeyAuthentication",
    ],
    "SERVER_OPTIONS": [
        ("grpc.max_receive_message_length", 100 * 1024 * 1024),  # 100MB
        ("grpc.max_send_message_length", 100 * 1024 * 1024),  # 100MB
    ],
}

# WebAuthn / Passkeys
WEBAUTHN_RP_ID = os.getenv("WEBAUTHN_RP_ID", "localhost")
WEBAUTHN_RP_NAME = os.getenv("WEBAUTHN_RP_NAME", "FutureAGI")
WEBAUTHN_ORIGIN = os.getenv("WEBAUTHN_ORIGIN", "http://localhost:3031")

# 2FA challenge token TTLs (seconds)
TWO_FACTOR_CHALLENGE_TTL = 300  # 5 minutes
WEBAUTHN_CHALLENGE_TTL = 120  # 2 minutes
