# Generated by Django 5.1.8 on 2025-07-28 18:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the scenario', max_length=255)),
                ('source', models.TextField(help_text='Source content or reference for the scenario')),
                ('scenario_type', models.CharField(choices=[('graph', 'Graph'), ('script', 'Script'), ('dataset', 'Dataset')], default='graph', help_text='Type of scenario (graph, script, or dataset)', max_length=20)),
                ('organization', models.ForeignKey(help_text='Organization this scenario belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'simulate_scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
