# Generated by Django 5.1.8 on 2025-07-29 01:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('simulate', '0002_scenarios_dataset_scenarios_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(help_text='Name of the AI agent', max_length=255)),
                ('contact_number', models.CharField(help_text='Phone number associated with the AI agent', max_length=50)),
                ('inbound', models.BooleanField(help_text='Whether the agent handles inbound calls')),
                ('description', models.TextField(help_text="Detailed description of the AI agent's purpose and capabilities")),
                ('assistant_id', models.CharField(help_text='External identifier for the assistant', max_length=255)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('bg', 'Bulgarian'), ('zh', 'Chinese Simplified'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ms', 'Malay'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('es', 'Spanish'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese')], help_text='Language of the agent', max_length=2)),
                ('websocket_url', models.URLField(blank=True, help_text='WebSocket URL for real-time communication with the agent', max_length=500, null=True)),
                ('websocket_headers', models.JSONField(blank=True, default=dict, help_text='Headers to be sent to the websocket server', null=True)),
                ('organization', models.ForeignKey(help_text='Organization this agent definition belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_definitions', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Agent Definition',
                'verbose_name_plural': 'Agent Definitions',
                'db_table': 'simulate_agent_definition',
                'ordering': ['-created_at'],
            },
        ),
    ]
