# Generated by Django 5.1.8 on 2025-07-29 02:19

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0003_agentdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorAgent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the simulator agent', max_length=255)),
                ('prompt', models.TextField(help_text='System prompt for the agent')),
                ('voice_provider', models.CharField(help_text='Voice service provider', max_length=100)),
                ('voice_name', models.CharField(help_text='Specific voice to use', max_length=100)),
                ('interrupt_sensitivity', models.FloatField(default=0.5, help_text='Sensitivity for interruption detection (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('conversation_speed', models.FloatField(default=1.0, help_text='Speed of conversation (0.1-3.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)])),
                ('finished_speaking_sensitivity', models.FloatField(default=0.5, help_text='Sensitivity for detecting when speaker has finished (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model', models.CharField(help_text='LLM model to use', max_length=100)),
                ('llm_temperature', models.FloatField(default=0.7, help_text='Temperature setting for LLM (0-2)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_call_duration_in_minutes', models.IntegerField(default=30, help_text='Maximum call duration in minutes (1-180)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('initial_message_delay', models.IntegerField(default=0, help_text='Delay before initial message in seconds (0-60)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('initial_message', models.TextField(blank=True, default='', help_text='Initial message to send when conversation starts')),
            ],
            options={
                'db_table': 'simulator_agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
