# Generated by Django 5.1.8 on 2025-07-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('simulate', '0004_simulatoragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatoragent',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization this simulator agent belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='simulator_agents', to='accounts.organization'),
            preserve_default=False,
        ),
    ]
