# Generated by Django 5.1.8 on 2025-07-29 06:02

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('simulate', '0005_simulatoragent_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the test run', max_length=255)),
                ('dataset_row_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='IDs of dataset rows to run evaluations on', size=None)),
                ('evals', models.JSONField(blank=True, default=dict, help_text='Evaluation configurations and results', null=True)),
                ('agent_definition', models.ForeignKey(help_text='Agent definition for this test run', on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='simulate.agentdefinition')),
                ('organization', models.ForeignKey(help_text='Organization this test run belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='accounts.organization')),
                ('scenarios', models.ManyToManyField(help_text='Scenarios to run in this test', related_name='run_tests', to='simulate.scenarios')),
                ('simulator_agent', models.ForeignKey(help_text='Simulator agent for this test run', on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='simulate.simulatoragent')),
            ],
            options={
                'verbose_name': 'Run Test',
                'verbose_name_plural': 'Run Tests',
                'db_table': 'simulate_run_test',
                'ordering': ['-created_at'],
            },
        ),
    ]
