# Generated by Django 5.1.8 on 2025-07-30 08:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0008_remove_runtest_evals_simulateevalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Phone number called', max_length=20)),
                ('vapi_call_id', models.CharField(blank=True, help_text='Vapi call ID for tracking', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the call', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the call started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the call completed', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration of the call in seconds', null=True)),
                ('recording_url', models.URLField(blank=True, help_text='URL to the call recording', max_length=500, null=True)),
                ('cost_cents', models.IntegerField(blank=True, help_text='Cost of the call in cents', null=True)),
                ('call_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the call')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the call failed', null=True)),
                ('scenario', models.ForeignKey(help_text='The scenario this call belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='call_executions', to='simulate.scenarios')),
            ],
            options={
                'verbose_name': 'Call Execution',
                'verbose_name_plural': 'Call Executions',
                'db_table': 'simulate_call_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('unknown', 'Unknown')], default='unknown', help_text='Role of the speaker (user or assistant)', max_length=20)),
                ('content', models.TextField(help_text='Transcript content')),
                ('start_time_ms', models.IntegerField(default=0, help_text='Start time of this transcript segment in milliseconds')),
                ('end_time_ms', models.IntegerField(default=0, help_text='End time of this transcript segment in milliseconds')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score for this transcript segment')),
                ('call_execution', models.ForeignKey(help_text='The call execution this transcript belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='simulate.callexecution')),
            ],
            options={
                'verbose_name': 'Call Transcript',
                'verbose_name_plural': 'Call Transcripts',
                'db_table': 'simulate_call_transcript',
                'ordering': ['start_time_ms'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the test execution', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the test execution started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the test execution completed', null=True)),
                ('total_scenarios', models.IntegerField(default=0, help_text='Total number of scenarios in this execution')),
                ('total_calls', models.IntegerField(default=0, help_text='Total number of calls to be made')),
                ('completed_calls', models.IntegerField(default=0, help_text='Number of successfully completed calls')),
                ('failed_calls', models.IntegerField(default=0, help_text='Number of failed calls')),
                ('execution_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the execution')),
                ('run_test', models.ForeignKey(help_text='The run test being executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='simulate.runtest')),
            ],
            options={
                'verbose_name': 'Test Execution',
                'verbose_name_plural': 'Test Executions',
                'db_table': 'simulate_test_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='callexecution',
            name='test_execution',
            field=models.ForeignKey(help_text='The test execution this call belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='simulate.testexecution'),
        ),
    ]
