# Generated by Django 5.1.8 on 2025-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0009_callexecution_calltranscript_testexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='analysis_data',
            field=models.JSONField(blank=True, help_text='Call analysis data from Vapi', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='Vapi assistant ID used for the call', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='call_summary',
            field=models.TextField(blank=True, help_text='Call summary from Vapi', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='call_type',
            field=models.CharField(blank=True, help_text='Type of call (e.g., outboundPhoneCall)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Customer phone number (E.164 format)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the call ended (from Vapi)', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='ended_reason',
            field=models.CharField(blank=True, help_text='Reason why the call ended', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='evaluation_data',
            field=models.JSONField(blank=True, help_text='Call evaluation data from Vapi', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='llm_cost_cents',
            field=models.IntegerField(blank=True, help_text='LLM cost in cents', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='message_count',
            field=models.IntegerField(blank=True, help_text='Number of messages in the call', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='overall_score',
            field=models.FloatField(blank=True, help_text='Overall call performance score', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='recording_available',
            field=models.BooleanField(default=False, help_text='Whether recording is available'),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Average response time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='stereo_recording_url',
            field=models.URLField(blank=True, help_text='Stereo recording URL from Vapi', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='stt_cost_cents',
            field=models.IntegerField(blank=True, help_text='STT cost in cents', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='transcript_available',
            field=models.BooleanField(default=False, help_text='Whether transcript is available'),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='tts_cost_cents',
            field=models.IntegerField(blank=True, help_text='TTS cost in cents', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='vapi_call_data',
            field=models.JSONField(blank=True, help_text='Complete Vapi call data from API', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='vapi_cost_cents',
            field=models.IntegerField(blank=True, help_text='Vapi platform cost in cents', null=True),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='end_time_ms',
            field=models.BigIntegerField(default=0, help_text='End time of this transcript segment in milliseconds'),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='speaker_role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', help_text='Role of the speaker (user or assistant)', max_length=20),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='start_time_ms',
            field=models.BigIntegerField(default=0, help_text='Start time of this transcript segment in milliseconds'),
        ),
    ]
