# Generated by Django 5.1.8 on 2025-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0010_callexecution_analysis_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='row_id',
            field=models.UUIDField(blank=True, help_text='Row ID from the dataset if this call is from a dataset scenario', null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='scenario_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of scenario IDs that were executed in this run'),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_type',
            field=models.CharField(choices=[('graph', 'Graph'), ('script', 'Script'), ('dataset', 'Dataset')], default='dataset', help_text='Type of scenario (graph, script, or dataset)', max_length=20),
        ),
    ]
