# Generated by Django 5.1.8 on 2025-07-31 11:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
        ('simulate', '0012_callexecution_eval_outputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Version number of the agent')),
                ('version_name', models.CharField(blank=True, help_text="Human-readable version name (e.g., 'v1.2.3')", max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('deprecated', 'Deprecated')], default='draft', help_text='Current status of this version', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=1, help_text='Performance score (0.0 to 10.0)', max_digits=3, null=True)),
                ('test_count', models.PositiveIntegerField(default=0, help_text='Number of tests run for this version')),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Test pass rate percentage', max_digits=5, null=True)),
                ('description', models.TextField(help_text='Description of changes in this version')),
                ('release_notes', models.TextField(blank=True, help_text='Detailed release notes for this version', null=True)),
                ('configuration_snapshot', models.JSONField(default=dict, help_text='Snapshot of agent configuration at this version')),
                ('agent_definition', models.ForeignKey(help_text='Parent agent definition', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='simulate.agentdefinition')),
                ('organization', models.ForeignKey(help_text='Organization this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_versions', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Agent Version',
                'verbose_name_plural': 'Agent Versions',
                'db_table': 'simulate_agent_version',
                'ordering': ['-version_number'],
                'unique_together': {('agent_definition', 'version_number')},
            },
        ),
    ]
