# Generated by Django 5.1.8 on 2025-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0013_agentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='provider',
            field=models.CharField(blank=True, help_text='Provider of the AI agent', max_length=255, null=True),
        ),
    ]
