# Generated by Django 5.1.8 on 2025-07-31 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0014_agentdefinition_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatoragent',
            name='conversation_speed',
            field=models.FloatField(default=1.0, help_text='Speed of conversation (0.1-3.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='simulatoragent',
            name='finished_speaking_sensitivity',
            field=models.FloatField(default=0.5, help_text='Sensitivity for detecting when speaker has finished (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)]),
        ),
        migrations.AlterField(
            model_name='simulatoragent',
            name='interrupt_sensitivity',
            field=models.FloatField(default=0.5, help_text='Sensitivity for interruption detection (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)]),
        ),
        migrations.AlterField(
            model_name='simulatoragent',
            name='max_call_duration_in_minutes',
            field=models.IntegerField(default=30, help_text='Maximum call duration in minutes (1-180)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
