# Generated by Django 5.1.8 on 2025-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0015_alter_simulatoragent_conversation_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdefinition',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='External identifier for the assistant', max_length=255, null=True),
        ),
    ]
