# Generated by Django 5.1.8 on 2025-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0016_alter_agentdefinition_assistant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulateevalconfig',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Completed', max_length=50),
        ),
    ]
