# Generated by Django 5.1.8 on 2025-08-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0017_alter_simulateevalconfig_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callexecution',
            name='ended_reason',
            field=models.CharField(blank=True, help_text='Reason why the call ended', max_length=10000, null=True),
        ),
    ]
