# Generated by Django 5.1.8 on 2025-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0018_alter_callexecution_ended_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='picked_up_by_executor',
            field=models.BooleanField(default=False, help_text='Whether the test execution was picked up by the executor'),
        ),
    ]
