# Generated by Django 5.1.8 on 2025-08-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0019_testexecution_picked_up_by_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='agent_definition',
            field=models.ForeignKey(blank=True, help_text='Agent definition used for this test execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions_agent', to='simulate.agentdefinition'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='simulator_agent',
            field=models.ForeignKey(blank=True, help_text='Simulator agent used for this test execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions_simulation', to='simulate.simulatoragent'),
        ),
    ]
