# Generated by Django 5.1.8 on 2025-08-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_organization_role_organizationmembership_and_more'),
        ('simulate', '0020_testexecution_agent_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_definitions', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='agentversion',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_versions', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='runtest',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='scenarios',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='simulatoragent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulator_agents', to='accounts.workspace'),
        ),
    ]
