# Generated by Django 5.1.8 on 2025-09-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0021_agentdefinition_workspace_agentversion_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCallExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number_id', models.CharField(help_text='The phone number ID to create the call execution for', max_length=255)),
                ('to_number', models.CharField(help_text='The phone number to create the call execution for', max_length=255)),
                ('system_prompt', models.TextField(help_text='The system prompt to create the call execution for')),
                ('metadata', models.JSONField(help_text='The metadata to create the call execution for')),
                ('voice_settings', models.JSONField(help_text='The voice settings to create the call execution for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='registered', help_text='The status of the call execution ', max_length=255)),
                ('call_execution', models.ForeignKey(help_text='The call execution this call count belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='create_call_executions', to='simulate.callexecution')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
