# Generated by Django 5.1.8 on 2025-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0022_createcallexecution'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['status', 'picked_up_by_executor'], name='idx_status_executor'),
        ),
    ]
