# Generated by Django 5.1.8 on 2025-09-10 10:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250908_0727'),
        ('simulate', '0022_createcallexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioGraph',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Graph name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('graph_config', models.JSONField(default=dict, help_text='Graph settings, styling, etc.')),
                ('organization', models.ForeignKey(help_text='Organization this graph belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scenario_graphs', to='accounts.organization')),
                ('scenario', models.ForeignKey(help_text='Scenario that owns this graph', on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='simulate.scenarios')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_graphs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'simulate_scenario_graph',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Case name', max_length=255)),
                ('persona', models.TextField(help_text='Customer persona description')),
                ('situation', models.TextField(help_text='Main situation description')),
                ('outcome', models.TextField(help_text='Expected outcome')),
                ('case_data', models.JSONField(help_text='Complete case with nodes, branches, etc.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the graph')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this case is active')),
                ('scenario', models.ForeignKey(help_text='Scenario this case belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='simulate.scenarios')),
                ('graph', models.ForeignKey(help_text='Graph this case belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='simulate.scenariograph')),
            ],
            options={
                'db_table': 'simulate_scenario_case',
                'ordering': ['graph', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scenariograph',
            index=models.Index(fields=['scenario', 'is_active'], name='simulate_sc_scenari_bc130d_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariograph',
            index=models.Index(fields=['organization', 'is_active'], name='simulate_sc_organiz_d1cb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariocase',
            index=models.Index(fields=['scenario', 'is_active'], name='simulate_sc_scenari_7637d9_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariocase',
            index=models.Index(fields=['graph', 'is_active'], name='simulate_sc_graph_i_783f07_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariocase',
            index=models.Index(fields=['graph', 'order'], name='simulate_sc_graph_i_9867f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenariocase',
            unique_together={('graph', 'name')},
        ),
    ]
