# Generated by Django 5.1.8 on 2025-09-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0030_merge_20250911_0838'),
        ('simulate', '0023_testexecution_idx_status_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='agent_type',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', max_length=255),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.knowledgebasefile'),
        ),
    ]
