# Generated by Django 5.1.8 on 2025-09-11 06:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0023_scenariograph_scenariocase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('node_type', models.CharField(help_text='Type of node (start, message, condition, end)', max_length=50)),
                ('label', models.CharField(help_text='Display label for the node', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Node configuration and metadata')),
                ('position_x', models.FloatField(default=0, help_text='X position in graph visualization')),
                ('position_y', models.FloatField(default=0, help_text='Y position in graph visualization')),
                ('is_terminal', models.BooleanField(default=False, help_text='Whether this node ends a conversation path')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='simulate.scenariograph')),
            ],
            options={
                'db_table': 'simulate_scenario_node',
                'ordering': ['graph', 'position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioEdge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='Edge label for visualization', max_length=255)),
                ('condition', models.JSONField(default=dict, help_text='Edge conditions and case metadata')),
                ('case_id', models.UUIDField(blank=True, help_text='Reference to original case', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of edge in the path')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='simulate.scenariograph')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='simulate.scenarionode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='simulate.scenarionode')),
            ],
            options={
                'db_table': 'simulate_scenario_edge',
                'ordering': ['graph', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='scenarionode',
            index=models.Index(fields=['graph', 'node_type'], name='simulate_sc_graph_i_454941_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarionode',
            index=models.Index(fields=['graph', 'is_terminal'], name='simulate_sc_graph_i_b53c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioedge',
            index=models.Index(fields=['graph', 'case_id'], name='simulate_sc_graph_i_c6e6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioedge',
            index=models.Index(fields=['from_node', 'to_node'], name='simulate_sc_from_no_3d49bc_idx'),
        ),
    ]
