# Generated by Django 5.1.8 on 2025-09-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0024_agentdefinition_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='agent_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_executions', to='simulate.agentversion'),
        ),
    ]
