# Generated by Django 5.1.8 on 2025-09-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0024_scenarionode_scenarioedge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioedge',
            name='from_node',
        ),
        migrations.RemoveField(
            model_name='scenarioedge',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='scenarioedge',
            name='to_node',
        ),
        migrations.RemoveField(
            model_name='scenarionode',
            name='graph',
        ),
        migrations.DeleteModel(
            name='ScenarioCase',
        ),
        migrations.DeleteModel(
            name='ScenarioEdge',
        ),
        migrations.DeleteModel(
            name='ScenarioNode',
        ),
    ]
