# Generated by Django 5.1.8 on 2025-09-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0025_remove_scenarioedge_from_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata associated with this scenario'),
        ),
        migrations.AddField(
            model_name='scenarios',
            name='simulator_agent',
            field=models.ForeignKey(blank=True, help_text='Simulator agent associated with this scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='simulate.simulatoragent'),
        ),
        migrations.AddField(
            model_name='scenarios',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error')], default='Running', help_text='Status of the scenario', max_length=50),
        ),
    ]
