# Generated by Django 5.1.8 on 2025-09-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0026_scenarios_metadata_scenarios_simulator_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='agent_definition',
            field=models.ForeignKey(blank=True, help_text='Agent definition associated with this scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='simulate.agentdefinition'),
        ),
    ]
