# Generated by Django 5.1.8 on 2025-09-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0025_callexecution_agent_version'),
        ('simulate', '0027_scenarios_agent_definition'),
    ]

    operations = [
    ]
