# Generated by Django 5.1.8 on 2025-09-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0028_merge_20250917_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtest',
            name='simulator_agent',
            field=models.ForeignKey(blank=True, help_text='Simulator agent for this test run (derived from scenarios)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='simulate.simulatoragent'),
        ),
    ]
