# Generated by Django 5.1.8 on 2025-09-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250908_0727'),
        ('simulate', '0029_alter_runtest_simulator_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createcallexecution',
            options={'ordering': ['-created_at'], 'verbose_name': 'Create Call Execution', 'verbose_name_plural': 'Create Call Executions'},
        ),
        migrations.AddIndex(
            model_name='callexecution',
            index=models.Index(fields=['status'], name='idx_callexecution_status'),
        ),
        migrations.AddIndex(
            model_name='createcallexecution',
            index=models.Index(fields=['status', 'deleted', 'created_at'], name='idx_createcall_status'),
        ),
        migrations.AddIndex(
            model_name='runtest',
            index=models.Index(fields=['organization_id'], name='idx_runtest_organization_id'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['run_test_id'], name='idx_testexecution_run_test_id'),
        ),
        migrations.AlterModelTable(
            name='createcallexecution',
            table='simulate_createcallexecution',
        ),
    ]
