# Generated by Django 5.1.8 on 2025-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0030_alter_createcallexecution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariograph',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('evaluating', 'Evaluating')], default='pending', help_text='Current status of the test execution', max_length=20),
        ),
    ]
