# Generated by Django 5.1.8 on 2025-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0031_remove_scenariograph_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='ai_interruption_count',
            field=models.IntegerField(blank=True, help_text='Number of times AI interrupted the user', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='ai_interruption_rate',
            field=models.FloatField(blank=True, help_text='Rate of AI interruptions (interruptions per minute)', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='avg_agent_latency_ms',
            field=models.IntegerField(blank=True, help_text="Average agent latency in milliseconds (time taken by agent to respond after user's pause)", null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='avg_stop_time_after_interruption_ms',
            field=models.IntegerField(blank=True, help_text='Average stop time after user interruption in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='bot_wpm',
            field=models.FloatField(blank=True, help_text="Bot's words per minute", null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='talk_ratio',
            field=models.FloatField(blank=True, help_text='Ratio of bot speaking time to user speaking time', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='user_interruption_count',
            field=models.IntegerField(blank=True, help_text='Number of times user interrupted the AI', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='user_interruption_rate',
            field=models.FloatField(blank=True, help_text='Rate of user interruptions (interruptions per minute)', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='user_wpm',
            field=models.FloatField(blank=True, help_text="User's words per minute", null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the call', max_length=20),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='speaker_role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='tool', help_text='Role of the speaker (user or assistant)', max_length=20),
        ),
    ]
