# Generated by Django 5.1.8 on 2025-09-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0031_remove_scenariograph_workspace_and_more'),
        ('tracer', '0029_alter_project_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for the agent', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='observability_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='observability_provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_definition', to='tracer.observabilityprovider'),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the call', max_length=20),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='speaker_role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='tool', help_text='Role of the speaker (user or assistant)', max_length=20),
        ),
    ]
