# Generated by Django 5.1.8 on 2025-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0031_remove_scenariograph_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentversion',
            name='commit_message',
            field=models.TextField(blank=True, help_text='Commit message for the agent version', null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the call', max_length=20),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='speaker_role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='tool', help_text='Role of the speaker (user or assistant)', max_length=20),
        ),
    ]
