# Generated by Django 5.1.8 on 2025-10-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0032_agentversion_commit_message_and_more'),
        ('simulate', '0032_simulateevalconfig_eval_group_and_more'),
    ]

    operations = [
    ]
