# Generated by Django 5.1.8 on 2025-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0032_callexecution_ai_interruption_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='conversation_metrics_data',
            field=models.JSONField(blank=True, help_text='Detailed conversation metrics data', null=True),
        ),
    ]
