# Generated by Django 5.1.8 on 2025-10-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0033_callexecution_conversation_metrics_data'),
        ('simulate', '0033_merge_20251001_0823'),
    ]

    operations = [
    ]
