# Generated by Django 5.1.8 on 2025-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0034_merge_20251001_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='monitor_call_data',
            field=models.JSONField(blank=True, help_text='Monitor call data from API', null=True),
        ),
    ]
