# Generated by Django 5.1.8 on 2025-10-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0032_agentdefinition_api_key_and_more'),
        ('simulate', '0035_callexecution_monitor_call_data'),
    ]

    operations = [
    ]
