# Generated by Django 5.1.8 on 2025-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0035_callexecution_monitor_call_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('cancelling', 'Cancelling'), ('evaluating', 'Evaluating')], default='pending', help_text='Current status of the test execution', max_length=20),
        ),
    ]
