# Generated by Django 5.1.8 on 2025-10-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0036_alter_testexecution_status'),
        ('simulate', '0036_merge_20251001_1957'),
    ]

    operations = [
    ]
