# Generated by Django 5.1.8 on 2025-10-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0037_merge_20251002_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdefinition',
            name='observability_enabled',
        ),
    ]
