# Generated by Django 5.1.8 on 2025-10-14 08:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0038_remove_agentdefinition_observability_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallExecutionSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_timestamp', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was created')),
                ('rerun_type', models.CharField(choices=[('eval_only', 'Evaluation Only'), ('call_and_eval', 'Call and Evaluation')], help_text='Type of rerun that triggered this snapshot', max_length=20)),
                ('vapi_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('stereo_recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cost_cents', models.IntegerField(blank=True, null=True)),
                ('stt_cost_cents', models.IntegerField(blank=True, null=True)),
                ('llm_cost_cents', models.IntegerField(blank=True, null=True)),
                ('tts_cost_cents', models.IntegerField(blank=True, null=True)),
                ('vapi_cost_cents', models.IntegerField(blank=True, null=True)),
                ('call_summary', models.TextField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=10000, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('assistant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('message_count', models.IntegerField(blank=True, null=True)),
                ('transcript_available', models.BooleanField(default=False)),
                ('recording_available', models.BooleanField(default=False)),
                ('analysis_data', models.JSONField(blank=True, null=True)),
                ('evaluation_data', models.JSONField(blank=True, null=True)),
                ('eval_outputs', models.JSONField(blank=True, null=True)),
                ('vapi_call_data', models.JSONField(blank=True, null=True)),
                ('monitor_call_data', models.JSONField(blank=True, null=True)),
                ('avg_agent_latency_ms', models.IntegerField(blank=True, null=True)),
                ('user_interruption_count', models.IntegerField(blank=True, null=True)),
                ('user_interruption_rate', models.FloatField(blank=True, null=True)),
                ('user_wpm', models.FloatField(blank=True, null=True)),
                ('bot_wpm', models.FloatField(blank=True, null=True)),
                ('talk_ratio', models.FloatField(blank=True, null=True)),
                ('ai_interruption_count', models.IntegerField(blank=True, null=True)),
                ('ai_interruption_rate', models.FloatField(blank=True, null=True)),
                ('avg_stop_time_after_interruption_ms', models.IntegerField(blank=True, null=True)),
                ('conversation_metrics_data', models.JSONField(blank=True, null=True)),
                ('transcripts', models.JSONField(blank=True, default=list, help_text='Snapshot of transcripts at the time of rerun')),
                ('call_execution', models.ForeignKey(help_text='The call execution this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='simulate.callexecution')),
            ],
            options={
                'verbose_name': 'Call Execution Snapshot',
                'verbose_name_plural': 'Call Execution Snapshots',
                'db_table': 'simulate_call_execution_snapshot',
                'ordering': ['-snapshot_timestamp'],
                'indexes': [models.Index(fields=['call_execution', '-snapshot_timestamp'], name='idx_snapshot_call_time'), models.Index(fields=['rerun_type'], name='idx_snapshot_rerun_type')],
            },
        ),
    ]
