# Generated by Django 5.1.8 on 2025-10-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0038_remove_agentdefinition_observability_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtest',
            name='agent_version',
            field=models.ForeignKey(blank=True, help_text='Agent version for this test run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='simulate.agentversion'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='agent_version',
            field=models.ForeignKey(blank=True, help_text='Agent version used for this test execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions_agent_version', to='simulate.agentversion'),
        ),
    ]
