# Generated by Django 5.1.8 on 2025-10-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0039_callexecutionsnapshot'),
        ('simulate', '0039_runtest_agent_version'),
    ]

    operations = [
    ]
