# Generated by Django 5.1.8 on 2025-10-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0040_merge_20251015_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='tool_outputs',
            field=models.JSONField(blank=True, help_text='Tool evaluation output - separate from standard evaluations', null=True),
        ),
        migrations.AddField(
            model_name='runtest',
            name='enable_tool_evaluation',
            field=models.BooleanField(default=False, help_text='Enable automatic tool evaluation for this test run'),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='speaker_role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool_calls', 'Tool Calls'), ('tool_call_result', 'Tool Call Result'), ('unknown', 'Unknown')], default='unknown', help_text='Role of the speaker (user or assistant)', max_length=20),
        ),
    ]
