# Generated by Django 5.1.8 on 2025-10-29 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0040_merge_20251015_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationPhoneNumber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Phone number in E.164 format (e.g., +15551234567)', max_length=20, unique=True)),
                ('vapi_phone_number_id', models.CharField(max_length=255, unique=True)),
                ('call_direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('in_use', 'In Use'), ('disabled', 'Disabled')], default='idle', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('current_call_execution', models.ForeignKey(blank=True, help_text='The call execution currently using this phone number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_phone_number', to='simulate.callexecution')),
            ],
            options={
                'db_table': 'simulate_phone_numbers',
                'indexes': [models.Index(fields=['status', 'call_direction'], name='simulate_ph_status_afd734_idx'), models.Index(fields=['phone_number'], name='simulate_ph_phone_n_5f0646_idx'), models.Index(fields=['call_direction', 'status', 'last_used_at'], name='simulate_ph_call_di_76dd64_idx')],
            },
        ),
    ]
