# Generated by Django 5.1.8 on 2025-10-30 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250908_0727'),
        ('simulate', '0040_merge_20251015_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callexecution',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Call Execution', 'verbose_name_plural': 'Call Executions'},
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_type', models.CharField(choices=[('system', 'System'), ('workspace', 'Workspace')], default='workspace', help_text='Type of persona (system or workspace-level)', max_length=20)),
                ('persona_id', models.IntegerField(default=0, help_text='Unique identifier for system personas (e.g., 1, 2, 3)')),
                ('name', models.CharField(help_text='Name of the persona', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the persona', null=True)),
                ('gender', models.JSONField(blank=True, default=list, help_text="List of genders for the persona (e.g., ['male'], ['female'])")),
                ('age_group', models.JSONField(blank=True, default=list, help_text="List of age groups for the persona (e.g., ['18-25'], ['25-32'])")),
                ('occupation', models.JSONField(blank=True, default=list, help_text="List of occupations/professions for the persona (e.g., ['Engineer'], ['Teacher'])")),
                ('location', models.JSONField(blank=True, default=list, help_text="List of locations for the persona (e.g., ['United States'], ['Canada'])")),
                ('personality', models.JSONField(blank=True, default=list, help_text="List of personality types for the persona (e.g., ['Friendly and cooperative'])")),
                ('communication_style', models.JSONField(blank=True, default=list, help_text="List of communication styles for the persona (e.g., ['Direct and concise'])")),
                ('multilingual', models.BooleanField(default=False, help_text='Whether the persona supports multiple languages')),
                ('languages', models.JSONField(blank=True, default=list, help_text="List of languages the persona speaks (e.g., ['English', 'Hindi'])")),
                ('accent', models.JSONField(blank=True, default=list, help_text="List of accents for the persona (e.g., ['American'], ['Australian'])")),
                ('conversation_speed', models.JSONField(blank=True, default=list, help_text="List of conversation speeds (e.g., ['1.0'], ['1.25'])")),
                ('background_sound', models.BooleanField(blank=True, default=False, help_text='Whether background sound is enabled (null=not specified, True/False for enabled/disabled)', null=True)),
                ('finished_speaking_sensitivity', models.JSONField(blank=True, default=list, help_text="List of sensitivities for detecting when persona finished speaking (e.g., ['5'], ['6'])")),
                ('interrupt_sensitivity', models.JSONField(blank=True, default=list, help_text="List of sensitivities for allowing interruptions (e.g., ['5'], ['6'])")),
                ('keywords', models.JSONField(blank=True, default=list, help_text="List of keywords/tags describing the persona (e.g., ['Knowledgeable', 'Patient', 'Helpful'])")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the persona (speech clarity, base emotion, etc.)')),
                ('additional_instruction', models.TextField(blank=True, help_text='Additional instructions for how this persona should behave', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is a default/recommended persona')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this persona belongs to (null for system personas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace this persona belongs to (null for system personas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'simulate_personas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['persona_type'], name='simulate_pe_persona_69bec3_idx'), models.Index(fields=['organization', 'workspace'], name='simulate_pe_organiz_d19aa9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('persona_type', 'system'), ('workspace__isnull', True)), ('persona_type', 'workspace'), _connector='OR'), name='system_persona_no_org_workspace'), models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('persona_type', 'workspace')), ('persona_type', 'system'), _connector='OR'), name='workspace_persona_has_org')],
            },
        ),
    ]
