# Generated by Django 5.1.8 on 2025-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0041_alter_callexecution_options_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='accent',
            field=models.JSONField(blank=True, default=list, help_text="List of accents for the persona (e.g., ['American'], ['Australian'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='age_group',
            field=models.JSONField(blank=True, default=list, help_text="List of age groups for the persona (e.g., ['18-25'], ['25-32'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='communication_style',
            field=models.JSONField(blank=True, default=list, help_text="List of communication styles for the persona (e.g., ['Direct and concise'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='conversation_speed',
            field=models.JSONField(blank=True, default=list, help_text="List of conversation speeds (e.g., ['1.0'], ['1.25'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='finished_speaking_sensitivity',
            field=models.JSONField(blank=True, default=list, help_text="List of sensitivities for detecting when persona finished speaking (e.g., ['5'], ['6'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.JSONField(blank=True, default=list, help_text="List of genders for the persona (e.g., ['male'], ['female'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='interrupt_sensitivity',
            field=models.JSONField(blank=True, default=list, help_text="List of sensitivities for allowing interruptions (e.g., ['5'], ['6'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is a default/recommended persona', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text="List of keywords/tags describing the persona (e.g., ['Knowledgeable', 'Patient', 'Helpful'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="List of languages the persona speaks (e.g., ['English', 'Hindi'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='location',
            field=models.JSONField(blank=True, default=list, help_text="List of locations for the persona (e.g., ['United States'], ['Canada'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the persona (speech clarity, base emotion, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='multilingual',
            field=models.BooleanField(default=False, help_text='Whether the persona supports multiple languages', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='occupation',
            field=models.JSONField(blank=True, default=list, help_text="List of occupations/professions for the persona (e.g., ['Engineer'], ['Teacher'])", null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='personality',
            field=models.JSONField(blank=True, default=list, help_text="List of personality types for the persona (e.g., ['Friendly and cooperative'])", null=True),
        ),
    ]
