# Generated by Django 5.1.8 on 2025-10-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0041_callexecution_tool_outputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecutionsnapshot',
            name='tool_outputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
