# Generated by Django 5.1.8 on 2025-10-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0041_simulationphonenumber'),
        ('simulate', '0042_alter_persona_accent_alter_persona_age_group_and_more'),
    ]

    operations = [
    ]
