# Generated by Django 5.1.8 on 2025-11-03 10:12

from django.db import migrations, models

def backfill_webhook_secret(apps, schema_editor):
    AgentVersion = apps.get_model('simulate', 'AgentVersion')
    for agent_version in AgentVersion.objects.all():
        agent_version.configuration_snapshot['webhook_secret'] = ""
        agent_version.save()

class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0043_merge_20251031_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='webhook_secret',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Webhook secret for the provider',
                max_length=255,
                null=True
            ),
        ),
        migrations.RunPython(backfill_webhook_secret),
    ]
