# Generated by Django 5.1.8 on 2025-11-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0043_merge_20251031_0632'),
        ('simulate', '0043_merge_20251031_1023'),
    ]

    operations = [
    ]
