# Generated by Django 5.1.8 on 2025-11-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0044_agentdefinition_webhook_secret'),
        ('simulate', '0044_merge_20251103_1151'),
    ]

    operations = [
    ]
