# Generated by Django 5.1.8 on 2025-11-05 10:56

from django.db import migrations


def remove_webhook_secret_from_agent_version(apps,schema_editor):
    AgentVersion = apps.get_model('simulate','AgentVersion')
    for version in AgentVersion.objects.all():
        snapshot = version.configuration_snapshot
        if snapshot.get('webhook_secret'):
            del version.configuration_snapshot['webhook_secret']
            version.save()



class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0045_merge_20251104_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdefinition',
            name='webhook_secret',
        ),
        migrations.RunPython(remove_webhook_secret_from_agent_version)
    ]
