# Generated by Django 5.1.8 on 2025-11-11 08:08

import django.contrib.postgres.fields
from django.db import migrations, models
from simulate.models.agent_definition import AgentDefinitionAuthenticationChoices

def populate_languages_and_auth_method_in_configuration_snapshot(apps, schema_editor):
    AgentVersion = apps.get_model('simulate','AgentVersion')
    AgentDefinition = apps.get_model('simulate','AgentDefinition')
    for agent_definition in AgentDefinition.objects.all():
        if agent_definition.language:
            agent_definition.languages = [agent_definition.language]
            agent_definition.save()

    for version in AgentVersion.objects.all():
        snapshot = version.configuration_snapshot
        language = snapshot.get("language")
        if language:
            snapshot["language"] = [language]
        else:
            snapshot["languages"] = ["en"]
        snapshot['authentication_method'] = AgentDefinitionAuthenticationChoices.API_KEY
        version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0046_remove_agentdefinition_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='authentication_method',
            field=models.CharField(choices=[('api_key', 'Api Key')], default='api_key'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ar', 'Arabic'), ('bg', 'Bulgarian'), ('zh', 'Chinese Simplified'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ms', 'Malay'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('es', 'Spanish'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese')], help_text='Language of the agent', max_length=2), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('bg', 'Bulgarian'), ('zh', 'Chinese Simplified'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ms', 'Malay'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('es', 'Spanish'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese')], help_text='Language of the agent', max_length=2, null=True),
        ),
        migrations.RunPython(populate_languages_and_auth_method_in_configuration_snapshot)

    ]