# Generated by Django 5.1.8 on 2025-11-13 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0046_remove_agentdefinition_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='customer_cost_breakdown',
            field=models.JSONField(blank=True, help_text='Detailed cost breakdown from customer call data', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_cost_cents',
            field=models.IntegerField(blank=True, help_text='Total customer-reported cost in cents', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_latency_metrics',
            field=models.JSONField(blank=True, help_text='Latency metrics from customer call data', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_log_url',
            field=models.URLField(blank=True, help_text='Customer call log URL from Vapi', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_logs_summary',
            field=models.JSONField(blank=True, help_text='Summary of customer call logs (e.g., counts by level)', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_vapi_call_id',
            field=models.CharField(blank=True, help_text='Customer Vapi call ID if available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='logUrl',
            field=models.URLField(blank=True, help_text='Log URL from Vapi', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='logs_ingested_at',
            field=models.DateTimeField(blank=True, help_text='When call logs were last ingested from Vapi', null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='logs_summary',
            field=models.JSONField(blank=True, help_text='Lightweight summary of ingested call logs (e.g., counts by level)', null=True),
        ),
        migrations.CreateModel(
            name='CallLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('customer', 'Customer')], default='agent', help_text='Source of the log entry (agent or customer)', max_length=16)),
                ('provider', models.CharField(choices=[('vapi', 'Vapi'), ('retell', 'Retell')], default='vapi', help_text='Provider of the log entry (vapi or retell)', max_length=16)),
                ('logged_at', models.DateTimeField(db_index=True, help_text='Timestamp of the log entry (UTC)')),
                ('level', models.IntegerField(help_text='Numeric severity level of the log entry (e.g., 30=INFO)')),
                ('severity_text', models.CharField(blank=True, help_text='Human-readable severity text (e.g., INFO, WARN)', max_length=32)),
                ('category', models.CharField(blank=True, help_text='Category of the log entry', max_length=128)),
                ('body', models.CharField(blank=True, help_text='Short message body for the log entry', max_length=1024)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Structured attributes parsed from the log entry')),
                ('payload', models.JSONField(help_text='Full log entry payload as returned by Vapi for auditing')),
                ('call_execution', models.ForeignKey(help_text='Call execution the log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='simulate.callexecution')),
            ],
            options={
                'verbose_name': 'Call Log Entry',
                'verbose_name_plural': 'Call Log Entries',
                'db_table': 'simulate_call_log_entry',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['call_execution', 'logged_at'], name='idx_calllog_exec_time'), models.Index(fields=['call_execution', 'source', 'logged_at'], name='idx_calllog_exec_src'), models.Index(fields=['category'], name='idx_calllogentry_category'), models.Index(fields=['body'], name='idx_calllogentry_body')],
            },
        ),
    ]
