# Generated by Django 5.1.8 on 2025-11-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0047_agentdefinition_authentication_method_and_more'),
        ('simulate', '0047_callexecution_customer_cost_breakdown_and_more'),
    ]

    operations = [
    ]
