# Generated by Django 5.1.8 on 2025-12-01 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0050_testexecution_eval_explanation_summary_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOptimiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the agent optimiser', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this optimiser does', null=True)),
                ('configuration', models.JSONField(blank=True, help_text='Configuration settings for this optimiser', null=True)),
            ],
            options={
                'db_table': 'agent_optimiser',
            },
        ),
        migrations.CreateModel(
            name='AgentOptimiserRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_optimiser_run',
            },
        ),
        migrations.AddField(
            model_name='testexecution',
            name='agent_optimiser',
            field=models.ForeignKey(blank=True, help_text='Agent optimiser used for this test execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='simulate.agentoptimiser'),
        ),
        migrations.AddField(
            model_name='agentoptimiserrun',
            name='agent_optimiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulate.agentoptimiser'),
        ),
        migrations.AddIndex(
            model_name='agentoptimiserrun',
            index=models.Index(fields=['status'], name='idx_optimiser_run_status'),
        ),
    ]
