# Generated by Django 5.1.8 on 2025-12-08 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0051_agentoptimiser_agentoptimiserrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPromptOptimiserRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('optimiser_type', models.CharField(choices=[('random_search', 'Random Search'), ('gepa', 'GEPA'), ('protegi', 'Protegi'), ('bayesian', 'Bayesian'), ('metaprompt', 'Metaprompt'), ('promptwizard', 'PromptWizard')], max_length=50, null=True)),
                ('model', models.CharField(help_text='LLM model used for the optimiser run', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('configuration', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'agent_prompt_optimiser_run',
            },
        ),
        migrations.CreateModel(
            name='AgentPromptOptimiserRunStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_prompt_optimiser_run_step',
            },
        ),
        migrations.AddField(
            model_name='agentpromptoptimiserrun',
            name='agent_optimiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_optimiser_runs', to='simulate.agentoptimiser'),
        ),
        migrations.AddField(
            model_name='agentpromptoptimiserrun',
            name='agent_optimiser_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_optimiser_runs', to='simulate.agentoptimiserrun'),
        ),
        migrations.AddField(
            model_name='agentpromptoptimiserrun',
            name='test_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_optimiser_runs', to='simulate.testexecution'),
        ),
        migrations.AddField(
            model_name='agentpromptoptimiserrunstep',
            name='agent_prompt_optimiser_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='simulate.agentpromptoptimiserrun'),
        ),
    ]
