# Generated by Django 5.1.8 on 2025-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0051_agentoptimiser_agentoptimiserrun_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callexecution',
            index=models.Index(fields=['test_execution', 'status'], name='idx_callexec_testexec_status'),
        ),
    ]
