# Generated by Django 5.1.8 on 2025-12-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0052_callexecution_idx_callexec_testexec_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='error_reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
