# Generated by Django 5.1.8 on 2025-12-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0052_agentpromptoptimiserrun_agentpromptoptimiserrunstep_and_more'),
        ('simulate', '0052_callexecution_idx_callexec_testexec_status'),
    ]

    operations = [
    ]
