# Generated by Django 5.1.8 on 2025-12-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0053_merge_20251209_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpromptoptimiserrunstep',
            name='step_number',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='agentpromptoptimiserrunstep',
            unique_together={('agent_prompt_optimiser_run', 'step_number')},
        ),
    ]
