# Generated by Django 5.1.8 on 2025-12-18 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('simulate', '0054_alter_scenarios_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='model',
            field=models.CharField(blank=True, help_text='Model of the agent', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], help_text='Role of the message sender (user or assistant)', max_length=20)),
                ('messages', models.JSONField(blank=True, default=list, help_text='List of extracted message content strings')),
                ('content', models.JSONField(blank=True, default=list, help_text='Full message content as list of dictionaries (ChatMessage objects)')),
                ('session_id', models.CharField(help_text='VAPI chat session ID', max_length=255)),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='List of tool calls used for the message')),
                ('call_execution', models.ForeignKey(help_text='The call execution this chat message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='simulate.callexecution')),
                ('organization', models.ForeignKey(help_text='Organization this chat message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.organization')),
                ('workspace', models.ForeignKey(help_text='Workspace this chat message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'simulate_chat_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['call_execution', 'created_at'], name='idx_chatmsg_exec_time'), models.Index(fields=['session_id', 'created_at'], name='idx_chatmsg_session_time'), models.Index(fields=['role'], name='idx_chatmsg_role')],
            },
        ),
    ]
