# Generated by Django 5.1.8 on 2025-12-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0054_agentpromptoptimiserrunstep_step_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpromptoptimiserrun',
            name='name',
            field=models.CharField(default='Agent Prompt Optimiser', max_length=255),
            preserve_default=False,
        ),
    ]
