# Generated by Django 5.1.8 on 2025-12-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0054_alter_scenarios_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('analyzing', 'Analyzing'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the call', max_length=20),
        ),
    ]
