# Generated by Django 5.1.8 on 2025-12-11 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0055_agentpromptoptimiserrun_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTrial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trial_number', models.IntegerField()),
                ('is_baseline', models.BooleanField(default=False)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('average_score', models.FloatField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('agent_prompt_optimiser_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='simulate.agentpromptoptimiserrun')),
            ],
            options={
                'db_table': 'prompt_trial',
                'ordering': ['trial_number'],
                'unique_together': {('agent_prompt_optimiser_run', 'trial_number')},
            },
        ),
        migrations.CreateModel(
            name='TrialItemResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('call_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_item_results', to='simulate.callexecution')),
                ('prompt_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_items', to='simulate.prompttrial')),
            ],
            options={
                'db_table': 'trial_item_result',
                'unique_together': {('prompt_trial', 'call_execution')},
            },
        ),
        migrations.CreateModel(
            name='ComponentEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('eval_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_evaluations', to='simulate.simulateevalconfig')),
                ('trial_item_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_evaluations', to='simulate.trialitemresult')),
            ],
            options={
                'db_table': 'component_evaluation',
            },
        ),
    ]
