# Generated by Django 5.1.8 on 2025-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0055_agentdefinition_model_chatmessagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='emoji_usage',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('rarely', 'Rarely'), ('frequently', 'Frequently'), ('sometimes', 'Sometimes')], help_text='Emoji usage for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='punctuation',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('minimal', 'Minimal'), ('excessive', 'Excessive'), ('inconsistent', 'Inconsistent')], help_text='Punctuation style for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='regional_mix',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Regional mix for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='simulation_type',
            field=models.CharField(blank=True, choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', help_text='Type of simulation for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='slang_usage',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Slang usage for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='typos_frequency',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Typos frequency for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='writing_style',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('casual', 'Casual'), ('business', 'Business'), ('academic', 'Academic'), ('sms', 'SMS')], help_text='Writing style for the persona', max_length=20, null=True),
        ),
    ]
