# Generated by Django 5.1.8 on 2025-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0056_prompttrial_trialitemresult_componentevaluation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentpromptoptimiserrun',
            index=models.Index(fields=['status'], name='idx_prompt_opt_run_status'),
        ),
        migrations.AddIndex(
            model_name='agentpromptoptimiserrun',
            index=models.Index(fields=['test_execution', 'status'], name='idx_prompt_opt_run_test_status'),
        ),
        migrations.AddIndex(
            model_name='componentevaluation',
            index=models.Index(fields=['trial_item_result', 'eval_config'], name='idx_comp_eval_trial_config'),
        ),
        migrations.AddIndex(
            model_name='componentevaluation',
            index=models.Index(fields=['eval_config'], name='idx_comp_eval_config'),
        ),
        migrations.AddIndex(
            model_name='trialitemresult',
            index=models.Index(fields=['prompt_trial'], name='idx_trial_item_prompt_trial'),
        ),
    ]
