# Generated by Django 5.1.8 on 2025-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0056_persona_emoji_usage_persona_punctuation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='model_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of the model', null=True),
        ),
    ]
