# Generated by Django 5.1.8 on 2025-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0057_agentdefinition_model_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdefinition',
            name='authentication_method',
            field=models.CharField(blank=True, choices=[('api_key', 'Api Key')], default='api_key', null=True),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Phone number associated with the AI agent', max_length=50, null=True),
        ),
    ]
