# Generated by Django 5.1.8 on 2025-12-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0054_alter_scenarios_status_and_more'),
        ('simulate', '0057_agentpromptoptimiserrun_idx_prompt_opt_run_status_and_more'),
    ]

    operations = [
    ]
