# Generated by Django 5.1.8 on 2025-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0058_alter_agentdefinition_authentication_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='simulation_call_type',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', help_text='Type of simulation call', max_length=20),
        ),
    ]
