# Generated by Django 5.1.8 on 2025-12-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0058_merge_20251218_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpromptoptimiserrun',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
