# Generated by Django 5.1.8 on 2025-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0059_callexecution_simulation_call_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='writing_style',
        ),
        migrations.AddField(
            model_name='persona',
            name='tone',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('casual', 'Casual'), ('neutral', 'Neutral')], help_text='Tone for the persona', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='verbosity',
            field=models.CharField(blank=True, choices=[('brief', 'Brief'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], help_text='Verbosity for the persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='emoji_usage',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('light', 'Light'), ('regular', 'Regular'), ('heavy', 'Heavy')], help_text='Emoji usage for the persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='punctuation',
            field=models.CharField(blank=True, choices=[('clean', 'Clean'), ('minimal', 'Minimal'), ('expressive', 'Expressive'), ('erratic', 'Erratic')], help_text='Punctuation style for the persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='regional_mix',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], help_text='Regional mix for the persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='slang_usage',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], help_text='Slang usage for the persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='typos_frequency',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('rare', 'Rare'), ('occasional', 'Occasional'), ('frequent', 'Frequent')], help_text='Typos frequency for the persona', max_length=20, null=True),
        ),
    ]
