# Generated by Django 5.1.8 on 2025-12-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0055_alter_callexecution_status'),
        ('simulate', '0059_agentpromptoptimiserrun_error_message'),
    ]

    operations = [
    ]
