# Generated by Django 5.1.8 on 2025-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0060_remove_persona_writing_style_persona_tone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='latency_ms',
            field=models.IntegerField(blank=True, help_text='Latency in milliseconds for this message (from SDK)', null=True),
        ),
        migrations.AddField(
            model_name='chatmessagemodel',
            name='tokens',
            field=models.IntegerField(blank=True, help_text='Token count for this message (calculated from content)', null=True),
        ),
    ]
