# Generated by Django 5.1.8 on 2025-12-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0060_merge_20251226_1007'),
        ('simulate', '0061_chatmessagemodel_latency_ms_chatmessagemodel_tokens'),
    ]

    operations = [
    ]
