# Generated by Django 5.1.8 on 2026-01-07 09:52

import simulate.semantics
from django.db import migrations, models


def backfill_updated_fields_call_execution(apps, schema_editor):
    """
    Backfill new provider-agnostic fields from deprecated VAPI-specific columns.

    - service_provider_call_id  <- vapi_call_id
    - customer_call_id          <- customer_vapi_call_id
    - provider_call_data        <- vapi_call_data (wrapped under provider key if dict)
    - snapshots mirror the same mapping
    """
    CallExecution = apps.get_model("simulate", "CallExecution")
    CallExecutionSnapshot = apps.get_model("simulate", "CallExecutionSnapshot")

    def _wrap_provider_payload(payload):
        # Only wrap dict payloads; leave others as-is to avoid validation issues.
        if isinstance(payload, dict):
            return {"vapi": payload}
        return None

    # Backfill CallExecution records
    for ce in CallExecution.objects.all():
        update_fields = []

        vapi_call_id = getattr(ce, "vapi_call_id", None)
        if not ce.service_provider_call_id and vapi_call_id:
            ce.service_provider_call_id = vapi_call_id
            update_fields.append("service_provider_call_id")

        customer_vapi_call_id = getattr(ce, "customer_vapi_call_id", None)
        if not getattr(ce, "customer_call_id", None) and customer_vapi_call_id:
            ce.customer_call_id = customer_vapi_call_id
            update_fields.append("customer_call_id")

        vapi_call_data = getattr(ce, "vapi_call_data", None)
        if not ce.provider_call_data and vapi_call_data:
            wrapped = _wrap_provider_payload(vapi_call_data)
            if wrapped is not None:
                ce.provider_call_data = wrapped
                update_fields.append("provider_call_data")

        if update_fields:
            ce.save(update_fields=update_fields)

    # Backfill CallExecutionSnapshot records
    for snap in CallExecutionSnapshot.objects.all():
        update_fields = []

        vapi_call_id = getattr(snap, "vapi_call_id", None)
        if not snap.service_provider_call_id and vapi_call_id:
            snap.service_provider_call_id = vapi_call_id
            update_fields.append("service_provider_call_id")

        vapi_call_data = getattr(snap, "vapi_call_data", None)
        if not snap.provider_call_data and vapi_call_data:
            wrapped = _wrap_provider_payload(vapi_call_data)
            if wrapped is not None:
                snap.provider_call_data = wrapped
                update_fields.append("provider_call_data")

        if update_fields:
            snap.save(update_fields=update_fields)

class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0062_merge_20251231_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callexecution',
            name='logUrl',
        ),
        migrations.AddField(
            model_name='callexecution',
            name='customer_call_id',
            field=models.CharField(blank=True, help_text='Customer call ID if available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='provider_call_data',
            field=models.JSONField(blank=True, help_text='Complete call data from the provider. Format: dict[provider_name, data] where provider_name must be from SupportedProviders', null=True, validators=[simulate.semantics.validate_provider_sent_objects]),
        ),
        migrations.AddField(
            model_name='callexecution',
            name='service_provider_call_id',
            field=models.CharField(blank=True, help_text='Service provider call ID for tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callexecutionsnapshot',
            name='provider_call_data',
            field=models.JSONField(blank=True, null=True, validators=[simulate.semantics.validate_provider_sent_objects]),
        ),
        migrations.AddField(
            model_name='callexecutionsnapshot',
            name='service_provider_call_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='analysis_data',
            field=models.JSONField(blank=True, help_text='Call analysis data from the service provider', null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='Assistant ID used for the call (system side)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='call_summary',
            field=models.TextField(blank=True, help_text='Call summary from the service', null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='customer_log_url',
            field=models.URLField(blank=True, help_text='Customer call log URL from the service provider', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the call ended', null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='evaluation_data',
            field=models.JSONField(blank=True, help_text='Call evaluation data from the service provider', null=True),
        ),
        migrations.AlterField(
            model_name='callexecution',
            name='logs_ingested_at',
            field=models.DateTimeField(blank=True, help_text='When call logs were last ingested from the provider', null=True),
        ),
        migrations.RunPython(backfill_updated_fields_call_execution, migrations.RunPython.noop),
    ]
