# Generated by Django 5.1.8 on 2026-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0062_merge_20251231_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='regional_mix',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('light', 'Light')], help_text='Regional mix for the persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='simulation_type',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', help_text='Type of simulation for the persona', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='slang_usage',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('light', 'Light')], help_text='Slang usage for the persona', max_length=20, null=True),
        ),
    ]
