# Generated by Django - Prompt Simulation Feature

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0050_alter_feedback_options_feedback_organization_and_more'),
        ('simulate', '0063_alter_persona_regional_mix_and_more'),
    ]

    operations = [
        # Add source_type field to Scenarios
        migrations.AddField(
            model_name='scenarios',
            name='source_type',
            field=models.CharField(
                choices=[('agent_definition', 'Agent Definition'), ('prompt', 'Prompt')],
                default='agent_definition',
                help_text='Source type for the scenario: agent_definition or prompt',
                max_length=20,
            ),
        ),
        # Add prompt_template foreign key to Scenarios
        migrations.AddField(
            model_name='scenarios',
            name='prompt_template',
            field=models.ForeignKey(
                blank=True,
                help_text='Prompt template associated with this scenario (only for prompt source type)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scenarios',
                to='model_hub.prompttemplate',
            ),
        ),
        # Add prompt_version foreign key to Scenarios
        migrations.AddField(
            model_name='scenarios',
            name='prompt_version',
            field=models.ForeignKey(
                blank=True,
                help_text='Prompt version associated with this scenario (only for prompt source type)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scenarios',
                to='model_hub.promptversion',
            ),
        ),
        # Add source_type field to RunTest
        migrations.AddField(
            model_name='runtest',
            name='source_type',
            field=models.CharField(
                choices=[('agent_definition', 'Agent Definition'), ('prompt', 'Prompt')],
                default='agent_definition',
                help_text='Source type for the test run: agent_definition or prompt',
                max_length=20,
            ),
        ),
        # Add prompt_template foreign key to RunTest
        migrations.AddField(
            model_name='runtest',
            name='prompt_template',
            field=models.ForeignKey(
                blank=True,
                help_text='Prompt template for this test run (only for prompt source type)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='run_tests',
                to='model_hub.prompttemplate',
            ),
        ),
        # Add prompt_version foreign key to RunTest
        migrations.AddField(
            model_name='runtest',
            name='prompt_version',
            field=models.ForeignKey(
                blank=True,
                help_text='Prompt version for this test run (only for prompt source type)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='run_tests',
                to='model_hub.promptversion',
            ),
        ),
    ]
