# Generated by Django 5.1.8 on 2026-01-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0063_remove_callexecution_logurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callexecution',
            name='customer_vapi_call_id',
        ),
        migrations.RemoveField(
            model_name='callexecution',
            name='vapi_call_data',
        ),
        migrations.RemoveField(
            model_name='callexecution',
            name='vapi_call_id',
        ),
        migrations.RemoveField(
            model_name='callexecutionsnapshot',
            name='vapi_call_data',
        ),
        migrations.RemoveField(
            model_name='callexecutionsnapshot',
            name='vapi_call_id',
        ),
    ]
