# Generated by Django 5.1.8 on 2026-01-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0063_alter_persona_regional_mix_and_more'),
        ('simulate', '0064_remove_callexecution_customer_vapi_call_id_and_more'),
    ]

    operations = [
    ]
