# Generated by Django 5.1.8 on 2026-01-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0064_add_prompt_simulation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpromptoptimiserrun',
            name='optimiser_type',
            field=models.CharField(choices=[('random_search', 'Random Search'), ('gepa', 'GEPA'), ('protegi', 'Protegi'), ('bayesian', 'Bayesian'), ('metaprompt', 'Metaprompt'), ('promptwizard', 'PromptWizard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='runtest',
            name='agent_definition',
            field=models.ForeignKey(blank=True, help_text='Agent definition for this test run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_tests', to='simulate.agentdefinition'),
        ),
    ]
