# Generated by Django 5.1.8 on 2026-01-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0065_make_agent_definition_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callexecution',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number called (null for TEXT/chat simulations)', max_length=20, null=True),
        ),
    ]
