# Generated by Django 5.1.8 on 2026-02-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0065_merge_20260115_1844'),
        ('simulate', '0066_make_phone_number_nullable'),
    ]

    operations = [
    ]
