# Generated by Django 5.1.8 on 2026-02-23 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('simulate', '0067_merge_20260203_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSimulatorAssistant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('system_prompt', models.TextField()),
                ('model', models.CharField(max_length=512)),
                ('temperature', models.FloatField(default=0.9)),
                ('max_tokens', models.IntegerField(default=800)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_simulator_assistants', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_simulator_assistants', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSimulatorSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=50)),
                ('has_chat_ended', models.BooleanField(default=False)),
                ('total_tokens', models.IntegerField(default=0)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simulate.chatsimulatorassistant')),
                ('call_execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_simulator_session', to='simulate.callexecution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_simulator_sessions', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_simulator_sessions', to='accounts.workspace')),
            ],
        ),
    ]
