# Generated by Django 5.1.8 on 2026-02-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0068_rename_vapi_phone_number_id_to_provider_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callexecution',
            name='storage_cost_cents',
            field=models.FloatField(blank=True, help_text='S3 recording storage cost in cents', null=True),
        ),
    ]
