# Generated by Django 5.1.8 on 2026-03-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0068_chatsimulatorassistant_chatsimulatorsession'),
        ('simulate', '0069_callexecution_storage_cost_cents'),
    ]

    operations = [
    ]
