# Generated by Django 5.1.8 on 2026-04-11 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_credentials(apps, schema_editor):
    """Migrate api_key and assistant_id from AgentDefinition to ProviderCredentials.

    Uses encrypt_token directly since historical models don't run
    the custom save() method.
    """
    from agentcc.services.credential_manager import encrypt_token

    AgentDefinition = apps.get_model("simulate", "AgentDefinition")
    ProviderCredentials = apps.get_model("simulate", "ProviderCredentials")

    for agent_def in AgentDefinition.objects.all():
        api_key = getattr(agent_def, "api_key", "") or ""
        assistant_id = getattr(agent_def, "assistant_id", "") or ""

        if not api_key:
            continue

        provider = agent_def.provider or "vapi"
        provider_type = "retell" if provider == "retell" else "vapi"

        ProviderCredentials.objects.create(
            agent_definition=agent_def,
            provider_type=provider_type,
            api_key=encrypt_token(api_key) if api_key else "",
            assistant_id=assistant_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0070_merge_20260303_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredentials',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('vapi', 'Vapi'), ('retell', 'Retell'), ('livekit', 'LiveKit')], max_length=50)),
                ('api_key', models.TextField(blank=True, default='')),
                ('api_secret', models.TextField(blank=True, default='')),
                ('assistant_id', models.CharField(blank=True, default='', max_length=255)),
                ('server_url', models.URLField(blank=True, default='', max_length=500)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('config_json', models.JSONField(blank=True, default=dict, null=True)),
                ('max_concurrency', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('agent_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='simulate.agentdefinition')),
            ],
            options={
                'verbose_name': 'Provider Credentials',
                'verbose_name_plural': 'Provider Credentials',
                'db_table': 'simulate_provider_credentials',
            },
        ),
        migrations.RunPython(backfill_credentials, migrations.RunPython.noop),
    ]
