# Generated by Django 5.1.8 on 2026-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0070_merge_20260303_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error'), ('Cancelled', 'Cancelled')], default='Running', help_text='Status of the scenario', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulateevalconfig',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Editing', 'Editing'), ('Inactive', 'Inactive'), ('Failed', 'Failed'), ('PartialRun', 'Partial Run'), ('ExperimentEvaluation', 'Experiment Evaluation'), ('Uploading', 'Uploading'), ('PartialExtracted', 'Partial Extracted'), ('Processing', 'Processing'), ('Deleting', 'Deleting'), ('PartialCompleted', 'Partial Completed'), ('OptimizationEvaluation', 'Optimization Evaluation'), ('Error', 'Error'), ('Cancelled', 'Cancelled')], default='Completed', max_length=50),
        ),
    ]
