# Generated by Django 5.1.8 on 2026-04-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0071_provider_credentials'),
        ('simulate', '0072_alter_scenarios_status_and_more'),
    ]

    operations = [
    ]
