# Generated by Django 5.1.8 on 2026-02-03 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name', max_length=255)),
                ('type', models.CharField(choices=[('workflow', 'Workflow'), ('module', 'Module')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_playground_graphs', to='accounts.organization')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_playground_graphs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'agent_playground_graph',
            },
        ),
        migrations.CreateModel(
            name='GraphVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active')], help_text='Version status (None for historical versions)', max_length=20, null=True)),
                ('tags', models.JSONField(default=list)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agent_playground.graph')),
            ],
            options={
                'db_table': 'agent_playground_graph_version',
            },
        ),
        migrations.CreateModel(
            name='GraphExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('output_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='agent_playground.graphversion')),
            ],
            options={
                'db_table': 'agent_playground_graph_execution',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('module', 'Module'), ('atomic', 'Atomic')], help_text="'module' for module nodes, 'atomic' for nodes using a NodeTemplate", max_length=20)),
                ('name', models.CharField(help_text='Display name', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Node-specific configuration (validated against node_template.config_schema for atomic nodes)')),
                ('position', models.JSONField(default=dict, help_text='UI coordinates {"x": 0, "y": 0}')),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agent_playground.graphversion')),
                ('ref_graph_version', models.ForeignKey(blank=True, help_text='If set: This node references a reusable module', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by_nodes', to='agent_playground.graphversion')),
            ],
            options={
                'db_table': 'agent_playground_node',
            },
        ),
        migrations.CreateModel(
            name='NodeExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('graph_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_executions', to='agent_playground.graphexecution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='agent_playground.node')),
            ],
            options={
                'db_table': 'agent_playground_node_execution',
            },
        ),
        migrations.AddField(
            model_name='graphexecution',
            name='parent_node_execution',
            field=models.ForeignKey(blank=True, help_text='If the graph is a module, the parent node calling this', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_graph_executions', to='agent_playground.nodeexecution'),
        ),
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('icon', models.URLField(blank=True, max_length=1000, null=True)),
                ('categories', models.JSONField(default=list)),
                ('input_definition', models.JSONField(default=list)),
                ('output_definition', models.JSONField(default=list)),
                ('input_mode', models.CharField(choices=[('strict', 'Strict'), ('extensible', 'Extensible'), ('dynamic', 'Dynamic')], max_length=20)),
                ('output_mode', models.CharField(choices=[('strict', 'Strict'), ('extensible', 'Extensible'), ('dynamic', 'Dynamic')], max_length=20)),
                ('config_schema', models.JSONField(default=dict, help_text='JSON Schema for Node.config validation')),
            ],
            options={
                'db_table': 'agent_playground_node_template',
                'indexes': [models.Index(fields=['categories'], name='agent_playg_categor_26d4aa_idx'), models.Index(fields=['name'], name='agent_playg_name_d238ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('name',), name='unique_node_template_name')],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='node_template',
            field=models.ForeignKey(blank=True, help_text='If set: References a node template (for atomic nodes). Null for module nodes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='agent_playground.nodetemplate'),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Identifier (e.g., 'prompt', 'result')", max_length=100)),
                ('direction', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=10)),
                ('data_schema', models.JSONField(default=dict, help_text='JSON Schema for validation')),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='agent_playground.node')),
            ],
            options={
                'db_table': 'agent_playground_port',
            },
        ),
        migrations.CreateModel(
            name='ExecutionData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='The actual data')),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_data', to='agent_playground.node')),
                ('node_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_data', to='agent_playground.nodeexecution')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_data', to='agent_playground.port')),
            ],
            options={
                'db_table': 'agent_playground_execution_data',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='agent_playground.graphversion')),
                ('source_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='agent_playground.port')),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='agent_playground.port')),
            ],
            options={
                'db_table': 'agent_playground_edge',
            },
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['workspace', 'type'], name='agent_playg_workspa_79211d_idx'),
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['organization', 'type'], name='agent_playg_organiz_54c204_idx'),
        ),
        migrations.AddIndex(
            model_name='graphversion',
            index=models.Index(fields=['graph', 'status'], name='agent_playg_graph_i_7037a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('graph', 'version_number'), name='unique_graph_version_number'),
        ),
        migrations.AddIndex(
            model_name='nodeexecution',
            index=models.Index(fields=['graph_execution', 'status'], name='agent_playg_graph_e_737d11_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecution',
            index=models.Index(fields=['node'], name='agent_playg_node_id_131bf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodeexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('graph_execution', 'node'), name='unique_graph_execution_node'),
        ),
        migrations.AddIndex(
            model_name='graphexecution',
            index=models.Index(fields=['graph_version', 'status'], name='agent_playg_graph_v_7caf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='graphexecution',
            index=models.Index(fields=['parent_node_execution'], name='agent_playg_parent__b84ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['graph_version', 'type'], name='agent_playg_graph_v_084ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['ref_graph_version'], name='agent_playg_ref_gra_3fd646_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_template'], name='agent_playg_node_te_09b81a_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['node', 'direction'], name='agent_playg_node_id_99ef81_idx'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('node', 'key'), name='unique_node_port_key'),
        ),
        migrations.AddIndex(
            model_name='executiondata',
            index=models.Index(fields=['node_execution'], name='agent_playg_node_ex_88fc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='executiondata',
            index=models.Index(fields=['node'], name='agent_playg_node_id_6416ca_idx'),
        ),
        migrations.AddIndex(
            model_name='executiondata',
            index=models.Index(fields=['port'], name='agent_playg_port_id_93c621_idx'),
        ),
        migrations.AddIndex(
            model_name='executiondata',
            index=models.Index(fields=['is_valid', 'port'], name='agent_playg_is_vali_195f37_idx'),
        ),
        migrations.AddConstraint(
            model_name='executiondata',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('node_execution', 'port'), name='unique_node_execution_port'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph_version'], name='agent_playg_graph_v_1076d4_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['source_port'], name='agent_playg_source__40cbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['target_port'], name='agent_playg_target__38d8a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('source_port', 'target_port'), name='unique_edge_connection'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('target_port',), name='unique_input_connection'),
        ),
    ]
