# Generated by Django 5.1.8 on 2026-02-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_agent_playground_graphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graph',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agent_playground_graphs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphversion',
            name='commit_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
