# Generated by Django 5.1.8 on 2026-02-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0002_graph_collaborators_graph_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='Version status (inactive for historical versions)', max_length=20),
        ),
    ]
