# Generated by Django 5.1.8 on 2026-02-05 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_module_to_subgraph(apps, schema_editor):
    """Rename all Node.type='module' to 'subgraph'."""
    Node = apps.get_model("agent_playground", "Node")
    Node.objects.filter(type="module").update(type="subgraph")


def rename_subgraph_to_module(apps, schema_editor):
    """Reverse: rename all Node.type='subgraph' back to 'module'."""
    Node = apps.get_model("agent_playground", "Node")
    Node.objects.filter(type="subgraph").update(type="module")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('agent_playground', '0003_alter_graphversion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='graph',
            name='agent_playg_workspa_79211d_idx',
        ),
        migrations.RemoveIndex(
            model_name='graph',
            name='agent_playg_organiz_54c204_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "agent_playground_graph" DROP COLUMN IF EXISTS "type";',
                    reverse_sql='ALTER TABLE "agent_playground_graph" ADD COLUMN IF NOT EXISTS "type" varchar(50);',
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='graph',
                    name='type',
                ),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graph',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_agent_playground_graphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graph',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_playground_graphs', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_template',
            field=models.ForeignKey(blank=True, help_text='If set: References a node template (for atomic nodes). Null for subgraph nodes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='agent_playground.nodetemplate'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ref_graph_version',
            field=models.ForeignKey(blank=True, help_text='If set: This node references a reusable subgraph', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by_nodes', to='agent_playground.graphversion'),
        ),
        migrations.RunPython(
            rename_module_to_subgraph,
            rename_subgraph_to_module,
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('subgraph', 'Subgraph'), ('atomic', 'Atomic')], help_text="'subgraph' for subgraph nodes, 'atomic' for nodes using a NodeTemplate", max_length=20),
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['workspace'], name='agent_playg_workspa_6e0a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['organization'], name='agent_playg_organiz_8d2da6_idx'),
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['is_template'], name='agent_playg_is_temp_7a05dd_idx'),
        ),
    ]
