# Generated by Django 5.1.8 on 2026-02-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('agent_playground', '0004_remove_graph_agent_playg_workspa_79211d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='port',
            name='unique_node_port_key',
        ),
        migrations.AddField(
            model_name='port',
            name='display_name',
            field=models.CharField(help_text='User-facing name for the port', max_length=100),
        ),
        migrations.AlterField(
            model_name='graph',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_playground_graphs', to='accounts.workspace'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('key', 'custom'), _negated=True)), fields=('node', 'key'), name='unique_node_port_key'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('node', 'display_name'), name='unique_node_port_display_name'),
        ),
    ]
