# Generated by Django 5.1.8 on 2026-02-27 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0005_remove_port_unique_node_port_key_port_display_name_and_more'),
        ('model_hub', '0050_alter_dataset_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphDataset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_dataset', to='model_hub.dataset')),
                ('graph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_dataset', to='agent_playground.graph')),
            ],
            options={
                'db_table': 'agent_playground_graph_dataset',
            },
        ),
    ]
