# Generated by Django 5.1.8 on 2026-03-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0006_graphdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='ref_port',
            field=models.ForeignKey(blank=True, help_text='For subgraph node ports: links to the corresponding port in the child graph', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_ports', to='agent_playground.port'),
        ),
    ]
