# Generated by Django 5.1.8 on 2026-03-12 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_playground", "0007_port_ref_port"),
        ("model_hub", "0070_migrate_assigned_to_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplateNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_template_node",
                        to="agent_playground.node",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompt_template_nodes",
                        to="model_hub.prompttemplate",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompt_template_nodes",
                        to="model_hub.promptversion",
                    ),
                ),
            ],
            options={
                "db_table": "agent_playground_prompt_template_node",
            },
        ),
    ]
