# Generated by Django 5.1.8 on 2026-03-12 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0007_port_ref_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_connections', to='agent_playground.graphversion')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='agent_playground.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='agent_playground.node')),
            ],
            options={
                'db_table': 'agent_playground_node_connection',
                'indexes': [models.Index(fields=['graph_version'], name='agent_playg_graph_v_25e17a_idx'), models.Index(fields=['source_node'], name='agent_playg_source__abca07_idx'), models.Index(fields=['target_node'], name='agent_playg_target__c7a0ae_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('source_node', 'target_node'), name='unique_node_connection')],
            },
        ),
    ]
