# Generated by Django 5.1.8 on 2026-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0008_nodeconnection'),
        ('agent_playground', '0008_prompttemplatenode'),
    ]

    operations = [
    ]
