# Generated by Django 5.1.8 on 2026-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0009_merge_0008_nodeconnection_0008_prompttemplatenode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('graph_version', 'name'), name='unique_node_name_per_graph_version'),
        ),
    ]
