# Generated by Django 5.1.8 on 2026-04-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_playground', '0010_node_unique_node_name_per_graph_version'),
        ('model_hub', '0070_migrate_assigned_to_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplatenode',
            name='prompt_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_template_nodes', to='model_hub.prompttemplate'),
        ),
        migrations.AlterField(
            model_name='prompttemplatenode',
            name='prompt_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_template_nodes', to='model_hub.promptversion'),
        ),
    ]
