# Generated by Django 5.1.8 on 2025-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
