# Generated by Django 5.1.8 on 2025-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('access', 'Access'), ('refresh', 'Refresh')], max_length=255, null=True),
        ),
    ]
