# Generated by Django 5.1.8 on 2025-08-22 08:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authtoken_auth_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSMarketplaceCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_identifier', models.CharField(help_text='AWS Marketplace Customer Identifier', max_length=255, unique=True)),
                ('customer_aws_account_id', models.CharField(help_text="Customer's AWS Account ID", max_length=255)),
                ('product_code', models.CharField(help_text='AWS Marketplace Product Code', max_length=255)),
                ('product_id', models.CharField(blank=True, help_text='AWS Marketplace Product ID', max_length=255, null=True)),
                ('agreement_id', models.CharField(blank=True, help_text='AWS Marketplace Agreement ID', max_length=255, null=True)),
                ('subscription_status', models.CharField(choices=[('subscribe-success', 'Subscribe Success'), ('subscribe-pending', 'Subscribe Pending'), ('subscribe-fail', 'Subscribe Fail'), ('unsubscribe-pending', 'Unsubscribe Pending'), ('unsubscribe-success', 'Unsubscribe Success')], default='subscribe-pending', max_length=50)),
                ('entitlements', models.JSONField(default=dict, help_text='Current entitlements from AWS Marketplace')),
                ('registration_token', models.TextField(blank=True, help_text='Last registration token received', null=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aws_marketplace_customer', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'AWS Marketplace Customer',
                'verbose_name_plural': 'AWS Marketplace Customers',
            },
        ),
    ]
