# Generated by Django 5.1.8 on 2025-08-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_organization_role_organizationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgapikey',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws_api_keys', to='accounts.workspace'),
        ),
    ]
