# Generated by Django 5.1.8 on 2025-08-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_awsmarketplacecustomer'),
        ('accounts', '0005_orgapikey_workspace'),
    ]

    operations = [
    ]
