# Generated by Django 5.1.8 on 2025-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_ws_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgapikey',
            options={},
        ),
        migrations.AddConstraint(
            model_name='orgapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('type', 'system')), fields=('organization', 'type'), name='unique_system_api_key_per_org_not_deleted', violation_error_message='Only one system API key is allowed per organization.'),
        ),
    ]
