# Generated by Django 5.1.8 on 2025-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250826_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member'), ('Viewer', 'Viewer'), ('workspace_admin', 'Workspace Admin'), ('workspace_member', 'Workspace Member'), ('workspace_viewer', 'Workspace Viewer')], default='Member', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member'), ('Viewer', 'Viewer'), ('workspace_admin', 'Workspace Admin'), ('workspace_member', 'Workspace Member'), ('workspace_viewer', 'Workspace Viewer')], default='Owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member'), ('Viewer', 'Viewer'), ('workspace_admin', 'Workspace Admin'), ('workspace_member', 'Workspace Member'), ('workspace_viewer', 'Workspace Viewer')], default='workspace_member', max_length=20),
        ),
    ]
