# Generated by Django 5.1.8 on 2025-09-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organizationmembership_role_and_more'),
        ('accounts', '0006_organization_ws_enabled_and_more'),
    ]

    operations = [
    ]
