# Generated by Django 5.1.8 on 2025-09-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_orgapikey_options_and_more'),
        ('accounts', '0007_merge_20250903_1403'),
    ]

    operations = [
    ]
