# Generated by Django 5.1.8 on 2025-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_organizationmembership_role_and_more'),
        ('accounts', '0008_merge_20250904_1413'),
    ]

    operations = [
    ]
