# Generated by Django 5.1.8 on 2025-09-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250905_1045'),
        ('accounts', '0009_merge_20250905_1157'),
    ]

    operations = [
    ]
