# Generated by Django 5.1.8 on 2025-09-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250905_1827'),
        ('accounts', '0010_merge_20250905_1241'),
    ]

    operations = [
    ]
