# Generated by Django 5.1.8 on 2025-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250908_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.JSONField(blank=True, default=None, help_text="List of user's goals for using the platform", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, help_text="User's job role (e.g., Data Scientist, ML Engineer, or custom role)", max_length=255, null=True),
        ),
    ]
