# Generated by Django 5.1.8 on 2025-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_goals_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization_role',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member'), ('Viewer', 'Viewer'), ('workspace_admin', 'Workspace Admin'), ('workspace_member', 'Workspace Member'), ('workspace_viewer', 'Workspace Viewer')], default='Owner', max_length=20, null=True),
        ),
    ]
