# Generated by Django 5.1.8 on 2026-03-08 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_2fa_enforced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_2fa_grace_period_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(15, 'Owner'), (8, 'Admin'), (3, 'Member'), (1, 'Viewer')], help_text='Integer RBAC level. Null means legacy role string is authoritative.', null=True),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_workspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(8, 'Workspace Admin'), (3, 'Workspace Member'), (1, 'Workspace Viewer')], help_text='Integer RBAC level. Null means legacy role string is authoritative.', null=True),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='organization_membership',
            field=models.ForeignKey(blank=True, help_text='Nullable during transition; backfill migration will populate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='accounts.organizationmembership'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ws_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_recovery_code',
            },
        ),
        migrations.CreateModel(
            name='UserTOTPDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_encrypted', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_totp_device',
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(default=list)),
                ('aaguid', models.CharField(blank=True, default='', max_length=36)),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_webauthn_credential',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('member.invited', 'Member Invited'), ('member.removed', 'Member Removed'), ('member.role_updated', 'Member Role Updated'), ('member.reactivated', 'Member Reactivated'), ('member.deactivated', 'Member Deactivated'), ('invite.resent', 'Invite Resent'), ('invite.cancelled', 'Invite Cancelled'), ('workspace_member.added', 'Workspace Member Added'), ('workspace_member.removed', 'Workspace Member Removed'), ('workspace_member.role_updated', 'Workspace Member Role Updated')], max_length=64)),
                ('scope', models.CharField(choices=[('organization', 'Organization'), ('workspace', 'Workspace')], max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'db_table': 'accounts_audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'scope', '-created_at'], name='audit_org_scope_ts')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_email', models.EmailField(db_index=True, max_length=254)),
                ('level', models.PositiveSmallIntegerField(choices=[(15, 'Owner'), (8, 'Admin'), (3, 'Member'), (1, 'Viewer')])),
                ('workspace_access', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(db_index=True, default='Pending', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.organization')),
            ],
            options={
                'db_table': 'accounts_organization_invite',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='organizationinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('organization', 'target_email'), name='unique_pending_invite_per_org_email'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'organization'), name='unique_active_org_membership'),
        ),
    ]
