# Generated by Django 5.1.8 on 2026-03-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgapikey',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('mcp', 'MCP')], default='system', max_length=50),
        ),
    ]
