# Generated by Django 5.1.8 on 2026-03-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_organization_region'),
        ('accounts', '0015_backfill_rbac_data'),
    ]

    operations = [
    ]
