# Generated by Django 5.1.8 on 2026-03-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_orgapikey_type'),
        ('accounts', '0015_backfill_rbac_data'),
    ]

    operations = [
    ]
