# Generated by Django 5.1.8 on 2026-03-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_0014_0015'),
        ('accounts', '0016_merge_20260316_1144'),
    ]

    operations = [
    ]
