# Generated by Django 5.1.8 on 2026-03-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_0016_merge_0014_0015_0016_merge_20260316_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedKeyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Blocked Key',
                'verbose_name_plural': 'Blocked IPs & Users (Redis)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
