# Generated by Django 5.1.8 on 2026-04-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_eval_template_version'),
        ('accounts', '0018_blockedkeyproxy'),
    ]

    operations = [
    ]
