# Generated by Django 5.1.8 on 2026-02-12 10:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_user_organization_role'),
        ('tracer', '0046_replaysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('langfuse', 'Langfuse')], max_length=50)),
                ('display_name', models.CharField(max_length=255)),
                ('host_url', models.URLField(max_length=500)),
                ('encrypted_credentials', models.BinaryField()),
                ('ca_certificate', models.TextField(blank=True, null=True)),
                ('external_project_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('syncing', 'Syncing'), ('backfilling', 'Backfilling')], default='active', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('sync_interval_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(1800)])),
                ('last_error_notified_at', models.DateTimeField(blank=True, null=True)),
                ('backfill_from', models.DateTimeField(blank=True, null=True)),
                ('backfill_completed', models.BooleanField(default=False)),
                ('backfill_progress', models.JSONField(blank=True, default=dict)),
                ('total_traces_synced', models.PositiveIntegerField(default=0)),
                ('total_spans_synced', models.PositiveIntegerField(default=0)),
                ('total_scores_synced', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_connections', to='tracer.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='accounts.workspace')),
            ],
            options={
                'db_table': 'integrations_connection',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited'), ('no_new_data', 'No New Data')], default='partial', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('traces_fetched', models.PositiveIntegerField(default=0)),
                ('traces_created', models.PositiveIntegerField(default=0)),
                ('traces_updated', models.PositiveIntegerField(default=0)),
                ('spans_synced', models.PositiveIntegerField(default=0)),
                ('scores_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('sync_from', models.DateTimeField(blank=True, null=True)),
                ('sync_to', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integrationconnection')),
            ],
            options={
                'db_table': 'integrations_sync_log',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['organization', 'platform', 'status'], name='idx_intconn_org_plat_status'),
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['status', 'last_synced_at'], name='idx_intconn_status_lastsync'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('organization', 'workspace', 'platform', 'external_project_name'), name='uq_intconn_org_ws_plat_extproj'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['connection', 'started_at'], name='idx_synclog_conn_started'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['connection', 'status'], name='idx_synclog_conn_status'),
        ),
    ]
