# Generated by Django 5.1.8 on 2026-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='platform',
            field=models.CharField(choices=[('langfuse', 'Langfuse'), ('datadog', 'Datadog'), ('posthog', 'PostHog'), ('pagerduty', 'PagerDuty'), ('mixpanel', 'Mixpanel'), ('cloud_storage', 'Cloud Storage'), ('message_queue', 'Message Queue')], max_length=50),
        ),
    ]
